### ISSUE TITLE
Simple way to control security cam lights

### ISSUE THREAD

**Issue by fullphat** [bropat/eufy-security-client#10]
Could someone help me with a how-to guide to control the outdoor security camera floodlights?  Ideally I would like to expose this feature in HomeKit via HomeBridge.

Thanks!

**Comment by schliemann** [comment]
As I read the eufy-security-client code. It is not possible currently. I don't know if this https://github.com/bropat/eufy-security-client/blob/8d6b7851e7ba7a33e1ebb98c0946d94e62b97c53/src/http/types.ts#L73 referes to the actual floodlights. Only @bropat can clarify this.

**Comment by schliemann** [comment]
@fullphat 

Looks like @bropat is already working on this.

https://github.com/bropat/ioBroker.eufy-security/issues/133

**Comment by bropat** [comment]
@schliemann 
This functionality has already been implemented in the current dev code (not yet published).
I am currently working on a major update... ;)

**Comment by bropat** [comment]
Feature was implemented in version 0.9.0 (among others ;) )
