### ISSUE TITLE
[Question]: Snapshot - is there a hope?

### ISSUE THREAD

**Issue by schliemann** [bropat/eufy-security-client#101]
### Ask your question

I read the closed issue here:

https://github.com/bropat/eufy-security-client/issues/58

And thought I would ask again if there were still no hope for a screenshot command. I got to think about the supoort for it in the homekit(apple) integration for the cameras. Every 10 seconds it makes a new snapshot. Do you think this is done by livestreaming or some other means?

https://user-images.githubusercontent.com/10818044/149137891-b4f0cd57-a3bc-44a0-9023-40ee1f6ae532.MOV

**Comment by fullphat** [comment]
If it helps, this is how the ffmpeg HomeBridge plugin does it:

```
[1/11/2022, 9:17:21 PM] [Camera FFmpeg] [Ext Front Doorbell] Snapshot command: /usr/local/lib/node modules/homebridge-camera-ffmpeg/node modules/ffmpeg-for-homebridge/ffmpeg
-i rtsp://192.168.2.2/live0 -frames:v 1 -f image2
- -hide_banner -loglevel error
```

Not sure if the RTSP url could be replaced with the socket detail?

**Comment by schliemann** [comment]
> If it helps, this is how the ffmpeg HomeBridge plugin does it:
> 
> ```
> [1/11/2022, 9:17:21 PM] [Camera FFmpeg] [Ext Front Doorbell] Snapshot command: /usr/local/lib/node modules/homebridge-camera-ffmpeg/node modules/ffmpeg-for-homebridge/ffmpeg
> -i rtsp://192.168.2.2/live0 -frames:v 1 -f image2
> - -hide_banner -loglevel error
> ```
> 
> Not sure if the RTSP url could be replaced with the socket detail?

The problem is that the accumulated time for fetching snapshots in homebridge takes some time. 

**Disclaimer Homekit/Homebridge stuff**
A HomeKit bridge can only respond to one request at a time. When the cameras are bridged, when a snapshot is being pulled all other traffic is blocked. Using unbridge mode for the cameras allows them all to respond independently - but that does have some caveats.
**Homekit/Homebridge stuff done**

The times for generating a snapshot is as far as I can see
getLocalLiveStream() takes     2.178seconds
ffmpeg.spawn() takes             0.022seconds
pipe() takes                             0.001seconds
ffmpeg.onclose()                    5.223seconds

A snapshot from an image source takes almost no time however.

I do however realize that @bropat has told me before that it is not possible. It is just my naive hope that it was possible :D

**Comment by fullphat** [comment]
I do run most of my other plugins as separate bridges as a matter of course now, not least so if a particular plugin crashes it doesn't take all of HomeBridge down.

However, given that getLocalLiveStream() takes 2.178 seconds and ffmpeg.onclose() 5.223 seconds, surely that impacts the local live stream feature as well?

Is there any reason for the long durations here?  Is it something unique to the P2P side of things?

I still can't quite figure why a snapshot would be different as all you're doing is starting the live stream, capturing a single frame to an image file and then closing the stream.

Unless I'm misunderstanding?

**Comment by schliemann** [comment]
Well. The ffmpeg stuff is not really related to the eufy-client-library. This question was merely a hope that there was some sort of way to obtain an image from the cameras without streaming.

**Comment by fuatakgun** [comment]
I remember there was a similar question from couple of months earlier and the answer was no. Let's see if anything changed

**Comment by fullphat** [comment]
> Well. The ffmpeg stuff is not really related to the eufy-client-library. This question was merely a hope that there was some sort of way to obtain an image from the cameras without streaming.

Understood 👍🏼

**Comment by bropat** [comment]
The screenshot function in the Eufy app is only available during a live stream, in which case the screenshot is taken from the current stream.
I did not notice any other methods in the code of the Eufy app.
So the answer is still the same. However, I am happy to be proven wrong.

**Comment by schliemann** [comment]
@bropat I understand. Are you using the apk to reverse engineer the integrations? I can understand why the app doesn't have this functionality since the screenshot I've attached in the original post is using the Homekit integration - which of course might be a blackbox for you (and me :)). I just wanted to show that the hub might be able to pass snapshots without a livestream.

**Comment by bropat** [comment]
> Are you using the apk to reverse engineer the integrations?

Yes, but not only.
