### ISSUE TITLE
[Bug]: DeviceVideoRecordingQuality incorrect for Eufy 2C Pro cameras

### ISSUE THREAD

**Issue by charlyr82** [bropat/eufy-security-client#102]
### Client version

1.5.0

### Node version

16.13.1

### Operating System type

Docker

### Operating system version

Alpine 3.14

### Describe the bug

My Eufy 2C Pro cameras are reporting a video recording quality of 1, which isn't a valid value according to the DeviceVideoRecordingQuality states list.

I am using the home assistant integration eufy_security (v1.2.2) from fuatakgun, with the eufy-security-ws docker image (v0.7.0) and have been involved with an issue reported for the fuatakgun eufy_security integration: 

Using some temporary debug code that fuatakgun put in to the integration I was getting the following error (from eufy_security):
2022-01-14 08:39:12 ERROR (MainThread) [custom_components.eufy_security] eufy_security - Shed - eufy_security_REDACTED_SHED_SERIALNO_video_recording_quality_select - missing value - value: 1 - values_to_states: {'2': 'Full HD (1080P)', '3': '2K HD'} - states_to_values: {'Full HD (1080P)': '2', '2K HD': '3'}

This error showed that the camera is reporting a video recording quality of 1, but the only recognised values are 2 or 3. The issue with eufy_security (https://github.com/fuatakgun/eufy_security/issues/191) has now been closed, as it was determined that this was an upstream issue, and I was directed by fuatakgun to post an issue on the eufy-security-ws github, but looking at the code I think it is more appropriate to post it here.

I have 4x Eufy 2C Pro cameras, all are set to record in 2K, the "Front" camera, which has RTSP turned on, is restricted to 1080p (apparently a limitation of enabling RTSP) according to the phone app. In this setup all cameras report: `param_type: 1286, param_value: '1'`.

Switching the "Shed" camera to record in 1080p using the phone app then restarting the eufy-security-ws container the shed camera then reports `param_type: 1286, param_value: '2'`, and all the other cameras still report a value of 1 for this parameter. I have not managed to do anything that will give me a value of 3 for this parameter.

I wonder if for the Eufy 2C Pro camera the parameter values are `1: "2K HD", 2: "Full HD (1080P)"`?

I have attached sanitized log files for a clean restart of the eufy-security-ws docker container with the shed camera set to 2K and 1080p.

EDIT: To help find the relevant areas of the log file, you can search for device_id: `4116772` to find the "Shed" camera, or param_id: `127455509` to find parameter 1286 of the "Shed" camera.

### To reproduce

Being an end user, and not using this client library directly, I don't know the proper commands to interact with this library directly, but as a rough guide.
1. Connect to a setup with a Eufy 2C Pro camera set to record in 2K.
2. Ask the 2C Pro what the video recording quality is set to (it will return a value of 1)
3. Look at the states list for video recording quality (or p2p parameter 1286)

### Screenshots & Logfiles

[eufy-security-ws-shed2K-sanitized.log](https://github.com/bropat/eufy-security-client/files/7874758/eufy-security-ws-shed2K-sanitized.log)
[eufy-security-ws-shed1080-sanitized.log](https://github.com/bropat/eufy-security-client/files/7874759/eufy-security-ws-shed1080-sanitized.log)

**Comment by fuatakgun** [comment]
I am closely following issues under these two repositories, i can jump in anytime if help is needed.

**Comment by bropat** [comment]
Thank you for the very clear description. It will be fixed in the next version.

I have never tested this camera myself, if you find something else that doesn't quite match just open a new issue.

**Comment by charlyr82** [comment]
Many thanks for your work on this bropat, I will be sure to report any other issues I find with my 2C Pros, but so far everything else seems to be working well with them.
