### ISSUE TITLE
[Question]: How to turn completely off Eufy cam 2K pan & tilt

### ISSUE THREAD

**Issue by napo-leon** [bropat/eufy-security-client#103]
### Ask your question

Hello all,

I would like to script a simple command to turn completely on / off my  Eufy cam 2K pan & tilt. 
Not stop the stream but turn off like the eufy app when the camera hide physically the lens.

Do you know if it's possible? If yes do you have some example script?

Thank you a lot

**Comment by fuatakgun** [comment]
you can set enabled property of device as true of false. It is same with mobile experience.

**Comment by bropat** [comment]
@fuatakgun has already answered correctly ;)
