### ISSUE TITLE
[Bug]: Invalid configuration for entry sensors

### ISSUE THREAD

**Issue by msbghome** [bropat/eufy-security-client#104]
### Client version

1.5.0

### Node version

-

### Operating System type

Other

### Operating system version

homeassistant

### Describe the bug

I followed the guide to integrate the Eufy devices. Stations, cameras and keypads are correctly configured, but I have an error about the (2) entry sensors. Here is the logs:

> Logger: homeassistant.setup
> Source: setup.py:316
> First occurred: 12:06:27 PM (4 occurrences)
> Last logged: 12:06:29 PM
> 
> Unable to prepare setup for platform eufy_security.binary_sensor: Platform not found (cannot import name 'EntityCategory' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).
> Unable to prepare setup for platform eufy_security.sensor: Platform not found (cannot import name 'EntityCategory' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).
> Unable to prepare setup for platform eufy_security.switch: Platform not found (cannot import name 'EntityCategory' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).
> Unable to prepare setup for platform eufy_security.select: Platform not found (cannot import name 'EntityCategory' from 'homeassistant.helpers.entity' (/usr/src/homeassistant/homeassistant/helpers/entity.py)).

The error is:

> Invalid config
> The following integrations and platforms could not be set up:
> 
> eufy_security.binary_sensor
> eufy_security.sensor
> eufy_security.switch
> eufy_security.select

### To reproduce

2. Click on '...'

### Screenshots & Logfiles

Follow the guide about how to install it.

**Comment by fuatakgun** [comment]
Hey @msbghome, this issue is related to home assistant, not about eufy-security-ws. You have to update your home assistant to latest version, at least December.

If you still have issues, please create it under eufy_security repository.

**Comment by msbghome** [comment]
@fuatakgun right, thank you for the help! After the update it works! Sorry for have posted in the wrong section and thank you for your work.
