### ISSUE TITLE
[Feature request]: Homebase2 mode change or alarm reset notification

### ISSUE THREAD

**Issue by hipsi** [bropat/eufy-security-client#105]
### Describe the solution you'd like

Is it possible for the client to receive notification when the Homebase2 changes mode, and by what method (keypad, app, geo, schedule) and also when an alarm is reset?

**Comment by Palmke** [comment]
@bropat you may want to consider merging this issue with #88, this one is also notification based. I can post the data I see in the client when doing:
- Alarm reset
- mode switch by keypad
- mode switch by app
I cannot do geo or schedule, but I assume they're all from the same enumeration :-)
