### ISSUE TITLE
[Feature request]: Support for OutdoorCam C22 (T8442)

### ISSUE THREAD

**Issue by mualemmi** [bropat/eufy-security-client#106]
### Describe the solution you'd like

This device does not appear in the list of supported devices. I use Homebridge and the contributors asked me to open a ticket for the device.

**Comment by bropat** [comment]
@mualemmi 

Just because it's not listed doesn't necessarily mean it doesn't work.
What does not work?

**Comment by mualemmi** [comment]
When I log in to the Eufy Security Homebridge Plugin I get the Message „No devices found“ and „no Stations found“.

**Comment by bropat** [comment]
This has another cause. It will be fixed in the next version.
