### ISSUE TITLE
No Bug - More a question (and a thank you)

### ISSUE THREAD

**Issue by marcus-j-davies** [bropat/eufy-security-client#11]
So,

I have recently setup some new Indoor 2K P/T cams, they work really well, and being very much a DIY-er, stumbled on this Lib, for which I am very grateful! so thank you!.

I do however, have a question around the P2P/Local interface.

I have set Homekit recording for both Home & Away, but control it via setting `Station.setMotionDetection`.
until Apple Introduce scheduling or the ability to control it via scenes - this library is filling a massive gap for a lot of situations for many people, again Thank you!

But....

if I have all devices and hubs serialised/stored, for which I can pass to the P2P constructor, do I need to call into the official Api each time? or does the `dskkey` change, so much so that I need to call into the official  API before I can do P2P/Local?

I guess my main concern, is that, as this isn't an official approach, Anker could kill it off, and ultimately, break some pretty  well thought  out automation  setups

Many Thanks

EDIT:
All device IP's are static if it makes any difference.

**Comment by bropat** [comment]
Hi,

thank you very much.
The dskkey is needed to connect to the station/device via P2P. Once the connection is established, it is no longer needed as long as the connection is maintained. The library accomplishes this by a keepalive.
The dskkey expires after 30 min.

**Comment by marcus-j-davies** [comment]
Oh nice!

So, in theory once a connection has been established, and maintains as such for say 10 days, it would have been 10 days ago, I needed to call into official API?

**Comment by bropat** [comment]
It depends on the device and functionality,
E.g. for the voice quick response of the doorbell you have to get the voice id via the api or if you want to watch a locally stored video you need the api to get the RSA key to decrypt the video.

**Comment by marcus-j-davies** [comment]
Cool!

This is just to control the motion sensor function (which Homekit uses, to start recordings)

Setting it to `false` stops Homekit being told there is motion, and thus doesn't record, setting it to true of course, reverses that, and Homekit is again notified of motion, and thus starts recording events to iCloud.

Great work!
