### ISSUE TITLE
[Question]: Eufy app src

### ISSUE THREAD

**Issue by martijnpoppen** [bropat/eufy-security-client#111]
### Ask your question

Hi @bropat 
Saw you already implemented the Eufy Home Management.
May I ask how you got the source code from Eufy for app version 4.0.0.
I already tried looking for the APK but it doesn't exist (yet)

For your info: I made the Eufy Homey app. https://homey.app/en-gb/app/com.eufylife.security/Eufy-Security/

Hope you can help me out :)

**Comment by bropat** [comment]
Hi @martijnpoppen,

look [here](https://apkcombo.com/eufy-security/com.oceanwing.battery.cam/). ;)
