### ISSUE TITLE
[Bug]: Docker Container :latest (V0.8.1?) doesn't start

### ISSUE THREAD

**Issue by lolouk44** [bropat/eufy-security-client#115]
### Client version

0.8.1 (:latest)

### Node version

Unavailable

### Operating System type

Docker

### Operating system version

Ubuntu

### Describe the bug

Container not starting

### To reproduce

v0.7.0 works, :latest (0.8.1) doesn't, see below logs

### Screenshots & Logfiles

Portainer logs show this:
`/usr/local/bin/docker-entrypoint.sh: exec: line 11: /usr/src/app/run.sh: not found`

**Comment by bropat** [comment]
wrong repo

**Comment by lolouk44** [comment]
Thanks, didn't realise I was on the wrong repo.
You may want to add a link to the right repo in your Docker description?
By the way this is the same issue as https://github.com/bropat/eufy-security-ws/issues/81
