### ISSUE TITLE
Trigger RTSP recording

### ISSUE THREAD

**Issue by adultano** [bropat/eufy-security-client#118]
### Ask your question

I am using a zigbee contact sensor to trigger a rtsp recording (eufy cam2c). This only works if the camera is „active“ i.e. motion was detected. Otherwise the livestream is not active and ffmeg returns 404. my workaround so far is to turn rtsp off and on again with your adapter and then start recording. This of course results in a couple of seconds delay before the recording can start. Is there any leaner / more efficient ways to do this? The requirement is basically through a blocky script -> contact trigger -> record rtsp stream (or even better record to homebase i/o rtsp but this I think is impossible)

Thanks for sharing your thoughts here.

**Comment by adultano** [comment]
Yeah with Anker's motion sensors you can create an automation to trigger a recording. If this could be made available for other sensors or any type of iobroker trigger would be awesome.

**Comment by adultano** [comment]
If anyone else is struggling, I found a workaround. In the eufy app you can create an automation for which you can use the alarm from homebase as trigger for a camera recording. I set this up and then used a script in iobroker to set homebase alarm = true and immediately false again. As trigger I use a zigbee contact sensor but can literally be any type of trigger in iobroker. Two things to note, i set the volume of the homebase to the lowest and put tape over the speaker at the bottom. Like this the alarm is barely audible. And second, you need to set video length to custom in powersettings. Otherwise it will only record 5 seconds since there might be no movement of the motion sensor. The recordings will be stored to the local memory of the homebase (or whatever default you have) thus enabling also 2k recordings. Hope this helps.

**Comment by hvorragend** [comment]
Is there a chance to get another solution for this request? 

I would like to start a record with my Home Assistant sensors.
