### ISSUE TITLE
Homebridge plugin development

### ISSUE THREAD

**Issue by deanlyoung** [bropat/eufy-security-client#12]
@bropat I am working on porting it over here: https://github.com/deanlyoung/homebridge-eufy-security, but it looks like a few methods and interfaces changed between `eufy-security-client` and the former `eufy-node-client`...

Do you have any recommendations for these portions:
- https://github.com/deanlyoung/homebridge-eufy-security/blob/587ea0dd5ba8d2cd5e09c891ad7dd9c0c38dd24c/src/platform.ts#L10
- https://github.com/deanlyoung/homebridge-eufy-security/blob/587ea0dd5ba8d2cd5e09c891ad7dd9c0c38dd24c/src/platform.ts#L92
- https://github.com/deanlyoung/homebridge-eufy-security/blob/587ea0dd5ba8d2cd5e09c891ad7dd9c0c38dd24c/src/platform.ts#L177
- https://github.com/deanlyoung/homebridge-eufy-security/blob/587ea0dd5ba8d2cd5e09c891ad7dd9c0c38dd24c/src/platform.ts#L190

__Originally posted by @deanlyoung in https://github.com/bropat/eufy-security-client/issues/7#issuecomment-822108580__

**Comment by schliemann** [comment]
As I read your homebridge plugin you never call authenticate on the api. And therefore hubs are never populated. At least that's how I read the eufy-security-client library.

**Comment by schliemann** [comment]
Same with devices not being set.

**Comment by deanlyoung** [comment]
Yeah, I haven't implemented everything yet, but I was starting by using https://github.com/birkir/homebridge-plugin-eufy-security as a template. However, it's built on https://github.com/JanLoebel/eufy-node-client, which has been deprecated in favor of your `eufy-security-client`. It appears that yours has a different structure, which is fine, but it's a bit beyond me in terms of what has been changed / implemented differently.

In VSCode, I get errors, particularly at 92, where it says that `createPushCredentials` is Private, so I can't call it here.

**Comment by schliemann** [comment]
I'm far from an expert in typescript or even this library. I can take a look tonight however.

**Comment by bropat** [comment]
@deanlyoung 
Check out my latest project: [eufy-security-ws](https://github.com/bropat/eufy-security-ws).
This one already uses the new high-level class EufySecurity, which provides a very simplified interface.
In the next days I'll try to publish a first example documentation.

**Comment by schliemann** [comment]
@deanlyoung We have the api running on https://github.com/samemory/homebridge-eufy-security-control changing guard mode. You are welcome to take a peak or even better help extend the features of this repo.
