### ISSUE TITLE
Toggle for Spotlight is missing for Outdoor Cam Pro (T8441)

### ISSUE THREAD

**Issue by jkyselak** [bropat/eufy-security-client#123]
### Ask your question

I noticed that while the Outdoor Cam Pro (T8441) works for the most part, with the eufy_security add-on for Home Assistant. What's missing is the toggle to turn the Spotlight on/off.
Probably because T8441 is not on the list of supported devices.
Any chance of making this toggle available?

Thanks

**Comment by bropat** [comment]
@jkyselak 

This functionality already exists and should only be implemented in the integration you mentioned.

**Comment by luisiam** [comment]
When I try to get the properties from a connected T8441, `light` does not exist in the list. Does something need to be update on this library end?

**Comment by bropat** [comment]
@ping-localhost 

Can you please tell me what device type (number) this unit has?

**Comment by ping-localhost** [comment]
How exactly do I find the device type?

**Comment by ping-localhost** [comment]
How exactly do I find the device type?

**Comment by schliemann** [comment]
On iOS app:

Click three dots on device -> Click cogs -> Click General -> Click About


https://user-images.githubusercontent.com/10818044/169685779-88100006-35e6-4dfa-b9f7-4048b6bafc8d.MOV

**Comment by bropat** [comment]
@ping-localhost 

With `eufy-security-ws` you can do it like this:

```
eufy-security> device.get_properties T8441...
eufy-security> Response: 
{
  type: 'result',
  success: true,
  messageId: 'get_properties',
  result: {
    serialNumber: 'T8441...',
    properties: {
      ...
      model: 'T8441',
      serialNumber: 'T8441...',
      type: 31,
      ...
    }
  }
}
```

I need the value of the property `type`.

**Comment by ping-localhost** [comment]
The value for `type` is `45`.

---

**Relevant log**:

```
eufy-security> device.get_properties T8441PXXXXXXXXXX
eufy-security> Response:
{
  type: 'result',
  success: true,
  messageId: 'get_properties',
  result: {
    serialNumber: 'T8441PXXXXXXXXXX',
    properties: {
      name: {
        value: 'Backyard',
        timestamp: 1653077035000
      },
      model: {
        value: 'T8441',
        timestamp: 1653077035000
      },
      serialNumber: {
        value: 'T8441PXXXXXXXXXX',
        timestamp: 1653077035000
      },
      type: {
        value: 45,
        timestamp: 1653077035000
      },
      hardwareVersion: {
        value: 'P1',
        timestamp: 1653077035000
      },
      softwareVersion: {
        value: '1.0.4.4',
        timestamp: 1649731639000
      },
      stationSerialNumber: {
        value: 'T8441PXXXXXXXXXX',
        timestamp: 1653077035000
      }
    }
  }
}
```

**Comment by bropat** [comment]
Fix will be released in the next version

**Comment by ping-localhost** [comment]
Awesome @bropat. Once it's released I'll ping fuatakgun to update `eufy_security`. 👍

**Comment by ping-localhost** [comment]
Any idea when the next version will be released @bropat 😅

**Comment by bropat** [comment]
@ping-localhost released ;)
