### ISSUE TITLE
[Question]: Floodlight Cam 2 model T8420X

### ISSUE THREAD

**Issue by ema-dev** [bropat/eufy-security-client#124]
Is the Floodlight Cam 2 model T8420X supported?

I have two floodlights (Floodlight Camera T8420 and Floodlight Cam 2 T8420X) that the client successfully connects to and listens for events. There appears to be a problem with the Floodlight Cam 2 T8420X as the client does not receive "motion detected" events. It does however receive "property changed" events. I do receive "motion detected" events for other devices. I see the Floodlight Cam 2 in the supported devices, but it has the model "T8424" instead of "T8420X" (I received the camera as a beta tester). When I compare the "devices" data (response from start_listening command) received from the client for the two floodlights I have, the older floodlight camera model T8420 has more data returned (enabled, motionDetection, and wifiRSSI).

Note to the developers/contributors: Thank you and great job!

**Comment by droiddavid91** [comment]
Having the same issue, but with the T8424 models proper. None of the motionDetected events are received.

**Comment by ema-dev** [comment]
@bropat Would you like me to provide particular logs? Please let me know. Thank you.

**Comment by bropat** [comment]
Hi @ema-dev,

yes i need the eufy-security-client debug logs.

**Comment by bropat** [comment]
Stale
