### ISSUE TITLE
[Feature request]: is it possible to add eufy doorbell dual 2K to supported devices

### ISSUE THREAD

**Issue by venables1** [bropat/eufy-security-client#126]
### Ask your question

Add support in the plug-in to recognise and allow eufy 2K doorbell dual as currently it does not recognise it and comes back with type 91.

**Comment by Palmke** [comment]
I have created a commit in an existing PR for this already. 
My local branch is working fine on it. Currently only default 2K Battery Doorbell (T8210) functionality is supported as I have not figured out the other types of settings to be set.
https://github.com/bropat/eufy-security-client/pull/112/commits/aef27cc495eed94f21d76969c42da6a38275b540

**Comment by mattatcha** [comment]
@bropat I should be able to provide access

**Comment by bropat** [comment]
@mattatcha @venables1 

I don't have much time to work on this project lately, but as soon as I have some again, I'll get back to you.

**Comment by bropat** [comment]
@mattatcha or @venables1 

Could you please share your device with me (i need admin rights):

* patrick.broetto+eu1@gmail.com (for EU)
* patrick.broetto+us1@gmail.com (for US)

Thanks!

**Comment by venables1** [comment]
All done patrick

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bropat** [comment]
@venables1 

Thank you very much!
Some things already work out of the box.
I need a few days to test everything and implement what is missing.

**Comment by venables1** [comment]
Ok perfect thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by bropat** [comment]
@venables1

**Short update:**

All functionalities of the "classic" battery doorbell already work here (incl. livestream).
Now all the special functionalities of this device still need to be implemented.

**Comment by bropat** [comment]
@venables1 

I have implemented just about everything. Now I still have to test everything. Almost finished ;)

**Comment by venables1** [comment]
That is great news thank you for the update

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by venables1** [comment]
Should this be implemented into homebridge eufy security bridge plugin or does that need work aswell I know this is not your plugin but thought I would ask you first as you have developed the fix thanks
