### ISSUE TITLE
How to install this on Home Assistant? [Question]: 

### ISSUE THREAD

**Issue by Xcat2008** [bropat/eufy-security-client#134]
### Ask your question

Hello and i'm sorry. Kinda new to this, but how can i setup this on my Home Assistant? Tryed to apply the repository and always invalid. From what ive read this can be the solution to use my Uefy 2K doorbell properly. What steps i need to apply this addons? Thank you

**Comment by bropat** [comment]
This is a library and cannot be used with HomeAssistant. I think you mean this project: 

https://github.com/fuatakgun/eufy_security
