### ISSUE TITLE
[Bug]: Got AuthResult.OK while invalid token detected function shouldn't return OK

### ISSUE THREAD

**Issue by lenoxys** [bropat/eufy-security-client#136]
### Client version

1.6.6

### Node version

16.2.0

### Operating System type

Linux

### Operating system version

Raspberry

### Describe the bug

Helllo,

```this.driver.api.authenticate```

return ```AuthResult.OK```

while invalid token detected function shouldn't return OK

### To reproduce

Have 2 instances of Eufy Security Client
Login on the first
Login on the second with same credentials
Try to fetch devices on the first

### Screenshots & Logfiles

```
ERROR: Status return code 401, invalidate token { status: 401, statusText: 'Unauthorized' }
ERROR: Status return code not 200 { status: 401, statusText: 'Unauthorized' }
AuthResult.OK
```

**Comment by bropat** [comment]
Hi @lenoxys,

I'm slowly working on version 2.0.0 where this bug is already fixed (the HTTPApi class has been partially revised).
