### ISSUE TITLE
[Question]: is Eufy actively working against attempts to use their API with for example this library?

### ISSUE THREAD

**Issue by andreasnuesslein** [bropat/eufy-security-client#137]
### Ask your question

I've been tinkering with this API for a few hours today and for a while I wouldn't get my Stations (#121) then, all of the sudden they started appearing again and now after a while, the API once again is not showing me any devices - without changes to the code :\

Has anybody else experienced this? Do I need to call some kind of cleanup API call before I exit my program? I checked https://mysecurity.eufylife.com/ for comparison and a) it still works, even if my `npm run` calls don't work anymore and b) it seems to make similar calls (minor differences here and there, e.g. `start_stream` is called via "v2" instead of "v1": https://mysecurity.eufylife.com/apieu/v2/web/equipment/start_stream 

Cheers

**Comment by andreasnuesslein** [comment]
So I did find this https://github.com/bropat/eufy-security-client/issues/57  . At least one other record of this happening. 

I _do_ get a captcha as well now, every time I try logging in via mysecurity.eufylife.com.  Sadly the password reset stuff (from #57) didnt help

**Comment by lenoxys** [comment]
Sometimes it helps to login into the Eufy App.

AFAIK, you need to create a dedicated account to consume API and with admin rights assign.

**Comment by andreasnuesslein** [comment]
hey @lenoxys thank you. yeah I did play around with this and I am using a dedicated account but it keeps getting blocked too, after too many attempts :S

**Comment by lenoxys** [comment]
Yeah we have implanted some throttle mechanism to avoid that. I'm using a lot of caching as well.

**Comment by andreasnuesslein** [comment]
can you give me a pointer what kind of time / rate limit seems to work for you? thanks

**Comment by lenoxys** [comment]
We're doing cache as throttle mechanism combined with using push instead of pulling information. Our user doesn't seems to be affected by being blocked only the dev teams is affected since we're rebooting a lot our script in order to test and sometimes we get blocked.

You can have a look here for the caching : https://github.com/homebridge-eufy-security/plugin/blob/beta/homebridge-ui/server.js

Pretty simple, we get the full list of devices and store it into json file and we force refresh of that file every hour. Users can manually refresh as well if they want.

**Comment by bropat** [comment]
@andreasnuesslein 

> hey @lenoxys thank you. yeah I did play around with this and I am using a dedicated account but it keeps getting blocked too, after too many requests :S

How many requests do you send? Are they all error-free or do you get 401 or other HTTP errors?

**Comment by bropat** [comment]
In the current published stable version of the library there are some bugs in the authentication mechanism. These have already been fixed in the `develop` branch.

**Comment by andreasnuesslein** [comment]
@bropat I didn't send many requests as such. Was just trying to develop a bit of software and therefore I ran the script again and again. 

> In the current published stable version of the library there are some bugs in the authentication mechanism. These have already been fixed in the develop branch.

Cool!


I ended up using https://mysecurity.eufylife.com/ and puppeteer. Now I just grab all videos with wget basically - the URL I get from puppeteer.

**Comment by bropat** [comment]
Eufy has added some new limitations that if they get too many requests you will get an error saying you should slow down ;)

**Comment by andreasnuesslein** [comment]
cool thanks! :)
