### ISSUE TITLE
[Question]: how to know if the Eufy credential uses is from the master

### ISSUE THREAD

**Issue by lenoxys** [bropat/eufy-security-client#138]
### Ask your question

Hello @bropat,

I was looking into the script but I can't figure how to verify if the Eufy credential provided are from a guest account or the master one.

I would like to create a check to warn user when using Eufy master credential, and advise them to create a dedicated Eufy Guest account for the plugin.

Thanks for your help!

**Comment by bropat** [comment]
You can query the following attribute:

```
Station.getRawStation().member.member_type
```

* 0 = Guest
* 1 = Admin
* 2 = Super Admin

`Super Admin` should be the primary account.
