### ISSUE TITLE
Changing guardmode to home (value 1) doesn't trigger a push notification

### ISSUE THREAD

**Issue by schliemann** [bropat/eufy-security-client#14]
When changing guard mode on station to 1 no push notification is generated. 0, 3 and 63 all generate push notifications. Don't know if it is guardModeChanged or currentModeChanged that prevents the call to emit of guard mode.

**this.emit("guard mode", this, message.station_guard_mode, message.station_current_mode);**

https://github.com/bropat/eufy-security-client/blob/master/src/http/station.ts#L288-L290

**Log:**
this.eufyStation.setGuardMode(63);
{"name":"eufyLog","hostname":"raspberrypi","pid":14352,"level":30,"msg":"Alarm mode for station T8010P2320281428 changed to: DISARMED","time":"2021-06-10T21:07:02.384Z","v":0}
{"name":"eufyLog","hostname":"raspberrypi","pid":14352,"level":30,"msg":"Received push notification for changing guard mode { guard_mode: 63, current_mode: 63, stationSN: 'T8010P2320281428' }","time":"2021-06-10T21:07:03.012Z","v":0}

this.eufyStation.setGuardMode(1);

{"name":"eufyLog","hostname":"raspberrypi","pid":14352,"level":30,"msg":"Alarm mode for station T8010P2320281428 changed to: HOME","time":"2021-06-10T21:07:03.726Z","v":0}
{"name":"eufyLog","hostname":"raspberrypi","pid":14352,"level":30,"msg":"Received push notification for changing guard mode { guard_mode: 1, current_mode: 1, stationSN: 'T8010P2320281428' }","time":"2021-06-10T21:07:04.091Z","v":0}

Version 0.8.3

**Comment by bropat** [comment]
@schliemann 

I need the full log of the test to understand the cause, because the guard mode is changed not only by the push notification, but also via the P2P connection (fastest!) or HTTP. Let's say there are several ways to get a change (push, p2p, http) and only the first one leads to an emit.

There is another point in the code that performs the emit and that is [here](https://github.com/bropat/eufy-security-client/blob/master/src/http/station.ts#L533-L536).

**Comment by schliemann** [comment]
Ok. I understand. I'll try to add some more logging and do some more debugging.

**Comment by schliemann** [comment]
@bropat Do you have any recommendations on how to retrieve the full log. I tried to fork your repo and add a bunch of logging. But couldn't get my fork up and running in the homebridge plugin.

**Comment by bropat** [comment]
@schliemann 

Yes, you can simply pass to the [constructor](https://github.com/bropat/eufy-security-client/blob/master/src/eufysecurity.ts#L59) of the class `EufySecurity` a "log" object that supports the following methods:

```typescript
trace: (_message?: any, ..._optionalParams: any[]) => {},
debug: (_message?: any, ..._optionalParams: any[]) => {},
info: (_message?: any, ..._optionalParams: any[]) => {},
warn: (_message?: any, ..._optionalParams: any[]) => {},
error: (_message?: any, ..._optionalParams: any[]) => {},
```

What I need then is that you repeat the error and send me the complete logs in debug level (you can find my mail [here](https://github.com/bropat/eufy-security-client#license)).

**Comment by schliemann** [comment]
You can disregard the email I sent. I just realized the loggers loglevel was info. Might be missing entries. I'll send a new dump tonight.

**Comment by schliemann** [comment]
I have sent a new email with the relevant log file attached.

**Comment by bropat** [comment]
Sorry, but I have very little time at the moment and therefore can not tell you when I can answer you. :(

**Comment by schliemann** [comment]
It's perfectly fine. I understand.

**Comment by bropat** [comment]
Please test the new version 0.9.0.
Now there are 2 separate events "guard mode" and "current mode".

**Comment by schliemann** [comment]
Works. Awesome job, @bropat 👏

**Comment by schliemann** [comment]
Maybe closed this prematurely. Will do some more testing.

**Comment by bropat** [comment]
Any news about it?

**Comment by schliemann** [comment]
@bropat I will try and re-test this.

**Comment by bropat** [comment]
@schliemann 
Do you have any news on this?

**Comment by schliemann** [comment]
@bropat I'm on vacation next week. Will try and verify by then.
