### ISSUE TITLE
Add the Eufy wired dual doorbell T8203

### ISSUE THREAD

**Issue by maferguson** [bropat/eufy-security-client#141]
### Describe the solution you'd like

Device type T8203 is currently unknown.

**Comment by bropat** [comment]
Could you please share your device with me (i need admin rights):

[patrick.broetto+eu1@gmail.com](mailto:patrick.broetto+eu1@gmail.com) (for EU)
[patrick.broetto+us1@gmail.com](mailto:patrick.broetto+us1@gmail.com) (for US)

Thanks!

**Comment by maferguson** [comment]
Thanks for implementing the T8203 wired dual doorbell.
