### ISSUE TITLE
[Bug]: T8520 Lock Push Notifications not working

### ISSUE THREAD

**Issue by xeryax** [bropat/eufy-security-client#144]
### Client version

0.8.4

### Node version

14.18.2

### Operating System type

Docker

### Operating system version

Debian 10

### Describe the bug

Having a problem getting "updates" from my T8520
I just got my eufy t8520 lock, so i dont know much about it... but it seems that the connection is closing to the eufy device, then only updating whenever the poll timer on my frontend is reached, but I dont seem to be getting any PUSH notifications indicating that the "lock status" has changed.

I do see things like: 27 Apr 14:04:20 - [info] Push notification connection successfully established

and when my device is connected for polling:
27 Apr 14:01:25 - [info] Connected to station T8520<SN> on host 192.168.<IP> and port 28019
I get status updates instantly... but not when the device is disconnected for powersave...

I've tried the NodeRed integration, and the HomeAssistant integration, and both seem to be having this issue- so I am opening the bug here because I think this is where the push notificaitons are not being received.

### To reproduce

Connect a eufy T8520 device to your connected account.
Allow the status to be polled, and allow the device to close the connection "for saving battery". and ensure you have received the "Disconnected from station" message.

Either lock or unlock the T8520- The status of the device does not update and no push notifications are received.

### Screenshots & Logfiles

27 Apr 13:59:15 - [info] MQTT connection successfully established
27 Apr 13:59:15 - [info] Successfully registered to MQTT notifications for lock <lock serial #>
27 Apr 13:59:15 - [info] Push notification connection successfully established
27 Apr 13:59:30 - [info] Connected to station <lock serial #> on host <lock Local IP Address> and port 27928
27 Apr 13:59:45 - [info] Initiated closing of connection to station <lock serial #> for saving battery.
27 Apr 13:59:45 - [info] Disconnected from station <lock serial #>
27 Apr 14:01:24 - [info] Stopping modified flows
27 Apr 14:01:24 - [info] Push notification connection closed
27 Apr 14:01:24 - [info] Disconnect from station <lock serial #>
27 Apr 14:01:24 - [info] Stopped modified flows
27 Apr 14:01:24 - [info] MQTT connection closed
27 Apr 14:01:24 - [info] Starting modified flows
27 Apr 14:01:24 - [info] Started modified flows
27 Apr 14:01:25 - [info] Connected to station <lock serial #> on host <lock Local IP Address> and port 28019
27 Apr 14:01:25 - [info] MQTT connection successfully established
27 Apr 14:01:25 - [info] Successfully registered to MQTT notifications for lock <lock serial #>
27 Apr 14:01:25 - [info] Push notification connection successfully established
27 Apr 14:01:40 - [info] Initiated closing of connection to station <lock serial #> for saving battery.
27 Apr 14:01:40 - [info] Disconnected from station <lock serial #>
27 Apr 14:04:20 - [info] Push notification connection successfully established

**Comment by bropat** [comment]
stale
