### ISSUE TITLE
[Feature request]: Add support for setting video type store to NAS

### ISSUE THREAD

**Issue by fabianluque** [bropat/eufy-security-client#147]
### Describe the solution you'd like

Add support for setting the video type to store to NAS as shown in the Eufy app:

![IMG_733220421875-1](https://user-images.githubusercontent.com/5721029/166313544-06f6e1ac-b59a-45fe-9a02-0d7ae3eb8919.jpeg)

(Example from T8400 but it applies to other Eufy cameras with RTSP support)

**Comment by fabianluque** [comment]
@bropat FYI, I can try working on this if you point me in the right direction. As you know, it’s something the app allows today.

**Comment by fuatakgun** [comment]
How is this different than enabling rtsp?

**Comment by fabianluque** [comment]
@fuatakgun Once you have RTSP enabled, you can select how it behaves as you can see in the screenshot: either stream when an event happens or stream 24/7. Options vary based on the camera you have, but the screen is available for all cameras supporting RTSP.

**Comment by fuatakgun** [comment]
i see, i have checked this screen in detailed for battery operated cameras and they don't support continues stream. I thought it is the only option, understood now, thanks

**Comment by bropat** [comment]
@fabianluque 

Has already been implemented in the next version.

**Comment by fabianluque** [comment]
Thanks @bropat! Really appreciate your work and effort!
