### ISSUE TITLE
[Question]: Complete no-cloud access? Possible?

### ISSUE THREAD

**Issue by dookei** [bropat/eufy-security-client#149]
### Ask your question

I have a eufy system(home base, motion sensors, door sensors,cameras etc) and in the past months I have been worried about having security data being sent into the "cloud". I would like to make a local server with home assistant where alarms and cameras storage would be save locally(only).
Is it possible to have access to the cameras and the home base without any internet access ?

**Comment by bropat** [comment]
Not that I know of.

**Comment by dookei** [comment]
Would it be possible to block the internet  access on the router ? And then use this method plus rtps to control the cameras and sensors?

**Comment by psi-4ward** [comment]
Also interested in this question. I would like to use some cams in a network without internet.
