### ISSUE TITLE
All address Tentatives failed

### ISSUE THREAD

**Issue by tjdavisbz** [bropat/eufy-security-client#152]
### Client version

0.8.4

### Node version

0.8.4

### Operating System type

Docker

### Operating system version

Unknown - Unpaid

### Describe the bug

All of my devices show up in HA but the docker log outputs this repeatedly after saying it has successfully registered for MTQQ and notifications.

90m2022-05-07 16:15:12.319 [39m[1m[91mERROR[39m[22m P2PClientProtocol.lookup(): station: T8021P10212112EC - All address lookup tentatives failed.

[90m2022-05-07 16:15:12.319 [39m[1m[94mINFO[39m[22m Timeout connecting to station T8021P10212112EC

### To reproduce

I just have installed the docker container and integration and attempted to use it, no other steps needed.

**Comment by bropat** [comment]
This means that it cannot connect to the unit. In the latest version, new Eufy Cloud servers for the USA were added. Try the latest version.

**Comment by bropat** [comment]
stale
