### ISSUE TITLE
[Question]: No motion detection updates when the notifications of the camera are disabled

### ISSUE THREAD

**Issue by mvanderheijden** [bropat/eufy-security-client#158]
### Ask your question

Hi, I have a Eufycam 2C and noticed that, when the notifications are disabled for this camera, that I won't recieve updates on motion detection.
Is this by design?

I'm using [this](https://github.com/bropat/eufy-security-client) home assistant custom component and would like to create automations based on motion detection, even when the notifications of the camera are disabled.

In the Eufy app I have created 2 modes:
- Home mode: in this mode the notifications are **disabled** and I **don't** recieve motion detection updates.
- Away mode: in this mode the notifications are **enabled**  and I **do** recieve motion detection updates.

**Comment by Palmke** [comment]
You only get updates because this application reads the same notification as you get on your phone. It subscribes to notifications in order to emit the events you see in Home Assistant.

**Comment by bropat** [comment]
As @Palmke has already correctly explained, it relies on push notifications and unfortunately there is no other option.
