### ISSUE TITLE
Is it possiblem to force getLastCameraImageURL() to be updated

### ISSUE THREAD

**Issue by schliemann** [bropat/eufy-security-client#17]
Is it possible to force a new snapshot to be generated for a eufy cam? We use getLastCameraImageURL in homebridge and homebridge has default functionality for updating snapshots at an interval. However the getLastCameraImageURL only seems to change when an event has been triggered.

**Comment by bropat** [comment]
Not at the moment.

**Comment by schliemann** [comment]
I think this issue can be closed. I hadn't realized that what I really wanted was instead to create a snapshot from the stream.
