### ISSUE TITLE
[Question]: Two simultaneous p2p streams on one station

### ISSUE THREAD

**Issue by thieren** [bropat/eufy-security-client#170]
### Ask your question

Hi!

We currently have an [issue](https://github.com/homebridge-eufy-security/plugin/issues/81) that is partly caused by two doorbells that try to start a p2p at the same time. Both doorbells are connected to the same station. It seems that only one can get the stream. It only depends which device asks first.

So I wondered: Should it be possible to stream two devices at the same time? Until now I thought so, since the client differs by the device channels. But maybe I was wrong.

**Comment by bropat** [comment]
Unfortunately, the station can only actively provide 1 livestream at a time. As soon as another one is started, the current one is terminated.
