### ISSUE TITLE
[Feature request]: Support snooze

### ISSUE THREAD

**Issue by amosyuen** [bropat/eufy-security-client#176]
### Describe the solution you'd like

In the app you can snooze a camera for some time. The camera keeps recording but doesn't send notifications during that time. This is useful to reduce notifications but keep recording events.

I would like to be able to see the current snooze duration as well as set the snooze duration using the API.

It looks like you already have the `ParamType.SNOOZE_MODE` which you decode to json and you have a param value for `CMD_SET_SNOOZE_MODE `, but doesn't seem like it's used anywhere.

**Comment by amosyuen** [comment]
From inspecting the snooze json payload returned from the HTTP API, for cameras it looks fairly simple:
```json
{
  "account_id": "", // Not sure how this is used if used at all
  "snooze_time": 600, // Seconds
  "startTime": 1234, // Epoch seconds
}
```

Doorbells are more complicated. Their payload looks like:
```json
{
  "account_id": "", // Not sure how this is used if used at all
  "snooze_time": 600, // Seconds
  "startTime": 1234, // Epoch seconds
  "chime_onoff": 1, // 0 or 1
  "motion_onoff": 1, // 0 or 1
  "homebase_onoff": 0, // Saw this in the payload for the doorbell, but I didn't see how to change it
}
```

Also doorbells set another param `DOORBELL_SNOOZE_START_TIME = 2037` that seems to be epoch seconds also.

**Comment by amosyuen** [comment]
Thanks for adding the new feature! Excited to try it out

**Comment by thogens** [comment]
Hi! Did anyone had success with the snooze function? For whatever reason, I can't get my devices into that mode.
Any hint what to put into the fields, so that it works?
Thanks,
Thomas

**Comment by fuatakgun** [comment]
I am using eufy-security-ws and snooze it well working there.

https://github.com/fuatakgun/eufy_security/blob/5b01b07e95c95d0a25aff9da769f5210c1ada5af/custom_components/eufy_security/eufy_security_api/outgoing_message.py#L75

**Comment by thogens** [comment]
Can you help me? What do I need to do? Sorry, I'm a rookie :-)
