### ISSUE TITLE
[Feature request]: Add support for Smart safe

### ISSUE THREAD

**Issue by Krhern18** [bropat/eufy-security-client#182]
### Describe the solution you'd like

Smart safe

**Comment by bropat** [comment]
@Krhern18 

In order for me to support this device, I need access to it. Could you please share your device with me (i need admin rights):

* [patrick.broetto+eu1@gmail.com](mailto:patrick.broetto+eu1@gmail.com) (for EU)
* [patrick.broetto+us1@gmail.com](mailto:patrick.broetto+us1@gmail.com) (for US)

Thanks!

**Comment by Krhern18** [comment]
Eufy security does not support device sharing with Smart Safe Wifi S12. What else can we do?

Ken

**Comment by Krhern18** [comment]
Ok, I sent the info to the email that you previously provided.

**Comment by bropat** [comment]
Small update:

* P2P connection up and running
* Decrypted P2P communication (AES-128-CBC)

**Comment by bropat** [comment]
@Krhern18 

While testing the functionalities, I changed the setting in the Power Manager from "High-Performance Mode" to "Power-Save Mode". Now I can no longer change any settings via Wi-Fi.
Could you please change the setting back to "High-Performance Mode".

Thanks and sorry ;)

**Comment by Krhern18** [comment]
No problem, it's back on.

**Comment by bropat** [comment]
Update:

* Sending commands to Smart Safe works (settings properties, unlock, etc.).

**Comment by bropat** [comment]
@Krhern18 

I have almost completed the integration. I just need to test everything a last time, but the device is no longer visible under the shared account.

Could you please check this?

Thank you!

**Comment by didgeriwho** [comment]
@bropat Do you still need access to this device? I have the similar model T7400 that I'd like to get working in home assistant. Right now I can see the device in HA (with a motion sensor and a streaming sensor) - but I can't get the device to unlock.

**Comment by didgeriwho** [comment]
@bropat - sent to your email

**Comment by bropat** [comment]
@didgeriwho 

I need the PIN to test some features. Could you send it to me?

Thx!

**Comment by bropat** [comment]
@didgeriwho 

Thank you very much for sharing the device. In the next release, the device will be supported.

**Comment by didgeriwho** [comment]
> @didgeriwho
> 
> Thank you very much for sharing the device. In the next release, the device will be supported.

🙏🙏🙏

**Comment by didgeriwho** [comment]
Hi @bropat 

Seems like the client is still not allowing unlocking the device
https://github.com/fuatakgun/eufy_security/issues/521#issuecomment-1366867281

**Comment by fuatakgun** [comment]
I might be missing some context here, I have used set_property(locked, False) and it is failing. 

Do I need to use some other service with entering pin?

**Comment by fuatakgun** [comment]
I have tried this order;
```
{
  "messageId": "verify", 
  "pin": "XXXXXX",
  "command": "device.verify_pin",
  "serialNumber": "T7400XXXXX" 
}
```

response:
```
{'type': 'result', 'success': False, 'errorCode': 'unknown_error'}
```

Of course, device.unlock also had failed.
```
{
  "messageId": "unlock", 
  "command": "device.unlock",
  "serialNumber": "T7400XXX" 
}
```

Result:
{'type': 'result', 'success': False, 'errorCode': 'unknown_error'}


@bropat , looking for your guidance on;
- correct flow of commands
- result is missing message id for errors

**Comment by fuatakgun** [comment]
my bad, all is working, thanks again for your work @bropat

**Comment by fuatakgun** [comment]
correct order;
- call verify_pin
- wait for pin_verified event
- call unlock
