### ISSUE TITLE
[Bug]: T8210 battery level does not get updated

### ISSUE THREAD

**Issue by reesion** [bropat/eufy-security-client#183]
### Client version

2.2.7

### Node version

NA

### Operating System type

Other

### Operating system version

Debian 11

### Describe the bug

T8210 battery level does not get updated

### To reproduce

Once integration is added, battery state remains the same all the time.

**Comment by bropat** [comment]
Could you please provide me with some debug logs so I can check and fix the cause.

**Comment by bropat** [comment]
Client version does not exist. No response regarding debug logs.
