### ISSUE TITLE
[Feature request]: Add state_class:measurement attribute to battery level

### ISSUE THREAD

**Issue by horriblenoises** [bropat/eufy-security-client#189]
### Describe the solution you'd like

You've already got `device_class: battery`; please add `state_class: measurement`.

Thank you.

**Comment by bropat** [comment]
I don't understand what you mean? 
Wrong repo?

**Comment by horriblenoises** [comment]
I'm sorry. This might be the wrong repo. I'm very confused about where client ends and ws begins.

Looking in Home Assistant. The battery level entity for my doorbell has an attribute for device_class but nothing for state_class.

**Comment by fuatakgun** [comment]
Please open this issue in eufy_security repository, not here

**Comment by horriblenoises** [comment]
Thanks & sorry about that.
