### ISSUE TITLE
[Bug]: EntrySensor gets no updates on cloud data refresh and no push messages

### ISSUE THREAD

**Issue by thieren** [bropat/eufy-security-client#192]
### Client version

2.1.1

### Node version

16.16.0

### Operating System type

Linux

### Operating system version

deb

### Describe the bug

Hi!

I have had a debugging session with @federicodigiacomo who has issues with his eufy sensors (T8900s). The state of theses sensors is updated correctly one time only on startup of the client. In subsequent refreshs of the cloud data the correct value for `CMD_ENTRY_SENSOR_STATUS` is retrieved from the cloud, but the raw property is not updated. In consequence the `DeviceSensorOpen` property is also not updated. In short: the sensor always shows the state that was loaded at startup. Any sensor changes are ignored.

I can provide a log. Since these are not mine and have sensitive data in them, I'd like to share them via google drive or something. I can also share snippets of the log, if that's helpful.
But to summarise the log: after every polling Interval the device data is fetched. It shows the correct state in the device data but when we try to get the sensor state in the homebridge plugin it is not updated. Also there is no `raw property change` or `property change` emitted. So I can confirm that the internal value is not correctly updated. The p2pconnection to the station is not disconnected, so this doesn't seem to be it.

**Also something peculiar: there's also no push notification regarding the sensor state change. Not even a raw push message in the logs. Do these just not work for these sensors?**

Push in general does seem to work. At least I have seen two other push messages in the log regarding guard mode changes.

### To reproduce

Observe internal state of sensor over a period of time.

**Comment by Palmke** [comment]
I'm on the latest `develop` version and I get updates just fine. I have push notifications enabled and get notifications/updates just fine.

**Comment by bropat** [comment]
Released version 2.1.2 based on the latest `develop` version which works according to @Palmke.

**Comment by thieren** [comment]
Will update the plugin to 2.1.2. in the coming days and let you know if this fixes it.

@Palmke so you own at least one T8900 also? I don't know if there are different kinds of sensors from eufy.

**Comment by Palmke** [comment]
I have three. And checked for logs for one when I opened a door after reading this issue.

**Comment by thieren** [comment]
@federicodigiacomo did let me know, that his issue is resolved. Thx!
