### ISSUE TITLE
Parse getStorageInfo results

### ISSUE THREAD

**Issue by yooo1999** [bropat/eufy-security-client#200]
### Ask your question

The function [getStorageInfo](https://github.com/bropat/eufy-security-client/blob/master/src/http/station.ts#L552)  return bytes buffer

How can I parse this ? I didn't see any usage of this function.

**Comment by bropat** [comment]
Hi @yooo1999,

I never actually finished implementing that part. I'd have to check again myself.

**Comment by PhilippEngler** [comment]
Hi,

@bropat has already implemented all the stuff for requesting the info and also the response, there were only a few more things to implement. You can see it here [getStorageInfo Branch](https://github.com/PhilippEngler/eufy-security-client/tree/getStorageInfo) or in the [commit](https://github.com/PhilippEngler/eufy-security-client/commit/c0fac4854476ec7614f3dd5f0e6a63e933fb0e44). @bropat, please check if its worth to make a pull request.

Some information:
- the response contains the status, capacity and available capacity
- checked on HomeBase E (T8002), HomeBase 2 (T8010), HomeBase 3 (T8030) and Indoor Cam Pan and Tilt 2k (T8410)
- on HomeBase 3
  - the response only contains the internal storage
  - the capacity is not the same as in the app
- the capacity and available capacity are in MB, to get it in GB, you have to
  - divide by 1000 for HomeBase E (T8002), HomeBase 2 (T8010) and Indoor Cam Pan and Tilt 2k (T8410)
  - divide by 1024 for HomeBase 3 (T8030)

**Comment by bropat** [comment]
@PhilippEngler 

Very good work! I have opened a pull request for integration into the develop branch.

**Comment by PhilippEngler** [comment]
@bropat thank you, Most of the work was done by you. I was not sure if I have integrated it the right way into the client (it is a little bit straight forward).
