### ISSUE TITLE
[Bug]: Station livestream on wireless doorbell not starting

### ISSUE THREAD

**Issue by syl035** [bropat/eufy-security-client#201]
### Client version

1.5.0

### Node version

16.15.1

### Operating System type

Mac OS X

### Operating system version

12.4

### Describe the bug

Hi, I cannot make the Eufy Plug-In work to livestream my doorbell.
I reported a bug on their repo (here: https://github.com/homebridge-eufy-security/plugin/issues )

And after further investigations from the developers, they told me the problem was coming from the "eufy-security-client" plug-in they are using to make the connection. It seems that the command is never really sent...

You can find the log snippet down below.

Do you know what could cause this problem? Is it really a bug on your side or a config problem on my side?

Thanks in advance for your help!

Best regards,

Sylvain

### To reproduce

2. Click on '...'

### Screenshots & Logfiles

2022-08-10 20:34:11.995  DEBUG [P2PClientProtocol.handleMsg] Station T8020P1021150F6C - LOOKUP_RESP - Got response 
{
  remoteAddress: '3.131.209.36',
  remotePort: 32100,
  response: {
    responseCode: 253
  }
}
2022-08-10 20:34:12.046  DEBUG [Station.startLivestream] Sending start livestream command to station T8020P1021150F6C for device T8220P602114005D 
2022-08-10 20:34:12.047  DEBUG [Station.startLivestream] Using CMD_SET_PAYLOAD for station T8020P1021150F6C (main_sw_version: 2.1.2.2m_3.1) 
2022-08-10 20:34:12.049  DEBUG [P2PClientProtocol.handleMsg] Station T8020P1021150F6C - LOOKUP_RESP - Got response 
{
  remoteAddress: '54.153.101.7',
  remotePort: 32100,
  response: {
    responseCode: 253
  }
}
2022-08-10 20:34:12.051  DEBUG [P2PClientProtocol.handleMsg] Station T8020P1021150F6C - LOOKUP_RESP - Got response 
{
  remoteAddress: '204.236.133.68',
  remotePort: 32100,
  response: {
    responseCode: 253
  }
}

**Comment by bropat** [comment]
The errors listed above are address lookup errors and not livestream errors.
Due to the address lookup errors communicated by the Eufy cloud, the IP address of the device cannot be determined, so no connection to the device can be established and no livestream start command can be sent.
If you send me a complete log file, I can tell you more.

**Comment by syl035** [comment]
@bropat 
Hi, thank you for checking the problem!
I juste sent you an email to your email address with the complete log file.

Thanks again for helping out!

Sylvain

**Comment by bropat** [comment]
@syl035 

In the logs I only see errors in the address lookup, so no connection could be established to the unit.

To debug the cause i need access to the device. Could you please share your device with me (i need admin rights):

* [patrick.broetto+eu1@gmail.com](mailto:patrick.broetto+eu1@gmail.com) (for EU)
* [patrick.broetto+us1@gmail.com](mailto:patrick.broetto+us1@gmail.com) (for US)

Thanks!

**Comment by syl035** [comment]
@bropat 
Hi, I just sent you an invite,

Thanks for your help!

Sylvain

**Comment by bropat** [comment]
@syl035 

The issue will be fixed in the next release. You can remove the sharing.

Thanks!

**Comment by syl035** [comment]
@bropat 
Wow, thanks a lot!

Best regards,

Sylvain

**Comment by thieren** [comment]
Hi @bropat 

just curious: can you elaborate on what the issue was?

Thx!

**Comment by bropat** [comment]
> Hi @bropat
> 
> just curious: can you elaborate on what the issue was?
> 
> Thx!

The cloud address device discovery part had fixed IP addresses in the library, now it uses the IP addresses sent by the eufy cloud to determine the device address.

[Old implementation](https://github.com/bropat/eufy-security-client/blob/c1776e754b98081a837e55f6e9820d904b352d07/src/p2p/session.ts#L68-L78)

[New Implementation](https://github.com/bropat/eufy-security-client/blob/6e7c4ffd95ae5f9db2b4991bc09be43173e9820f/src/p2p/session.ts#L106)
