### ISSUE TITLE
[Bug]: Mismatched sequence numbers

### ISSUE THREAD

**Issue by cbwilliamsnh** [bropat/eufy-security-client#207]
### Client version

2.2.0.rc.2

### Node version

16.16.0

### Operating System type

Mac OS X

### Operating system version

macOS Monterey 12.5.1

### Describe the bug

I'm using the eufy-security plugin on Homebridge and I'm seeing the following issue in the log:

```
2022-08-31 17:54:34.068  DEBUG [Station.startLivestream] Sending start livestream command to station T8010T1321520EA2 for device T8113T9321523513 
2022-08-31 17:54:34.069  DEBUG [Station.startLivestream] Using CMD_SET_PAYLOAD for station T8010T1321520EA2 (main_sw_version: 3.1.9.0h) 
2022-08-31 17:54:34.070  DEBUG [P2PClientProtocol._sendCommand] Sending p2p command... 
{
  station: 'T8010T1321520EA2',
  sequence: 6,
  commandType: 1350,
  channel: 0,
  retries: 0,
  messageStatesSize: 2
}
2022-08-31 17:54:34.070  DEBUG [P2PClientProtocol._sendCommand] Sending p2p command... 
{
  station: 'T8010T1321520EA2',
  sequence: 7,
  commandType: 1045,
  channel: 0,
  retries: 0,
  messageStatesSize: 3
}
2022-08-31 17:54:34.083  DEBUG [P2PClientProtocol.handleMsg] Station T8010T1321520EA2 - DATA DATA - received from host 192.168.109.123:14596 - Processing sequence 5... 
2022-08-31 17:54:34.083  DEBUG [P2PClientProtocol.parseDataMessage] Station T8010T1321520EA2 - Received data 
{
  seqNo: 5,
  header: {
    commandId: 1350,
    bytesToRead: 132,
    channel: 0,
    signCode: 0,
    type: 1
  },
  bytesRead: 132,
  bytesToRead: 132,
  firstPartMessage: true,
  messageSize: 148
}
2022-08-31 17:54:34.085  DEBUG [P2PClientProtocol.handleData] Station T8010T1321520EA2 - Received data 
{
  commandIdName: 'CMD_SET_PAYLOAD',
  commandId: 1350,
  resultCodeName: 'ERROR_PPCS_NOT_INITIALIZED',
  resultCode: -1,
  message: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
  data: 'ffffffff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
}
2022-08-31 17:54:34.086  DEBUG [P2PClientProtocol.handleData] Station T8010T1321520EA2 - dataType: DATA commandtype and sequencenumber different! 
{
  msg_sequence: 5,
  msg_channel: 1,
  msg_commandType: 1056,
  message: {
    commandId: 1350,
    bytesToRead: 132,
    channel: 0,
    signCode: 0,
    type: 1,
    seqNo: 5,
    dataType: 0,
    data: <Buffer ff ff ff ff 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 82 more bytes>
  }
}
2022-08-31 17:54:34.087  WARN [P2PClientProtocol.handleData] P2P protocol instability detected for station T8010T1321520EA2. Please reinitialise the connection to solve the problem! 
2022-08-31 17:54:34.088  DEBUG [P2PClientProtocol.handleMsg] Station T8010T1321520EA2 - DATA DATA - Received expected sequence (seqNo: 5 queuedData.size: 0) 
2022-08-31 17:54:34.089  DEBUG [P2PClientProtocol.handleMsg] Station T8010T1321520EA2 - ACK DATA - received from host 192.168.109.123:14596 for sequence 6 
2022-08-31 17:54:34.089  DEBUG [P2PClientProtocol.handleMsg] Station T8010T1321520EA2 - ACK DATA - received from host 192.168.109.123:14596 for sequence 7 
2022-08-31 17:54:34.836  DEBUG [P2PClientProtocol.handleMsg] Station T8010T1321520EA2 - DATA DATA - received from host 192.168.109.123:14596 - Processing sequence 6... 
2022-08-31 17:54:34.837  DEBUG [P2PClientProtocol.parseDataMessage] Station T8010T1321520EA2 -2022-08-31 17:54:34 Received data 
{
  seqNo: 6,
  header: {
    commandId: 1045,
    bytesToRead: 132,
    channel: 0,
    signCode: 0,
    type: 1
  },
  bytesRead: 132,
  bytesToRead: 132,
  firstPartMessage: true,
  messageSize: 148
}
2022-08-31 17:54:34.837  DEBUG [P2PClientProtocol.handleData] Station T8010T1321520EA2 - Received data 
{
  commandIdName: 'CMD_DEV_LED_SWITCH',
  commandId: 1045,
  resultCodeName: 'ERROR_PPCS_SUCCESSFUL',
  resultCode: 0,
  message: '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00',
  data: '000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'
}
2022-08-31 17:54:34.838  DEBUG [P2PClientProtocol.handleData] Station T8010T1321520EA2 - dataType: DATA commandtype and sequencenumber different! 
{
  msg_sequence: 6,
  msg_channel: 0,
  msg_commandType: 1350,
  message: {
    commandId: 1045,
    bytesToRead: 132,
    channel: 0,
    signCode: 0,
... (21 lines left)
```

I currently have six cameras and a doorbell, three + doorbell on one Homebase2, the other three on a second Homebase2.

### To reproduce

Not sure how to reproduce as I'm using a library via the [homebridge-eufy-security](https://github.com/homebridge-eufy-security/plugin) plugin.

**Comment by bropat** [comment]
Hi @cbwilliamsnh,
i need the complete debug log do understand what caused this issue.

**Comment by cbwilliamsnh** [comment]
Here you go.

[ChuckNewBetaLogs.zip](https://github.com/bropat/eufy-security-client/files/9464109/ChuckNewBetaLogs.zip)

**Comment by bropat** [comment]
@cbwilliamsnh 

I can't reproduce this issue (maybe I have too few devices :P). I think I know what the problem is.
Can you share one of your stations with the corresponding paired devices, as the problem occurs with both.

Let me know.

**Comment by cbwilliamsnh** [comment]
when you say "share one of your stations..." do you mean give you access to them through the eufy app? What email address do you want me to use if that's the case?

**Comment by bropat** [comment]
> when you say "share one of your stations..."

Exactly, with Admin Rights. Account: patrick.broetto+us1@gmail.com

**Comment by cbwilliamsnh** [comment]
Just sent you an invite to my outdoor cams. There are three as you'll see. All of my cameras on both Homebase2 now show no response in the Home app. None of them are using RTP Streaming.

**Comment by cbwilliamsnh** [comment]
correction. I viewed each live stream in the eufy security app and now I see up to date snapshots and the streams are working in the Home app for the left and right sides, but not the backyard.

**Comment by cbwilliamsnh** [comment]
Might the issue be that I have two Homebase2's? I originally had all the cameras and both Homebase2's in HK/Home App and now they're in HK via the eufy Security Homebridge plugin.

**Comment by bropat** [comment]
I cannot reproduce the error myself, but what I have already seen from the logs is, that wrong values are being tried to be set for  nightvision (true). EufyCam 2c do not have 2 states but 3 and therefore no boolean is expected here but a number. The Homebridge plugin probably does not check the metadata of the attributes to be set.

**Comment by cbwilliamsnh** [comment]
ah! I assume you are done using the cameras?

**Comment by bropat** [comment]
@cbwilliamsnh 

Yes, sorry.

Can you please try the following:

1. under the installation directory of the eufy-security Homebridge plugin, you should find a node_modules directory
2. in this directory you should find an eufy-security-client directory
3. in the eufy-security-client directory, go to build, then p2p
4. edit the file session.js and change the following:
    
    Before:

```javascript
sendQueuedMessage() {
        if (this.sendQueue.length > 0 && this.connected) {
            let queuedMessage;
            while ((queuedMessage = this.sendQueue.shift()) !== undefined) {
                let exists = false;
                this.messageStates.forEach(stateMessage => {
                    if (stateMessage.commandType === queuedMessage.commandType) {
                        exists = true;
                    }
                });
                if (!exists) {
                    this._sendCommand(queuedMessage);
                }
                else {
                    this.sendQueue.unshift(queuedMessage);
                    break;
                }
            }
        }
        else if (!this.connected) {
            this.connect();
        }
    }
```
    After:

```javascript
sendQueuedMessage() {
        if (this.sendQueue.length > 0 && this.connected) {
            let queuedMessage = this.sendQueue.shift();
            if (queuedMessage  !== undefined) {
                let exists = false;
                this.messageStates.forEach(stateMessage => {
                    if (stateMessage.commandType === queuedMessage.commandType) {
                        exists = true;
                    }
                });
                if (!exists) {
                    this._sendCommand(queuedMessage);
                }
                else {
                    this.sendQueue.unshift(queuedMessage);
                    break;
                }
            }
        }
        else if (!this.connected) {
            this.connect();
        }
    }
```
5. Restart the plugin or homebridge and try again
6. Check if the following error still occurs: `P2P protocol instability detected for station <station_serialnumber>. Please reinitialise the connection to solve the problem! `
7. Let me know ;)

**Comment by cbwilliamsnh** [comment]
still seeing: `STREAMING DISABLED ACTIVE` in the log many many times. Could this be that I have the indoor camera set to "Off" when I'm home and "Record and Stream" when I'm away?

**Comment by cbwilliamsnh** [comment]
Changed the code you sent a bit to:

```
sendQueuedMessage() {
        if (this.sendQueue.length > 0 && this.connected) {
            let queuedMessage = this.sendQueue.shift();
            if (queuedMessage  !== undefined) {
                let exists = false;
                this.messageStates.forEach(stateMessage => {
                    if (stateMessage.commandType === queuedMessage.commandType) {
                        exists = true;
                    }
                });
                if (exists) {
                    this.sendQueue.unshift(queuedMessage);
                }
                else {
                    this._sendCommand(queuedMessage);
                }
            }
        }
        else if (!this.connected) {
            this.connect();
        }
    }
```

**Comment by bropat** [comment]
> 6\. Check if the following error still occurs: `P2P protocol instability detected for station <station_serialnumber>. Please reinitialise the connection to solve the problem!`

I don't follow you. This is not a log output from eufy-client-security.
At point 6, you should check the eufy.log to see if you are still getting this error: `P2P protocol instability detected for station <station_serialnumber>. Please reinitialise the connection to solve the problem!`

Does this error still occur after you have changed the above source code lines?

**Comment by bropat** [comment]
> Changed the code you sent a bit to:
> 
> ```
> sendQueuedMessage() {
>         if (this.sendQueue.length > 0 && this.connected) {
>             let queuedMessage = this.sendQueue.shift();
>             if (queuedMessage  !== undefined) {
>                 let exists = false;
>                 this.messageStates.forEach(stateMessage => {
>                     if (stateMessage.commandType === queuedMessage.commandType) {
>                         exists = true;
>                     }
>                 });
>                 if (exists) {
>                     this.sendQueue.unshift(queuedMessage);
>                 }
>                 else {
>                     this._sendCommand(queuedMessage);
>                 }
>             }
>         }
>         else if (!this.connected) {
>             this.connect();
>         }
>     }
> ```
> 
> And that's the code that's running now. Seeing better performance when I view live streams in the Home app, but still get too many "No Response" errors. Can't view the doorbell camera at all in the Home app.

Here you are in the repository of the driver (`eufy-security-client`) and not of the Homebridge plugin. I can't give you support for the Homebridge plugin. You have to open an issue in the other repository and ask for support.

I can only give you support for errors in the "eufy.log" file of the Homebridge plugin, as this file corresponds to the logging of the "eufy-security-client" (as far as I can see).

**Comment by cbwilliamsnh** [comment]
My bad!! I'll check the log when I'm back at my computer and let you know.

**Comment by cbwilliamsnh** [comment]
@bropat any further news or requests?

**Comment by cbwilliamsnh** [comment]
Any idea when the next version will be released?

**Comment by bropat** [comment]
@cbwilliamsnh 

Released yesterday
