### ISSUE TITLE
[Feature request]: add support for T8503 Door Lock

### ISSUE THREAD

**Issue by etorr** [bropat/eufy-security-client#208]
### Describe the solution you'd like

I tried setting up device but kept getting connected and disconnected from device

**Comment by etorr** [comment]
Shared access to door lock

**Comment by etorr** [comment]
2022-09-04 06:34:41.031  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2022-09-04 06:34:51.588  INFO  Push notification connection successfully established 
2022-09-04 06:34:52.882  INFO  Connected to station T8503Q1021450032 on host 10.0.0.176 and port 24791 
2022-09-04 06:35:26.480  INFO  Disconnected from station T8503Q1021450032 
2022-09-04 06:35:42.734  INFO  Connected to station T8503Q1021450032 on host 10.0.0.176 and port 11519 
2022-09-04 06:36:16.383  INFO  Disconnected from station T8503Q1021450032 
2022-09-04 06:36:34.563  INFO  Connected to station T8503Q1021450032 on host 10.0.0.176 and port 15622 
2022-09-04 06:37:08.263  INFO  Disconnected from station T8503Q1021450032 
2022-09-04 06:37:23.678  INFO  Connected to station T8503Q1021450032 on host 10.0.0.176 and port 18488 
2022-09-04 06:37:57.415  INFO  Disconnected from station T8503Q1021450032 
2022-09-04 06:38:12.805  INFO  Connected to station T8503Q1021450032 on host 10.0.0.176 and port 28211 
2022-09-04 06:38:46.595  INFO  Disconnected from station T8503Q1021450032 
2022-09-04 06:39:00.720  INFO  Connected to station T8503Q1021450032 on host 10.0.0.176 and port 11377 
2022-09-04 06:39:34.420  INFO  Disconnected from station T8503Q1021450032 
2022-09-04 06:39:48.270  INFO  Connected to station T8503Q1021450032 on host 10.0.0.176 and port 12498

**Comment by bropat** [comment]
@etorr 

Hi,

I can no longer connect to the device via P2P using the Eufy App. Can you please check?

Thank you!

**Comment by etorr** [comment]
Restarted device, I am able to connect to it with Eufy app

**Comment by bropat** [comment]
Now it's working again.

Thank you!

**Comment by bropat** [comment]
@etorr 

Could you restart the device one more time and let me know?

Thanks!

**Comment by etorr** [comment]
Restarted again, Thank You for working on it!

**Comment by bropat** [comment]
@etorr 

**Small update:**

In the meantime, basic communication with the unit has been implemented. The first commands already work, such as locking and unlocking the device.

**Comment by bropat** [comment]
@etorr 

Communication with the unit is not very stable. At the moment, the device is not accessible again. Please restart the device and share it with me at this email address:

* patrick.broetto+testing@gmail.com

PS: I have deleted the other share.

Thank you!

**Comment by bropat** [comment]
@etorr 

Could you share the device again?

**Comment by tiko7426** [comment]
Do you still need access to one? I just got one I'd be happy to share

**Comment by tiko7426** [comment]
Just noticed your response now, sorry. Inviting you at the email you listed above.

**Comment by tiko7426** [comment]
Just invited you and set a calendar reminder for myself to check daily for replies here

**Comment by tiko7426** [comment]
Just invited you and set a calendar reminder for myself to check daily for replies here. Mine is a model T8504 which appears to be the same as T8503 just with an additional fingerprint module. My SN starts with T8503Q

**Comment by kardboard604** [comment]
+1 on implementing support for the T8503 door lock. Thank you!

**Comment by austin-r-brown** [comment]
Yes please, would really love to see support for T8503 door lock! I saw in duplicate issue #294 someone said they were able to get it to integrate but that is not the case for me. I am seeing the lock in my devices but a bunch of errors are thrown and nothing seems to work. My node version is v20.10.0 and I tried a few versions of the homebridge-eufy-security plugin but currently on the one that says latest (v2.2.21)

**Comment by austin-r-brown** [comment]
@bropat I can provide access to mine if you need it

**Comment by kardboard604** [comment]
> Yes please, would really love to see support for T8503 door lock! I saw in duplicate issue #294 someone said they were able to get it to integrate but that is not the case for me. I am seeing the lock in my devices but a bunch of errors are thrown and nothing seems to work. My node version is v20.10.0 and I tried a few versions of the homebridge-eufy-security plugin but currently on the one that says latest (v2.2.21)

The T8503 is detected if you share the lock itself with the eufy account you use for HA integration. In the eufy app, tap on the lock, then Settings>>Share Device. It won't show up otherwise.

In my HA, it intermittently works. I see it as a device all the time and add it to automations, and I can lock and unlock it manually by going into its Device Info and hitting lock/unlock under Diagnostic. It doesn't work in automations for me.

**Comment by austin-r-brown** [comment]
> > Yes please, would really love to see support for T8503 door lock! I saw in duplicate issue #294 someone said they were able to get it to integrate but that is not the case for me. I am seeing the lock in my devices but a bunch of errors are thrown and nothing seems to work. My node version is v20.10.0 and I tried a few versions of the homebridge-eufy-security plugin but currently on the one that says latest (v2.2.21)
> 
> The T8503 is detected if you share the lock itself with the eufy account you use for HA integration. In the eufy app, tap on the lock, then Settings>>Share Device. It won't show up otherwise.
> 
> In my HA, it intermittently works. I see it as a device all the time and add it to automations, and I can lock and unlock it manually by going into its Device Info and hitting lock/unlock under Diagnostic. It doesn't work in automations for me.

Yes, I am able to get the lock to show up like I said, but the only device that makes it to the actual Home app on my phone is a security device with settings like 'Home, Away, Night' etc, which not only doesn't apply to this lock but it causes Homebridge to crash and restart if you try to change them. As far as the lock and pinpad device that are detected by the plugin but don't make it to the Home app, it just shows a bunch of errors in the logs about not expecting return values.  I'm not sure if it makes a difference but I'm not using Home Assistant, I'm trying to integrate it with Homebridge. I want to create an automation for when the Locked/Unlocked status changes, which I was kind of able to do in a roundabout way through Alexa, but its not very reliable

**Comment by paulbaird87** [comment]
> > Yes please, would really love to see support for T8503 door lock! I saw in duplicate issue #294 someone said they were able to get it to integrate but that is not the case for me. I am seeing the lock in my devices but a bunch of errors are thrown and nothing seems to work. My node version is v20.10.0 and I tried a few versions of the homebridge-eufy-security plugin but currently on the one that says latest (v2.2.21)
> 
> The T8503 is detected if you share the lock itself with the eufy account you use for HA integration. In the eufy app, tap on the lock, then Settings>>Share Device. It won't show up otherwise.
> 
> In my HA, it intermittently works. I see it as a device all the time and add it to automations, and I can lock and unlock it manually by going into its Device Info and hitting lock/unlock under Diagnostic. It doesn't work in automations for me.

How do you interact with the device in HA, I have the device shared from my Eufy account to a seperate account used in HA. It shows up alongside my other devices but only entities available in Diagnostic are 'Reset Alarm' and 'Trigger Alarm'?

**Comment by paulbaird87** [comment]
> @etorr
> 
> **Small update:**
> 
> In the meantime, basic communication with the unit has been implemented. The first commands already work, such as locking and unlocking the device.

How can we access these in HA? I can only see 'Reset Alarm' and 'Trigger Alarm' after re-configuring add on and removing and adding the Eufy integration.

**Comment by bropat** [comment]
There is still no support for this device. If someone shares the device with me, I can provide support.

**Comment by kardboard604** [comment]
> There is still no support for this device. If someone shares the device with me, I can provide support.

I can share mine with you. Do I just share it to patrick.broetto+testing@gmail.com?

**Comment by austin-r-brown** [comment]
@bropat I just shared access with mine as well

**Comment by paulbaird87** [comment]
Not all heroes wear capes......@bropat 
Thank you

**Comment by austin-r-brown** [comment]
@bropat Thank you!!!!
Not sure who is in charge of the Homebridge plugin but I added a request to add support there as well as I was able to successfully get the lock working in my local environment with these changes from my fork:

https://github.com/austin-r-brown/plugin/tree/master

**Comment by kardboard604** [comment]
Amazing, thank you, @bropat!
