### ISSUE TITLE
[Feature request]: add support for 4G LTE Starlight Camera

### ISSUE THREAD

**Issue by billyj85** [bropat/eufy-security-client#209]
### Describe the solution you'd like

[EufySecurity-2.1.0-rc.5] DEBUG: Found Station T8152Pxxxxx Driveway entrance CAMERA_FG 
[EufySecurity-2.1.0-rc.5] WARN:  T8152P3022070266 type: 2
[EufySecurity-2.1.0-rc.5] DEBUG: This device is not a station. Generating a new UUID to avoid any duplicate issue
[EufySecurity-2.1.0-rc.5] DEBUG: Driveway entrance UUID: xxxx
[EufySecurity-2.1.0-rc.5] DEBUG: Driveway entrance Constructed Station
[EufySecurity-2.1.0-rc.5] DEBUG: Driveway entrance manual alarm will be triggered only in these hk modes: 
[EufySecurity-2.1.0-rc.5] DEBUG: Driveway entrance Mapping for station modes: [{"hk":0,"eufy":1},{"hk":1,"eufy":0},{"hk":2,"eufy":3},{"hk":3,"eufy":63}]
[EufySecurity-2.1.0-rc.5] INFO:  Updating accessory: Driveway entrance
[EufySecurity-2.1.0-rc.5] DEBUG: Found device T8152Pxxxxxx Driveway entrance CAMERA_FG
[EufySecurity-2.1.0-rc.5] DEBUG: Device ignored

**Comment by bropat** [comment]
This is not a log of this library.
Apart from that, if you want me to officially support this device, I need access to the device.
Let me know if you are willing to share the device with me.

**Comment by billyj85** [comment]
Happy to give you access, please let me know an email account to add you as a guest to access the cameras. Or do you need a physical device. my email is wilburwild85@gmail.com

**Comment by bropat** [comment]
@billyj85 

* patrick.broetto+testing2@gmail.com
