### ISSUE TITLE
Station livestream is dark and doesn't use IR nightvision

### ISSUE THREAD

**Issue by schliemann** [bropat/eufy-security-client#21]
**Bug**
Using the station livestream returns a stream which is rather dark and doesn't make use of the IR night vision

**To Reproduce**  
1. Receive videostream from https://github.com/bropat/eufy-security-client/blob/d8c394f2148e66fb9aabbfeee7692a37ec66ce5b/src/http/station.ts#L402-L404
2. Make snapshot with ffmpeg https://github.com/schliemann/homebridge-eufy-security-control/blob/F-Realtime_Snapshot/src/streamingDelegate.ts#L330-L374
3. Compare darkness and nightvision with cloud livestream

**Expected behavior**  
Station livestream makes use of IR night vision and is comparable in colour to cloud livestream.

**Screenshots & Logfiles**  
Snapshot from station livestream:
![StationLiveStream](https://user-images.githubusercontent.com/10818044/124092890-9e6ebf00-da57-11eb-86d0-1efde8b87ad8.png)

Snapshot from eufy app
![EufyApp](https://user-images.githubusercontent.com/10818044/124092897-a0388280-da57-11eb-8d95-e070660f22f7.png)

Video shows cloud livestream and then a very dark snapshot. The livestream uses IR night vision the stream from the station doesn't:

https://user-images.githubusercontent.com/10818044/124093016-bcd4ba80-da57-11eb-922e-a0665c10962c.mp4

**Comment by bropat** [comment]
@schliemann 

Hi,

the video I get from the station is untouched, there is no post-processing done like probably with the "Eufy Cloud".
I think it has nothing to do with the IR Night Vision.
You can easily edit the RAW stream you get with ffmpeg through filters (brightness, contrast etc.).

**Comment by schliemann** [comment]
I believe you are correct. The night vision mode does indeed kick in. However it is still extremely difficult to make anything from the stream when it is enabled.

Eufy cloud
![3A5AA343-E874-4629-84E2-664C6150BF76](https://user-images.githubusercontent.com/10818044/124191000-6d2bd880-dac3-11eb-9ba8-cfc69f946974.png)

Station stream with ffmpeg filter
eq=brightness=0.1:saturation=2

Night vision enabled
![817BBB60-76AD-474B-9113-50411E2A58CF](https://user-images.githubusercontent.com/10818044/124191223-c85dcb00-dac3-11eb-89b8-deb10ed7f50c.jpeg)

Night vision disabled
![379C1805-5957-466D-A507-A8FC1D8A5ADF](https://user-images.githubusercontent.com/10818044/124191268-d875aa80-dac3-11eb-90c1-4066458b3eed.jpeg)

**Comment by bropat** [comment]
@schliemann 
I have already tested the livestream extensively with my Eufycam 2 some time ago and had no problem with night vision on or off.
Therefore, I can not understand your image "night vision enabled".

**Comment by schliemann** [comment]
@bropat The device I'm using in this test is T8210_Video Doorbell 2K. When I write that night vision is enabled it is because it can be set in the device settings:

![image](https://user-images.githubusercontent.com/10818044/124265375-e19f5f80-db35-11eb-84e9-b1b6a545d708.png)

I'll gladly share the doorbell with you through guest access.

**Comment by bropat** [comment]
@schliemann I will get back to you in about 2 weeks

**Comment by bropat** [comment]
@schliemann 

I just tested it with my ioBroker adapter, which also uses eufy-security-client, and the video is fine:

![image](https://user-images.githubusercontent.com/2305255/129094836-4f443ce7-baf2-45f7-abae-07d4d7eedd80.png)

The problem must lie somewhere else, not with the library eufy-security-client

**Comment by schliemann** [comment]
@bropat Interesting. Your ioBroker works slightly different, since you use fluentffmpeg and save files to the disk. Can you see anything that looks completely off here?

https://github.com/schliemann/homebridge-eufy-security-control/blob/F-Realtime_Snapshot/src/streamingDelegate.ts#L199-L378

**Comment by bropat** [comment]
@schliemann 
Have you tried removing [these](https://github.com/schliemann/homebridge-eufy-security-control/blob/e5dd6b8125684295e0aa6f66d9838033d2a18236/src/streamingDelegate.ts#L335-L338)?

Apart from the filter parameters, I don't see any difference.

**Comment by schliemann** [comment]
@bropat I finally figured out why my snapshots didn't utilize night vision. Apparently it is not present in the first frame(s) of a started livestream. When I added seeking (-ss) of half a second the night vision is turned on.

https://user-images.githubusercontent.com/10818044/151251932-4d4707f9-3de1-432a-bc32-d6cf3869ffcb.mp4
