### ISSUE TITLE
[Feature request]: Read state of night vision

### ISSUE THREAD

**Issue by mauricehofman** [bropat/eufy-security-client#211]
I would like to read the state of night vision (is it currently on or off). I think is this not possible yet.

**Comment by PhilippEngler** [comment]
I think, this should work already. Try `getPropertyValue(PropertyName.DeviceNightvision)` on the device object. On supported devices you get a number value (tried with T8113, return values are: `0`: off, `1`: B/W, `2`: color), on devices without support of night vision you get `undefined` as return value. There you can try use `getPropertyValue(PropertyName.DeviceAutoNightvision)` (return values are `true/false` or `undefined`).

**Comment by bropat** [comment]
As @PhilippEngler already wrote, it's already possible.
