### ISSUE TITLE
[Bug]: Streaming Command with Floodlight results in ERROR_INVALID_COMMAND

### ISSUE THREAD

**Issue by thieren** [bropat/eufy-security-client#215]
### Client version

2.2.0-rc.2

### Node version

-

### Operating System type

Other

### Operating system version

-

### Describe the bug

Some users have reported that streaming with Floodlight cameras doesn't work anymore in 2.2.0-rc versions.

### To reproduce

2. Click on '...'

### Screenshots & Logfiles

[eufy-log.log](https://github.com/bropat/eufy-security-client/files/9586261/eufy-log.log)

### Additional context

More information can be found in [this issue](https://github.com/homebridge-eufy-security/plugin/issues/143).

Maybe this has something to do with [this pr](https://github.com/bropat/eufy-security-client/pull/171) which was introduced to get streaming for T8420 working? Maybe different firmware versions need different commands for the 8420?

**Comment by thieren** [comment]
Just checked again.

The tested command for T8420 in the PR worked for `main_sw_version: 2.0.4.8`.

The new Error was reported for `main_sw_version: 1.0.0.35`.

**Comment by smitty078** [comment]
I’m experiencing this same issue as well with the same model of floodlight. I am on firmware 1.0.0.35 and there is no newer firmware available when checking for an update.

**Comment by smitty078** [comment]
In the additional context your reference a pull request. This is absolutely the cause of the issue. The user that submitted the or fixed the issue for what appears to be an 8420X (floodlight 2k - firmware version is 2.x.x.x) which is distinctly different from the 8420 (floodlight, not 2k - firmware versions at 1.x.x.x).

The code in the pr implements a check by matching serial number starts with T8420 - both the 8420 and 8420X have serial numbers starting with 8420, but use different commands. The pr uses the wrong approach to fix the issue.

**Comment by thieren** [comment]
@smitty078 Thx for checking. I too believe this to be the cause.

I've created a PR to fix this: https://github.com/bropat/eufy-security-client/pull/217

Can you test this by any chance?

**Comment by smitty078** [comment]
Can confirm your new PR fixes my issue.

Side note: any reason not to change:
`(device.getSerial().startsWith("T8420") && isGreaterEqualMinVersion('2.0.4.8', this.getSoftwareVersion()))`

To this:
`this.getModel() === "T8420X"`

Using model number may be more resilient to future serial number and/or firmware version changes that are out of your control. At the same time, going _only_ by model number may not be narrow enough scope to resolve issues for all. There's an over/under on how to approach it.

For what it's worth, I tested it both ways and resolves for me (8420 NOT 8420X). The later model-based condition should probably be verified by an 8420X user (floodlight 2K).

**Comment by smitty078** [comment]
I also see other opportunities within the code where the 8420 is an oddball where there are firmware checks to differentiate the several models of 8420 that are out there. There may be an opportunity to refactor to support different models of the 8420 as completely separate devices rather that implementing one-off checks throughout different areas of the code. This of course is outside the scope of this bug and a thought for another day.

**Comment by thieren** [comment]
@smitty078 I think you're right. Checking against only the model should in theory resolve the issue just as well.
As for why I used this approach: I did follow the pattern of the other parts of the source. So the overall decision would have to be made by @bropat I think.

**Comment by bropat** [comment]
@smitty078 @thieren 

In the original source code from Eufy, the firmware version is queried for some devices and a decision is made based on this as to which command is sent. From this I conclude that some devices can send the respective command differently after a firmware update.

For this reason, I find @thieren's last suggestion better, which is following the pattern of the other parts of the source.
