### ISSUE TITLE
[Feature request]: Support Garage-Control Cam

### ISSUE THREAD

**Issue by AnAnonymousUsername** [bropat/eufy-security-client#219]
### Describe the solution you'd like

Please add support for the newly released [Garage-Control Cam](https://us.eufy.com/products/E84521W1).

**Comment by bropat** [comment]
I need access to the device to implement it, but at the moment I am already implementing other devices.
If you want to share the device with me, I'll get back to you as soon as I can take care of it.
Let me know.

**Comment by AnAnonymousUsername** [comment]
Sure, just let me know when and what I need to do.

**Comment by fulviofreitas** [comment]
> I need access to the device to implement it, but at the moment I am already implementing other devices. If you want to share the device with me, I'll get back to you as soon as I can take care of it. Let me know.

How should we share the device with you? I may send one for you if you need it.

**Comment by bropat** [comment]
You can simply share it with me from the Eufy app with admin rights on the following account:

* patrick.broetto+us1@gmail.com

**Comment by fulviofreitas** [comment]
> You can simply share it with me from the Eufy app with admin rights on the following account:
> 
> * [patrick.broetto+us1@gmail.com](mailto:patrick.broetto+us1@gmail.com)

done ✅

**Comment by ajaymdesai** [comment]
@bropat I'm interested in this feature. I'm also a developer so I can help out if you need some coding help. I have two of these devices.

**Comment by fulviofreitas** [comment]
@bropat do you have any updates on this feature?

**Comment by AnAnonymousUsername** [comment]
Any progress here?

**Comment by bropat** [comment]
Sorry, once again I didn't have enough time to implement this device completely.
If someone could share the device with me again, I will try to implement the remaining functionalities:

* patrick.broetto+eu1@gmail.com (for EU)
* patrick.broetto+us1@gmail.com (for US)

I remind you again that to implement I have to run and test all the functionalities.

Thanks!

**Comment by AnAnonymousUsername** [comment]
Sent

**Comment by AnAnonymousUsername** [comment]
Looks like you've added support now. Thank you. Do you still need device access, or can I remove that now?

**Comment by bropat** [comment]
@AnAnonymousUsername 
You can remove it. Thanks!

**Comment by DWLaurie** [comment]
I have a question on this implementation.
Was it only the cam support that was added?
Or was Door Position added as well?
Was support for state (Home/Away/Night/Off) added?
