### ISSUE TITLE
[Feature request]: T8530 Smart Lock w/ video, code, and fingerprint access - and base station (T8021)

### ISSUE THREAD

**Issue by mwexcell** [bropat/eufy-security-client#220]
### Describe the solution you'd like

I have a brand new T8530. Looks like it isn't supported. Can I help get support for this device added?

I've followed the instructions for setup. It is running the latest Firmware: 1.1.5.4 as of 9/17.

I would be happy to share my Eufy home with you (this, and the base for it, are the only Eufy devices I currently have), if this is something that is doable. I can probably also help with debug from this end if there is anything you would like me to do to help.

Again, I haven't yet share the device with you. I will. Just let me know if and when you would like me to do that.

**Comment by bropat** [comment]
@mwexcell 

Yes, by sharing the device with me, but at the moment you have to be a bit patient as I am already implementing other devices.

**Comment by bropat** [comment]
As soon as I can take care of it, I will get back to you.

**Comment by mwexcell** [comment]
No problem. Let me know when you are ready, and I'll share the device with you.

**Comment by atlflyer** [comment]
I also have this device and am willing to share/help.

**Comment by modogo2000** [comment]
I.m willing to help too I have the device

**Comment by cchchris** [comment]
Also willing to help if needed

**Comment by billdwhite** [comment]
Also looking to get this device supported.  Let me know if I can help.

**Comment by SamBRZ** [comment]
Hi , was wondering if this device is supported ? Want to buy one in Amazon prime days, so appreciate your feedback

**Comment by xbmcnut** [comment]
@SamBRZ Not as far as anyone is aware. Developer is [awaiting some free time](https://github.com/bropat/eufy-security-client/issues/220#issuecomment-1367509083) before turning attention to this model so we have to be patient.

**Comment by paulbaird87** [comment]
Fingers crossed @bropat has time for this one. I have to say it is my favourite Eufy product to date. Happy to be a guinea pig as well if need be.

**Comment by steven-g-w** [comment]
Hey @bropat I'm happy to share my T8530 with you if you can provide an account for Australia. Also I'm a typescript developer as well, let me know if you need some of my help on this :)

**Comment by bropat** [comment]
I need someone to share the device with admin rights.

If someone wants to share it:

* patrick.broetto+eu1@gmail.com
* patrick.broetto+us1@gmail.com

**Comment by steven-g-w** [comment]
do you have an au account? My region is Australia

**Comment by paulbaird87** [comment]
> I need someone to share the device with admin rights.
> 
> If someone wants to share it:
> If
> * [patrick.broetto+eu1@gmail.com](mailto:patrick.broetto+eu1@gmail.com)
> * [patrick.broetto+us1@gmail.com](mailto:patrick.broetto+us1@gmail.com)

I'm also Australia if you want or need access to one from here @bropat just let me know!

**Comment by bropat** [comment]
You can simply select an account above for Australia. The subdivision eu/us was for a former version of the Eufy Cloud, now it is no longer important ;)

**Comment by steven-g-w** [comment]
Shared to the eu one :)

**Comment by bropat** [comment]
@steven-g-w 

I have to test all the functions so that I can implement them. I hope that's ok. :)

**Comment by steven-g-w** [comment]
That's ok but it'll be nice if you can do it tomorrow after 8AM AEST? I just put the baby to sleep

**Comment by bropat** [comment]
I try my best. My time zone is CET (8AM AEST means from 10 PM CET) ;)

**Comment by steven-g-w** [comment]
Crap. Anytime from 8AM to 8PM AEST works for me.

**Comment by xbmcnut** [comment]
@bropat I have a T8530 in a lab environment I could give you 24/7 access to if that suits better. It's in NZ but that shouldn't matter?

**Comment by bropat** [comment]
@xbmcnut
Yes, much better, because I can only work on it myself when I have time and that could often be at times when it doesn't suit others.

@steven-g-w @paulbaird87 
You can remove the share. Thank you very much and stay tuned!

At the moment I have also been given a lot of devices and so it will take some time until I have implemented everything.

**Comment by xbmcnut** [comment]
> @xbmcnut Yes, much better, because I can only work on it myself when I have time and that could often be at times when it doesn't suit others.
> 
👍Give me 24hrs to move my rig into the garage so it won't disturb anyone.

**Comment by Nicolition** [comment]
Just came here to say thank you @bropat for taking the time to find a solution for the T8530. I just bought mine last week and love this product, but would love it even more once it's accessible in HA.

**Comment by xbmcnut** [comment]
> @xbmcnut Yes, much better, because I can only work on it myself when I have time and that could often be at times when it doesn't suit others.
> 
This has now been done. You have admin access 24/7 as I moved my lab rig into the garage. Let me know if you need me to activate any events at this end (fingerprint, pin code etc.) and I'll fire them off. I work from home so I can be pretty responsive. Good luck and thanks for having a go at this.

**Comment by meijieru** [comment]
Is it trivial to support the newly released E330 (model T8531) once we support this, or would it be more appropriate to open a separate issue for this?

**Comment by bropat** [comment]
@meijieru 

Unfortunately, even very similar devices are often implemented very differently. I can only comment on this specifically when I have access to such a device.
In any case, it would make sense to open a separate topic.

**Comment by bropat** [comment]
@xbmcnut 

__Short update:__

I haven't forgotten about this device, I'm still working on it.
The camera features have already been implemented (including live streaming).

Smart locks are a bit more complex to implement ;)

**Comment by xbmcnut** [comment]
> @xbmcnut
> 
> **Short update:**
> 
> I haven't forgotten about this device, I'm still working on it. The camera features have already been implemented (including live streaming).
> 
> Smart locks are a bit more complex to implement ;)

Thats awesome, thank you. Appreciate the update.

**Comment by meijieru** [comment]
> @meijieru
> 
> Unfortunately, even very similar devices are often implemented very differently. I can only comment on this specifically when I have access to such a device. In any case, it would make sense to open a separate topic.

Opened a new issue #457 here.

**Comment by bropat** [comment]
__Short update:__

Opening and closing the lock now also works.

__Todo:__ Push notifications and settings must be implemented.

**Comment by xbmcnut** [comment]
Thanks again. Would my expectations be too high if the integration (through Home Assistant) was able to report the user that unlocked the door? Extra points for the method used 🤗

**Comment by paulbaird87** [comment]
> **Short update:**
> 
> Opening and closing the lock now also works.
> 
> **Todo:** Push notifications and settings must be implemented.

Thanks @bropat. Is this something we can implement  from our end in HA yet?

**Comment by bropat** [comment]
> Would my expectations be too high if the integration (through Home Assistant) was able to report the user that unlocked the door? Extra points for the method used 🤗

Both implemented ;)
In the next release the device is supported.

The last thing I need to add is the user management function.

**Comment by xbmcnut** [comment]
You Sir are a legend. Thank you so much. We heard the system beeping and farting this morning so knew something was up 😁😁

**Comment by Nicolition** [comment]
Wow! @bropat 
Thank you so much for all the time you put into this. It was the only thing left to work with Home Assistant at home. Your the best and thanks again 🤝

**Comment by kineticscreen** [comment]
Just a note that I just got a firmware update to 1.3.0.8 on the video smart lock. Just had bug fixes as the changeling, but you never know what else might have snuck in.

**Comment by kineticscreen** [comment]
BTW do you do beta releases? Let us know if you need testers once you've got it built.

**Comment by nexusis7** [comment]
ahhh finally HA integration! cant wait .. the only thing missing in mine is the T8530

**Comment by kineticscreen** [comment]
@bropat is there an ETA for version 3.0.0? Any other thread we should keep an eye on the progress of?

**Comment by fuatakgun** [comment]
I just want to set the scene here;
- we all are sparing our free time on this, sharing ETAs might be overkill
- after client release, depending on the consumer, target systems should pick up the latest version too. Such us eufy-security-ws add-on, iobroker plugin, home bridge plugin etc So having a release here doesn't mean immediate solution if you are not directly consuming this library

**Comment by kineticscreen** [comment]
Totally understand. I guess I was more asking if there is a roadmap or something, just seeing that this has been earmarked for the 3.0 release, which I can only assume is some kind of larger milestone.

**Comment by town3r** [comment]
@bropat Has been updating the dev build regularly along w/ its [readme](https://github.com/bropat/eufy-security-client/blob/develop/README.md) changelog.

**Comment by SkyRanger90** [comment]
Great work @bropat !! nice to see those lock updates and door lock unlock events in the debug of the addon eufy-security-ws. Wonder if there’s a way to get these under system log events.

**Comment by paulbaird87** [comment]
> @bropat Has been updating the dev build regularly along w/ its [readme](https://github.com/bropat/eufy-security-client/blob/develop/README.md) changelog.

Sorry for the silly question @town3r , but I am unsure how to get the dev build fot the eufy-security-ws add-on, so I can see these options in the debug?

**Comment by town3r** [comment]
> Sorry for the silly question @town3r , but I am unsure how to get the dev build fot the eufy-security-ws add-on, so I can see these options in the debug?

Sadly I have no idea. 
I use the homebridge plugin that utilizes this device library. Were all excited for the big milestone update :)

**Comment by SkyRanger90** [comment]
Thank you @bropat for the update !

**Comment by nexusis7** [comment]
Yes! Thank you @bropat and team. Amazing work!

**Comment by voodoomutt** [comment]
hi, this is update is fantastic, thank you.  

dumb question -is lock / unlock functionality also included for the s330 / T8530?  I can see lock status entity but not lock control

**Comment by nexusis7** [comment]
> hi, this is update is fantastic, thank you.
> 
> dumb question -is lock / unlock functionality also included for the s330 / T8530? I can see lock status entity but not lock control

its disabled by default. you will need to enable the entities manually

**Comment by thiagobalzano** [comment]
Hi there, I just installed this update, the 2.3.9 hksk - is this one right?
So, the chime and the front door lock both show up in Homekit, but the lock has a "no supported" label with a little house icon, and clicking on it doesn't do anything. The camera doesn't show up either. What am I doing wrong? How can I enable entities manually? When I click on the Lock, it just shows "Ignore Device" + a toggle. Hope someone can help me! Thank you!

**Comment by jevins09** [comment]
Thank you @bropat for this amazing plugin! I'm using eufy security client as a Homebridge plugin. I've also added it to my HomeKit integration in iOS. 

In my Home app in iOS I'm able to see the lock status of the door but I'm not able to see the device added as a camera and therefore cannot access the device's camera from the home app.

Is anyone able to access the camera feed from the smart lock in their HomeKit? If so, how did you set it up?

**Comment by fbelkadhi** [comment]
> > Sorry for the silly question [@town3r](https://github.com/town3r) , but I am unsure how to get the dev build fot the eufy-security-ws add-on, so I can see these options in the debug?
> 
> Sadly I have no idea. I use the homebridge plugin that utilizes this device library. Were all excited for the big milestone update :)

First of all a very big thanks to @bropat  for all great works he did. 

Hi jevins09, I'm using the Homebridge plugin too and I installed all the the required npm dependencies for eufy-security-client but no changes happened and I did not find a documentation to explain how let eufy-security-client works :(
Please help, thank you.
