### ISSUE TITLE
[Feature request]: Support for Homebase 3 [S380] and eufyCam 3 [S330]

### ISSUE THREAD

**Issue by gmogoody** [bropat/eufy-security-client#228]
### Describe the solution you'd like

I have been using the plugin for years. Just pulled the trigger to update my Homebase 2 to Homebase 3. Look forward to continuing to use the plugin once you have time to add support. 

Originally just looking for equivalence support as homebase 2. 

Once I receive mine I can also work with Devs on collecting logs etc. 

Setup: Homebridge running in Docker on Synology NAS

**Comment by mahst68** [comment]
+1. Please add HomeBase 3

**Comment by gabrielcsapo** [comment]
Everything seems to work except for DeviceEnabled

```
{"name":"[EufySecurity-2.2.0-beta.5]","hostname":"orangepi3-lts","pid":4504,"level":20,"msg":"Front Door GET DeviceEnabled: undefined","time":"2022-10-05T05:24:34.960Z","v":0}
```

Looking into this now.

**Comment by gabrielcsapo** [comment]
Looking at the camera connected to the s380 I get 

```
> camera.properties
{
  motionDetected: false,
  personDetected: false,
  personName: '',
  name: 'Front Door',
  model: 'T8140-Z',
  serialNumber: 'xxxxx',
  type: 14,
  hardwareVersion: 'T8140-Z',
  softwareVersion: '4.6.9',
  stationSerialNumber: 'xxxxxx',
  rtspStreamUrl: '',
  lastChargingDays: -1,
  lastChargingFalseEvents: 0,
  lastChargingRecordedEvents: 0,
  lastChargingTotalEvents: 0,
  batteryUsageLastWeek: 0,
  recordingClipLength: 60,
  recordingRetriggerInterval: 5,
  recordingEndClipMotionStops: true,
  snoozeTime: 0,
  'hidden-snoozeStartTime': 0,
  watermark: 2,
  motionDetectionSensitivity: 4,
  motionDetectionType: 0,
  snooze: false,
  audioRecording: true,
  powerSource: 0,
  batteryTemperature: 17,
  speaker: true,
  powerWorkingMode: 1,
  antitheftDetection: false,
  chargingStatus: 0,
  statusLed: true,
  speakerVolume: 92,
  state: 1,
  rtspStream: false,
  notificationType: 1,
  autoNightvision: true,
  microphone: true,
  battery: 86,
  motionDetection: true,
  wifiRssi: -54,
  wifiSignalLevel: 4
}
```

When I query a camera connected to a base station 2

```
> cameraFromBase2.properties
{
  motionDetected: false,
  personDetected: false,
  personName: '',
  name: 'Left Side House',
  model: 'T8140-Z',
  serialNumber: 'xxxx',
  type: 14,
  hardwareVersion: 'T8140-Z',
  softwareVersion: '4.6.9',
  stationSerialNumber: 'xxxx',
  rtspStreamUrl: '',
  lastChargingDays: 112,
  lastChargingFalseEvents: 0,
  lastChargingRecordedEvents: 850,
  lastChargingTotalEvents: 850,
  batteryUsageLastWeek: 0,
  pictureUrl: 'xxxxx',
  recordingClipLength: 60,
  recordingRetriggerInterval: 5,
  recordingEndClipMotionStops: true,
  snoozeTime: 0,
  'hidden-snoozeStartTime': 0,
  watermark: 0,
  wifiRssi: -53,
  wifiSignalLevel: 4,
  audioRecording: true,
  state: 0,
  motionDetectionType: 2,
  notificationType: 1,
  statusLed: true,
  antitheftDetection: false,
  autoNightvision: true,
  rtspStream: false,
  motionDetectionSensitivity: 4,
  battery: 68,
  powerWorkingMode: 1,
  speaker: true,
  enabled: true,
  powerSource: 0,
  microphone: true,
  speakerVolume: 92,
  chargingStatus: 2,
  motionDetection: true,
  batteryTemperature: 14
}
```

**Comment by gabrielcsapo** [comment]
so enabled is just not queryable when the camera is connected to the s380 base station, this might be a bug on the base station side.

**Comment by mahst68** [comment]
That sucks. Not surprised though… running some RTSP tests, apparently it kills RTSP for the cameras after 15 seconds then requires you to go back into camera settings to re-enable RTSP. We are assuming it had to do with solar power and eufy unwillingness to let batteries drain due to promoting “forever power” on these new cameras. Curiously, it gave me an option to pair the new camera with the old homebase 2 since it was on my same account. I wonder, even though it defeats the purpose of 4K recording, if a new camera paired to the old base works. I returned mine until all this can be sorted out or I would try the test myself. Thank You,Michael HudecIAP Unit Manager - Manufacturing Control – Repair OperationsIndiana Auto Plant - HDMA2755 North Michigan AvenueGreensburg, IN 47240-9341Direct Connect #: 4502(812)651-6250 "Work Smarter... Not Harder..." - Scrooge McDuck  (Carl Barks, Disney Studios, 1947)Sent from my iPhoneOn Oct 5, 2022, at 3:02 AM, Gabriel Csapo ***@***.***> wrote:﻿
so enabled is just not queryable when the camera is connected to the s380 base station, this might be a bug on the base station side.

**Comment by michaeleberhardt** [comment]
> Everything seems to work except for DeviceEnabled
> 
> ```
> {"name":"[EufySecurity-2.2.0-beta.5]","hostname":"orangepi3-lts","pid":4504,"level":20,"msg":"Front Door GET DeviceEnabled: undefined","time":"2022-10-05T05:24:34.960Z","v":0}
> ```
> 
> Looking into this now.

Does P2P Discovery work for you? For my S380, P2P Discovery always fails..

**Comment by gabrielcsapo** [comment]
> > Everything seems to work except for DeviceEnabled
> 
> > 
> 
> > ```
> 
> > {"name":"[EufySecurity-2.2.0-beta.5]","hostname":"orangepi3-lts","pid":4504,"level":20,"msg":"Front Door GET DeviceEnabled: undefined","time":"2022-10-05T05:24:34.960Z","v":0}
> 
> > ```
> 
> > 
> 
> > Looking into this now.
> 
> 
> 
> Does P2P Discovery work for you? For my S380, P2P Discovery always fails..

Fails for me as well

**Comment by Palmke** [comment]
Probably doesn't work because it's a new type of homebase, not like any we've seen with the first one, E, 2 or those doorbell base stations.
If one of you knows how to read the app's code, you can probably find out how it works. 
It will work eventually (using the same communication protocol), as it integrates with almost every camera this client already supports.

**Comment by gabrielcsapo** [comment]
Yeah most probably it will be fixed, probably good to flag it as it doesn't work right due to API differences between it and the home base 2. I will keep mine in the box for the time being. Hopefully end of October with the support of more cameras they add support for HomeKit.

**Comment by raneses** [comment]
Throwing my hat in the ring to get this update in place -- let me know how I can help. For context, we just picked up a pair of EufyCam S330 including the HomeBase 3.

**Comment by kaesi-jones** [comment]
I got 2 EufyCam S330 and a S380 HomeBase at the weekend and can integrate everything. However, I have a problem with the "Guard Mode". When I set this via the variable, the "Current Mode" does not change. This worked without problems with the HomeBase 2. Does anyone have an idea how to solve the problem?

**Comment by Maddin1684** [comment]
> I got 2 EufyCam S330 and a S380 HomeBase at the weekend and can integrate everything. However, I have a problem with the "Guard Mode". When I set this via the variable, the "Current Mode" does not change. This worked without problems with the HomeBase 2. Does anyone have an idea how to solve the problem?

Hey, my S330 is on track…
Do you have integrated it with the HB Plugin? So you can see the „Camera“ in HomeKit?

**Comment by kaesi-jones** [comment]
I use the "eusec" adapter in io.broker

**Comment by Palmke** [comment]
If you read the guard mode flag from the raw properties you get from the web API, is it the currently known p2p parameter that is used in this client?
Perhaps the S380 uses a different parameter for guard mode or requires a different channel to set it.

**Comment by michaeleberhardt** [comment]
As far as I understand, the current status can be read via HTTP API. When changing a value, this is done via P2P. As P2P-Discovery does not work for Homebase 3 yet, new values cannot be sent to the base.

**Comment by gmogoody** [comment]
> As far as I understand, the current status can be read via HTTP API. When changing a value, this is done via P2P. As P2P-Discovery does not work for Homebase 3 yet, new values cannot be sent to the base.

Is the consensus right now the S380 has a FW bug or did Eufy close the previous APIs/Previous methods?

I use this setting through the plugin. I will wait on swapping them out for now since it’s such a pain with existing cams.

**Comment by bropat** [comment]
Can someone share the device with me with admin rights on the following email?

* patrick.broetto+testing2@gmail.com

Thanks!

**Comment by michaeleberhardt** [comment]
> Can someone share the device with me with admin rights on the following email?
> 
> * [patrick.broetto+testing2@gmail.com](mailto:patrick.broetto+testing2@gmail.com)
> 
> Thanks!

I will give you Access 😎

**Comment by Palmke** [comment]
@bropat out of curiosity, are you only adding the S380 homebase, or also the S330 eufycam 3?

**Comment by mutchu** [comment]
Hi there,
I confirm that old and new generation cameras do not work in Homekit when connected to HomeBase 3.
Hope for HomeBase 3 support soon please.
Thanks

**Comment by bropat** [comment]
> @bropat out of curiosity, are you only adding the S380 homebase, or also the S330 eufycam 3?

If I find time both ;)

**Comment by mutchu** [comment]
> > @bropat out of curiosity, are you only adding the S380 homebase, or also the S330 eufycam 3?
> 
> If I find time both ;)

Only HomeBase 3 S380 with ring doorbell ans eufycam2

**Comment by Palmke** [comment]
@bropat have you gotten access yet? 
I'm waiting for this change before buying a set, but if it helps you, I can buy the set now and then give you access instead.

**Comment by bropat** [comment]
@Palmke 

Yes @michaeleberhardt gave me access.

Progress status:

Basic communication with the new station is now working.

**Comment by michaeleberhardt** [comment]
@bropat I am curious: what did you have to modify to get the station discovered via p2p?
Looking forward to the next release :-)
Thanks for your effort!

**Comment by mutchu** [comment]
Great news, I can't wait to see the update so that everything works

**Comment by aszymanik** [comment]
@bropat Thank you so much for you work with this integration. I see you have access to a HomeBase 3 and S330.  I have some S300s- would you like access to them? I don't know how much they differ from a S330.

Thank you so much!

**Comment by bropat** [comment]
> @bropat I am curious: what did you have to modify to get the station discovered via p2p? Looking forward to the next release :-) Thanks for your effort!

@michaeleberhardt 

I didn't have to change anything regarding discovery, this part was already working correctly (since the last RC versions).
The P2P communication was not stable and error-prone, as some information is now increasingly compressed into individual data packets.

**Comment by kaesi-jones** [comment]
Maybe it is also helpfull: By changing the Guard mode, I received the following error:
P2PClientProtocol.lookup(): station: T8030P2322440792 - All address lookup tentatives failed.

**Comment by bropat** [comment]
**Update:** P2P communication for Homebase 3 and eufyCam 3 is working stable
**ToDo:** Integrate push notification for this devices

**Comment by bropat** [comment]
@michaeleberhardt 

I need your help to integrate push notification. You would need to generate push events for me.
Please contact me directly via email. 

Thanks!

**Comment by aszymanik** [comment]
> **Update:** P2P communication for Homebase 3 and eufyCam 3 is working stable **ToDo:** Integrate push notification for this devices

How do we update? There's no recent commits on this repo on any branch. Is there somewhere further upstream I should update? eufy-security-ws hasn't had a recent update and npm/eufy-security-client is also about a month old. 

Thank you for all your hard work. Looking forward to putting this to use with just a little guidance as to where to look.

**Comment by bropat** [comment]
At the moment there is no new release. I am working on it. As soon as the new release is available I will announce it here.

**Comment by michaeleberhardt** [comment]
@bropat , Mail sent!

**Comment by bropat** [comment]
**Update:** Push notifications are implemented.
**ToDo**: Start download of event videos over p2p from hb3

**Comment by Palmke** [comment]
Purely out of curiousity, is the HB3 using all new kinds of command types?
I thought it was more of an upgraded and beefed up HB2 (using that firmware as a base).

**Comment by bropat** [comment]
> Purely out of curiousity, is the HB3 using all new kinds of command types?

No, only some things are different or new/safer.
The majority has remained the same, i.e. the old devices can be addressed in the same way with the new HB3.

**Comment by bropat** [comment]
https://support.eufylife.com/s/article/Centralize-Your-Security-Ecosystem-with-HomeBase-3

**Comment by mahst68** [comment]
Anything to recently update? Look like there was good momentum towards an solution up until last week... Any help needed? just curious!

**Comment by bropat** [comment]
I work as best I can, but I have a family with children, work etc, so please be patient.
It's just a spare time project of mine. I don't use Eufy products myself anymore, but I'm still continuing the project.
Please don't ask for an ETA, because I won't name one. There will be a new version as soon as I think it is ready.

**Comment by bropat** [comment]
**Short update:**

* HB3 will be partially supported in the next version. e.g. download of videos still does not work at the moment.
* eufyCam 3 will be supported in the next version

**Comment by bropat** [comment]
New driver version (2.2.0) was released.

**Comment by bropat** [comment]
@signalshift 
This project is not a plugin for Homebridge, but a driver that can be used to communicate with Eufy products.
In your case you have to ask here: https://github.com/homebridge-eufy-security/plugin

**Comment by mahst68** [comment]
@signalshift @bropat 
I have already added an issue enhancement to the eufy-security-plugin for homebridge. It is not assigned and currently not on the roadmap as of yet

**Comment by yooo1999** [comment]
@bropat Is the function [handleDataBinaryAndVideo ](https://github.com/bropat/eufy-security-client/blob/master/src/p2p/session.ts#L1246) compatible for S380 (livestream)

**Comment by kaesi-jones** [comment]
@bropat: I'm thrilled how quickly you wrote the new driver - thanks for that!

Now I can set the state via the "guard" mode without any problems.
When I look at the log file, the station seems to log off every minute.
Any idea what this could be?

Here is the log:

eusec.0 | 2022-11-04 09:19:09.517 | info | (24061) Disconnected from station T8030P2322330784
eusec.0 | 2022-11-04 09:18:09.096 | info | (24061) Connected to station T8030P2322330784 on host 192.168.2.205 and port 22241
eusec.0 | 2022-11-04 09:18:03.824 | info | (24061) Disconnected from station T8030P2322330784
eusec.0 | 2022-11-04 09:17:03.414 | info | (24061) Connected to station T8030P2322330784 on host 192.168.2.205 and port 15642
eusec.0 | 2022-11-04 09:16:58.134 | info | (24061) Disconnected from station T8030P2322330784
eusec.0 | 2022-11-04 09:15:57.690 | info | (24061) Connected to station T8030P2322330784 on host 192.168.2.205 and port 12687
eusec.0 | 2022-11-04 09:15:52.411 | info | (24061) Disconnected from station T8030P2322330784
eusec.0 | 2022-11-04 09:14:51.990 | info | (24061) Connected to station T8030P2322330784 on host 192.168.2.205 and port 13877
eusec.0 | 2022-11-04 09:14:46.706 | info | (24061) Disconnected from station T8030P2322330784
eusec.0 | 2022-11-04 09:13:46.280 | info | (24061) Connected to station T8030P2322330784 on host 192.168.2.205 and port 14581

I also got this:

eusec.0 | 2022-11-04 08:46:35.172 | warn | (14103) Terminated (UNCAUGHT_EXCEPTION): Without reason
eusec.0 | 2022-11-04 08:46:35.170 | info | (14103) terminating
eusec.0 | 2022-11-04 08:46:35.168 | info | (14103) Disconnect from station T8030P2322330784
eusec.0 | 2022-11-04 08:46:35.166 | info | (14103) Disconnect from station T8010N2321261F60
eusec.0 | 2022-11-04 08:46:35.164 | info | (14103) Push notification connection closed
eusec.0 | 2022-11-04 08:46:35.153 | error | --- property '_idleNext' closes the circle
eusec.0 | 2022-11-04 08:46:35.153 | error | \| property '_idlePrev' -> object with constructor 'TimersList'
eusec.0 | 2022-11-04 08:46:35.153 | error | --> starting at object with constructor 'Timeout'
eusec.0 | 2022-11-04 08:46:35.153 | error | (14103) Converting circular structure to JSON
eusec.0 | 2022-11-04 08:46:35.152 | error | at UDP.onMessage [as onmessage] (dgram.js:931:8)
eusec.0 | 2022-11-04 08:46:35.152 | error | at Socket.emit (events.js:400:28)
eusec.0 | 2022-11-04 08:46:35.152 | error | at Socket.<anonymous> (/opt/iobroker/node_modules/eufy-security-client/build/p2p/session.js:76:56)
eusec.0 | 2022-11-04 08:46:35.152 | error | at P2PClientProtocol.handleMsg (/opt/iobroker/node_modules/eufy-security-client/build/p2p/session.js:839:26)
eusec.0 | 2022-11-04 08:46:35.152 | error | at P2PClientProtocol.parseDataMessage (/opt/iobroker/node_modules/eufy-security-client/build/p2p/session.js:1007:26)
eusec.0 | 2022-11-04 08:46:35.152 | error | at P2PClientProtocol.handleData (/opt/iobroker/node_modules/eufy-security-client/build/p2p/session.js:1043:34)
eusec.0 | 2022-11-04 08:46:35.152 | error | at ioBrokerLogger.debug (/opt/iobroker/node_modules/iobroker.eusec/build/lib/log.js:40:29)
eusec.0 | 2022-11-04 08:46:35.152 | error | at ioBrokerLogger._getMessage (/opt/iobroker/node_modules/iobroker.eusec/build/lib/log.js:32:41)
eusec.0 | 2022-11-04 08:46:35.152 | error | at JSON.stringify (<anonymous>)
eusec.0 | 2022-11-04 08:46:35.152 | error | --- property '_idleNext' closes the circle
eusec.0 | 2022-11-04 08:46:35.152 | error | \| property '_idlePrev' -> object with constructor 'TimersList'
eusec.0 | 2022-11-04 08:46:35.152 | error | --> starting at object with constructor 'Timeout'
eusec.0 | 2022-11-04 08:46:35.152 | error | (14103) TypeError: Converting circular structure to JSON
eusec.0 | 2022-11-04 08:46:35.150 | error | --- property '_idleNext' closes the circle
eusec.0 | 2022-11-04 08:46:35.150 | error | \| property '_idlePrev' -> object with constructor 'TimersList'
eusec.0 | 2022-11-04 08:46:35.150 | error | --> starting at object with constructor 'Timeout'
eusec.0 | 2022-11-04 08:46:35.150 | error | (14103) uncaught exception: Converting circular structure to JSON

**Comment by bropat** [comment]
@yooo1999 

Why do you ask?

**Comment by bropat** [comment]
@kaesi-jones 

Thanks!

> Any idea what this could be?

The answer is simple, `ioBroker.eusec` does not yet use the new driver (version `2.2.0`). Therefore the support is not yet given.

**Comment by kaesi-jones** [comment]
O.K. - Can you already say when a new version of ioBroker.eusec is planned that supports the driver?

**Comment by kaesi-jones** [comment]
@bropat

I saw that you updated the driver - thanks a lot! All errors are gone.
