### ISSUE TITLE
`livestream video data` event is not fired

### ISSUE THREAD

**Issue by fuatakgun** [bropat/eufy-security-client#23]
**Describe the bug**  
With latest update, I am not able to receive `livestream video data` events anymore. I have tried with two different cameras, both 2c, and only receiving `livestream audio data` events without video.

**To Reproduce**  
1. Start eufy-security-ws server
2. Initiate start listening
3. Send start live stream command
4. I have received successful message and received chunks of audio data but video data is missing

**Expected behavior**  
Next to audio data, video chunks should be forwarded

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/11085566/126078263-e3b85b04-3028-4db1-8d98-daa22da657bd.png)

**Versions:**  
 - Client version: <client-version>
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**  
Tested with my own fork (https://github.com/fuatakgun/eufy_security) and `livestream_video_data` events are raised.
![image](https://user-images.githubusercontent.com/11085566/126078511-be0ae800-cd78-44ea-bb85-bd7df171c788.png)

**Comment by bropat** [comment]
I have lost an if condition.... my mistake :( Was corrected in version 0.9.2
