### ISSUE TITLE
[Feature request]: Support for Eufy Starlight 4G (T8151)

### ISSUE THREAD

**Issue by witold-gren** [bropat/eufy-security-client#231]
### Describe the solution you'd like

I have been using the plugin for years and it is amazing - it do very good job. I have two places when I don't have network access but also I needed monitor those places, so I decided bought  Eufy Starlight 4G.

I checked and alarm configuration is supported by default (so I have automation that informs me If the alarm will be triggered). Also, it will be nice to have some pop-up windows with real strim in my wall panel :) I see other attributes but to be honest, I did not check yep do they work at all.

Setup: Home Assistant runs in Synology NAS via Virtual Machine.

Log which I found in the container:

```
2022-10-15 19:27:32.511  ERROR Message error 
 NotSupportedError  This functionality is not implemented or supported by T8151XXXYYYZZZ
error stack:
• station.ts:2917 startLivestream
    node_modules/eufy-security-client/src/http/station.ts:2917:19
• message_handler.ts:124 handle
    src/lib/device/message_handler.ts:124:39
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• server.ts:103 receiveMessage
    src/lib/server.ts:103:21
2022-10-15 19:29:32.881  ERROR Message error 
 NotSupportedError  This functionality is not implemented or supported by T8151XXXYYYZZZ
error stack:
• station.ts:2917 startLivestream
    node_modules/eufy-security-client/src/http/station.ts:2917:19
• message_handler.ts:124 handle
    src/lib/device/message_handler.ts:124:39
• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
• server.ts:103 receiveMessage
    src/lib/server.ts:103:21
2022-10-15 19:29:45.783  WARN Station T8151XXXYYYZZZ - Tried all hosts, no connection could be established 
2022-10-15 19:29:45.784  INFO  Timeout connecting to station T8151XXXYYYZZZ
2022-10-15 19:29:50.763  WARN Station T8151XXXYYYZZZ - Tried all hosts, no connection could be established 
2022-10-15 19:29:50.763  INFO  Timeout connecting to station T8151XXXYYYZZZ
```

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/2304938/196008928-18d0687a-b61f-4d39-ab95-f8f8717f8db0.png">

**Comment by bropat** [comment]
Hi @witold-gren 

Thank you very much for the feedback.

I am currently working on the integration of other devices, so as soon as I have time to implement this device as well, I will get back to you here.

**Comment by witold-gren** [comment]
Thank you, I you will need any help/access from my site, just let me know.

**Comment by witold-gren** [comment]
Hey 😀 How can I share access with my device to you? Which email I should use to share device with you?

**Comment by fishingpatrol** [comment]
@bropat @witold-gren - I have this camera setup and willing to share the connection as well.

**Comment by bropat** [comment]
@witold-gren or @fishingpatrol 

You can share it on the following account:

* patrick.broetto+eu1@siag.it

**Comment by fishingpatrol** [comment]
@bropat - I emailed you the info for my setup.

**Comment by witold-gren** [comment]
Thank's @fishingpatrol - I was unavailable last few days and I read this info now. @bropat If you still need access to my devices let me know.. 😀

**Comment by fishingpatrol** [comment]
@bropat - Were you able to access my portal?  Please let me know.
