### ISSUE TITLE
[Feature request]: Support for S300 eufyCam (eufyCam 3C)

### ISSUE THREAD

**Issue by aszymanik** [bropat/eufy-security-client#233]
### Describe the solution you'd like

The S300/S330 eufyCams are the next generation of their battery powered cameras. 

Asking kindly for integration and willing to share my cameras to aid this process.

Thank you!

**Comment by bropat** [comment]
@aszymanik 

Can you share the device with me with admin rights on the following email?

* [patrick.broetto+testing2@gmail.com](mailto:patrick.broetto+testing2@gmail.com)

Thanks!

**Comment by aszymanik** [comment]
Thank you. Shared HB3 and 2 S300's

**Comment by bropat** [comment]
@aszymanik 

I need one more thing, namely the country in which the devices are registered.

**Comment by aszymanik** [comment]
> @aszymanik
> 
> I need one more thing, namely the country in which the devices are registered.
> 
> Found!

US for clarity
