### ISSUE TITLE
[Bug]: Re-Open Motion Detection for T8420x does not work

### ISSUE THREAD

**Issue by eufysecurity** [bropat/eufy-security-client#235]
### Client version

0.9.4

### Node version

14.18.0

### Operating System type

Linux

### Operating system version

Linux 5 VMware

### Describe the bug

Motion Sensor is not working for T8420x. It does not pick up any motion. Motion and Person Motion.

### To reproduce

1. Create Motion on the floodlight cam.
2. get a notification on phone app
3. eufy security ws does not detect any motion

### Additional context

I think line 920 in eufy-security-client/src/http/type.ts needs to be changed

From: 
export const DeviceMotionDetectionIndoorSoloFloodProperty: PropertyMetadataBoolean = {

To:
export const DeviceMotionDetectionProperty: PropertyMetadataBoolean = {

**Comment by eufysecurity** [comment]
There is no errors in the log, but the Floodlight is missing the enable motion detection switch. If you look at line 4018 you can see that [PropertyName.DeviceMotionDetection]: DeviceMotionDetectionIndoorSoloFloodProperty, is commented out right there. and the new Floodlight GenericDeviceProperties is right below it with [PropertyName.DeviceMotionDetection]: DeviceMotionDetectionProperty, on line 4047. Line 920 is referencing the device property that has been commented out.

**Comment by Palmke** [comment]
You should be careful with what you share.
![image](https://user-images.githubusercontent.com/5384698/199556596-a2330968-f944-4cee-89c6-51f09a8a6f55.png)

**Comment by eufysecurity** [comment]
> You should be careful with what you share. ![image](https://user-images.githubusercontent.com/5384698/199556596-a2330968-f944-4cee-89c6-51f09a8a6f55.png)

thank you

**Comment by bropat** [comment]
@eufysecurity 

You are not on the current version of the driver (see above => `'version': '2.1.2'`).
Why do you open a bug again if you are not on the current version?
The version given above (`0.9.4`) is also wrong...
I think this is the version of the other project (`eufy-security-ws`) which is also not up to date!
