### ISSUE TITLE
Wrong 0.9.2 Version

### ISSUE THREAD

**Issue by piitaya** [bropat/eufy-security-client#24]
The 0.9.2 is not the good one on npm.
I think the `npm run build` was forgotten before the `npm publish`.

Maybe a Github Action can void similar issues in the future. What do you think about it ?

**Comment by bropat** [comment]
I'm sorry, but I'm on vacation with limited access, so I made this mistake :(
Yes GitHub Actions could be a good solution ;)
In the meantime I have released a new version.

**Comment by piitaya** [comment]
Nice for the new version! It works! 🚀 
No problem ! Have good vacations 🏝
I will look at Github Actions and create a PR.
