### ISSUE TITLE
[Bug]: T8422 Camera Motion or Person Detection Not Working

### ISSUE THREAD

**Issue by kevinfowler** [bropat/eufy-security-client#240]
### Client version

2.2.2

### Node version

v16.14.0

### Operating System type

Linux

### Operating system version

Fedora 35

### Describe the bug

I am using eufy-security-ws to test.  I am having issues with a Eufy Floodlight Camera T8422.  When I start the ws server and connect to it with the ws client everything registers with Eufy ok.  It receives notifications on the server end.  However the ws client does not show any of the push messages from the motion or person detection.  I can see on the server it is receiving the push message from Eufy but it might not be formatted correctly for the ws server to send anything to the ws client.  When I look at the push messages the ws server received this is what it gets when there is motion on the camera (I removed part of the serial numbers):

2022-11-07 16:31:34.102  DEBUG [EufySecurity.onPushMessage] Received push message
{
  name: '',
  event_time: 1667838692119,
  type: 37,
  station_sn: 'T8422N002XXXXXXX',
  device_sn: 'T8422N002XXXXXXX',
  title: 'Floodlight',
  content: 'Someone has been spotted',
  push_time: 1667838693977,
  channel: undefined,
  cipher: undefined,
  event_session: '20221107_113132',
  event_type: undefined,
  file_path: '',
  pic_url: 'https://security-app.eufylife.com/v1/s/g/gQqcIw_2l',
  push_count: 2,
  notification_style: 3,
  tfcard_status: undefined,
  alarm_delay_type: undefined,
  alarm_delay: undefined,
  alarm_type: undefined,
  sound_alarm: undefined,
  user_name: undefined,
  user_type: undefined,
  user_id: undefined,
  short_user_id: undefined,
  station_guard_mode: undefined,
  station_current_mode: undefined,
  person_name: undefined,
  sensor_open: undefined,
  device_online: undefined,
  fetch_id: undefined,
  sense_id: undefined,
  battery_powered: undefined,
  battery_low: undefined,
  storage_type: 1,
  unique_id: 'eb17c23250d73365d5627e30daaf98d5',
  automation_id: undefined,
  click_action: undefined,
  news_id: undefined
}

When this happens NOTHING shows on the ws client at all.

As a comparison, my Eufy doorbell works correctly.  When my Doorbell camera detects motion, the following message is received on the ws server console:

022-11-07 16:32:53.133  DEBUG [EufySecurity.onPushMessage] Received push message
{
  name: 'Doorbell',
  event_time: 1667838771884,
  type: 7,
  station_sn: 'T8010P132XXXXXXX',
  device_sn: 'T8210P202XXXXXXX',
  title: 'Eufy Security',
  content: 'Doorbell:Someone has been spotted',
  push_time: 1667838773032,
  channel: 0,
  cipher: 66,
  event_session: '20221107_113251',
  event_type: 3102,
  file_path: '/media/mmcblk0p1/Camera00/h265_20221107113247.dat',
  pic_url: 'https://security-app.eufylife.com/v1/s/g/dd3InQgnB',
  push_count: 1,
  notification_style: 2
}

When this is received I see a lot of messages on the ws client end similar to the following:

eufy-security>
{
  type: 'event',
  event: {
    source: 'device',
    event: 'property changed',
    serialNumber: 'T8210P202016046C',
    name: 'personDetected',
    value: true
  }
}

Some of the things I am seeing different between the two sets of messages received above are that the T8422 camera has a blank name and a type of 37.  The Doorbell camera has a type of 7.  I also noticed event_type is undefined for the T8422 but is 3102 for the Doorbell camera.  I am guessing the event_type of undefined could be the issue.

There is a possibility this is an issue with the eufy-security-ws and not the eufy-security-client that it is using.  But it looks to me like it's an issue with the way the eufy-security-client is interpreting the push messages from Eufy.

### To reproduce

1. Start the eufy-security-ws server with a config file to connect to Eufy.
2. Start the eufy-security-ws client to connect back to the server.
3. Stand in front of the T8422 camera and make some motion.
4. I will receive a pop-up on my phone that motion is detected.  I will see push messages on the eufy-security-ws server that it is also receiving the messages.  However nothing shows on the eufy-security-ws client at all.

**Comment by bropat** [comment]
@kevinfowler 

I also need the line that starts with `Raw push message received`.

**Comment by kevinfowler** [comment]
Thanks for the follow-up.  I had to do the random trustedDeviceName change mentioned in the other #242 issue to get it working again.  But here is the Raw push message received when there is motion on the camera:

2022-11-12 22:06:08.481  DEBUG [eufy-security-client/src/push/service.ts:493  PushNotificationService.onMessage] Raw push message received 
{
  id: '67AF5600',
  from: '348804314802',
  to: 'cZi0uTzxC9BXvdiPurgn1_',
  category: 'com.oceanwing.battery.cam',
  persistentId: '0:1668290768409034%0d2a775cf9fd7ecd',
  ttl: 3600,
  sent: '1668290768398',
  payload: {
    device_sn: '',
    payload: {
      msg_type: 18,
      event_type: 3102,
      device_sn: 'T8422N002XXXXXXX',
      name: 'Garage',
      channel: 0,
      cipher: 132,
      session_id: '20221112_170607',
      pic_url: 'https://security-app.eufylife.com/v1/s/g/LjtnflCXt',
      create_time: 1668290767025,
      trigger_time: 1668290767023,
      file_path: '/media/mmcblk0p1/Camera00/20221112170607.dat',
      push_count: 2,
      notification_style: 3,
      storage_type: 1,
      unique_id: '26ad0816b064d1a22e035d5b99eb2a04'
    },
    station_sn: 'T8422N002XXXXXXX',
    'google.c.sender.id': '348804314802',
    title: 'Floodlight',
    type: '37',
    push_time: '1668290768375',
    event_time: '1668290767025',
    content: 'Someone has been spotted'
  }
}

**Comment by bropat** [comment]
@kevinfowler 

You wrote above that you use `eufy-security-ws`. Which version?

**Comment by kevinfowler** [comment]
I normally use this library via the home assistant eufy-security plugin and the eufy-security-ws container.  However, I have been testing it with running eufy-security-ws server and client manually with the latest version 1.1.0.

**Comment by fuatakgun** [comment]
By the way, i have updated home assistant addon to latest version of eufy-security-ws

**Comment by bropat** [comment]
Will be fixed in the next version (`2.3.0`).
