### ISSUE TITLE
[Bug]: Unable to login

### ISSUE THREAD

**Issue by Palmke** [bropat/eufy-security-client#242]
### Client version

2.2.2

### Node version

v16.18.0

### Operating System type

Docker

### Operating system version

Raspberry OS

### Describe the bug

It seems the login isn't working anymore.
When using https://mysecurity.eufylife.com/apieu/v2/passport/login I do see a proper response with a data field.
When logging into the eufy app with the configured user, everything works OK in the app, just not this client apparently?
The app does not appear to have any changed login endpoints, although I did spot new paths:
`passport/update_agreement_records`, `passport/query_agreement_msg` and `passport/query_agreement_records`. 
I am getting this stack trace and then that's it:

```
2022-11-09 17:32:34.406  DEBUG [EufySecurity._initializeInternals] No stored data from last exit found 
2022-11-09 17:32:34.413  DEBUG [EufySecurity._initializeInternals] Handling of driver update 
{
  currentVersion: 2.22,
  previousVersion: 0
}
2022-11-09 17:32:34.992  DEBUG [undefined.constructor] Loaded API_BASE: https://security-app-eu.eufylife.com 
2022-11-09 17:32:34.999  DEBUG [EufySecurity._initializeInternals] Load previous login_hash: <redacted> 
2022-11-09 17:32:35.003  DEBUG [EufySecurity._initializeInternals] Generated new openudid: 962f147b4eb1406d 
2022-11-09 17:32:35.005  DEBUG [EufySecurity._initializeInternals] Generated new serial_number: 634a5dba74dd 
2022-11-09 17:32:35.080  DEBUG [src/lib/server.ts:489  EufySecurityServer.start] Starting server on host 0.0.0.0, port 3000 
2022-11-09 17:32:35.087  INFO  [src/lib/server.ts:495  EufySecurityServer.start] Eufy Security server listening on host 0.0.0.0, port 3000 
2022-11-09 17:32:35.091  DEBUG [HTTPApi.login] Login and get an access token 
{
  token: null,
  tokenExpiration: null
}
2022-11-09 17:32:35.098  DEBUG [HTTPApi.request] Request: 
{
  method: 'post',
  endpoint: 'v2/passport/login_sec',
  token: null,
  data: {
    ab: '<redacted>',
    client_secret_info: {
      public_key: '04bc749631da017d514f498652a849a7df4f7ade1731282479ba92b5d0856c6861c1e95c29df98eeef8a593e298edc0686e52747d948d31b29d5bae0a49719f391'
    },
    enc: 0,
    email: '<redacted>',
    password: '[***]',
    time_zone: 0,
    transaction: '1668015155096'
  }
}
2022-11-09 17:32:35.195  DEBUG [HTTPApi.request] Response: 
{
  response: {
    code: 0,
    msg: 'Succeed.'
  }
}
2022-11-09 17:32:35.204  ERROR [HTTPApi.login] Generic Error: 
 TypeError  Cannot read properties of undefined (reading 'user_id')
error stack:
• api.ts:289 login
    node_modules/eufy-security-client/src/http/api.ts:289:66

• task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5

• eufysecurity.ts:662 connect
    node_modules/eufy-security-client/src/eufysecurity.ts:662:9

• server.ts:496 start
    src/lib/server.ts:496:9

• server.ts:66 <anonymous>
    src/bin/server.ts:66:9
```

Same issue as: https://github.com/bropat/eufy-security-ws/issues/146

### To reproduce

Start the client.

**Comment by bropat** [comment]
@Palmke 

I have just carried out a test and it works perfectly. I think Eufy may have bungled some servers again.

```json
{
   "code":0,
   "msg":"Succeed.",
   "data":{
      "user_id":"redacted",
      "email":"redacted",
      "nick_name":"pat***",
      "auth_token":"redacted",
      "token_expires_at":1670615045,
      "avatar":"",
      "invitation_code":"redacted",
      "inviter_code":"",
      "verify_code_url":"",
      "mac_addr":"",
      "domain":"security-app-eu.eufylife.com",
      "ab_code":"IT",
      "geo_key":"redacted",
      "privilege":0,
      "phone":"",
      "phone_code":"",
      "server_secret_info":{
         "public_key":"0470ca96234263082120ab0646918187a9df3f0b70f1429e349b5d8a7bcde7cc4f5dd00fadbe1fd225ed0576fce145c785c8ed6b667485619bbcf57b2e5faa8405"
      },
      "params":[
         {
            "param_type":10002,
            "param_value":"off"
         }
      ],
      "trust_list":[
         
      ]
   }
}
```

**Comment by bropat** [comment]
However, it could also be that when the token is renewed, the values are no longer returned as they were at the first login.
If you have this problem, you could try deleting the file `persistent.json` and restart the process and see if it works again (forces a new 1st login).

**Comment by Palmke** [comment]
I have tested a custom Docker image and your public image, so in case of a new Docker container (with different image), this `persistent.json` file should not exist yet.

**Comment by bropat** [comment]
@Palmke 

I can't replicate this problem, I get the correct complete answer from the EU Eufy servers.... :(

**Comment by lolouk44** [comment]
> you could try deleting the file `persistent.json`
I've tried this:
```
docker-compose down
docker systen prune -a -f
docker volume prune -f
docker-compose up -d
```
Same error. I've also tried other docker versions (1.0.1, 1.0.0, 0.9.4), so brand new setups, same error...

**Comment by Palmke** [comment]
Perhaps you are talking to a different server and it's just a hiccup (strangely enough the eufy app keeps on working fine).
Maybe users are getting (shadow)banned and this data is omitted on purpose...

Can you keep the client running for a while, perhaps send some commands?

**Comment by lolouk44** [comment]
> Maybe users are getting (shadow)banned and this data is omitted on purpose...

I'm going to stop the container for the night and try again tomorrow in case of too many loging failures resulting in some sort of ban...

**Comment by Palmke** [comment]
Webportal endpoint works fine...

Calls `https://mysecurity.eufylife.com/apieu/v2/passport/login`

![Screenshot from 2022-11-09 20-59-33](https://user-images.githubusercontent.com/5384698/200929421-b9cec9a5-d36c-4393-b1dc-2d1d63963ab0.png)

**Comment by Palmke** [comment]
Webportal endpoint works fine...

Calls `https://mysecurity.eufylife.com/apieu/v2/passport/login`

![Screenshot from 2022-11-09 20-59-33](https://user-images.githubusercontent.com/5384698/200929634-3b82fefa-69ab-46b1-a68c-a0477a4f03b0.png)

**Comment by lolouk44** [comment]
> Webportal endpoint works fine...
> 
> Calls `https://mysecurity.eufylife.com/apieu/v2/passport/login`
> 
> ![Screenshot from 2022-11-09 20-59-33](https://user-images.githubusercontent.com/5384698/200929634-3b82fefa-69ab-46b1-a68c-a0477a4f03b0.png)

Interesting, I've clicked the above URL and I get `404 page not found` I'm based in the UK in case it makes any difference...

**Comment by Palmke** [comment]
@lolouk44 it's a `POST`, not a `GET` (clicking a link is `GET`)

**Comment by lolouk44** [comment]
> @lolouk44 it's a `POST`, not a `GET` (clicking a link is `GET`)

🤦‍♂️

**Comment by bropat** [comment]
@Palmke 

But in your example above you also get a correct answer including `user_id`.

**Comment by bropat** [comment]
The `user_id` is needed to generate the `gtoken`: 

```typescript
gtoken: md5(dataresult.user_id)
```

**Comment by Palmke** [comment]
@bropat yes. The webportal is working just fine. I have tried a custom Docker image calling this endpoint in the login function, but that also resulted in an absent `data` object.

**Comment by bropat** [comment]
But then the important information would not be included either, namely:

https://github.com/bropat/eufy-security-client/blob/eb5c2787f0760988023d12d4fd8731bd723d5821/src/http/api.ts#L293

**Comment by bropat** [comment]
@Palmke 
Can you confirm that there is no `cloud_token` in your `persistent.json`?

**Comment by Palmke** [comment]
Where would I find this file? In the root of the container? I can't find it either using `find | grep persistent` on `/` so I guess it's not there.

As for the lines of code you mentioned.
`dataresult` does not exist in the response. The code you're mentioning requires that data object to be present.
The web portal response is like this:
```
{
    "code": 0,
    "msg": "Succeed.",
    "data": {
        "user_id": "redacted",
        "email": "redacted",
        "nick_name": "redacted",
        "auth_token": "redacted",
        "token_expires_at": 1670616715,
        "avatar": "",
        "invitation_code": "redacted",
        "inviter_code": "",
        "verify_code_url": "",
        "mac_addr": "",
        "domain": "security-app-eu.eufylife.com",
        "ab_code": "redacted",
        "geo_key": "redacted",
        "privilege": 0,
        "phone": "",
        "phone_code": "",
        "server_secret_info": {
            "public_key": "0470ca96234263082120ab0646918187a9df3f0b70f1429e349b5d8a7bcde7cc4f5dd00fadbe1fd225ed0576fce145c785c8ed6b667485619bbcf57b2e5faa8405"
        },
        "params": null,
        "trust_list": []
    }
}
```

**Comment by Palmke** [comment]
OK I found it, but it doesn't contain a cloud token (it's `""`).

**Comment by bropat** [comment]
It could also be that Eufy starts intercepting our request and returns an "invalid" response.

**Comment by bropat** [comment]
Try changing some values here:

https://github.com/bropat/eufy-security-client/blob/eb5c2787f0760988023d12d4fd8731bd723d5821/src/http/api.ts#L54-L57
https://github.com/bropat/eufy-security-client/blob/eb5c2787f0760988023d12d4fd8731bd723d5821/src/http/api.ts#L66

**Comment by bropat** [comment]
Try adding:

```
User-Agent: okhttp/3.12.12
```

**Comment by bropat** [comment]
@Palmke 
Try adding the following to the hosts file and restart the process:

```
3.73.97.139 security-app-eu.eufylife.com
```

I use (at the moment) this server which gives me the correct answer.

**Comment by Palmke** [comment]
Changing headers does not work.

**Comment by Palmke** [comment]
Okay... something changed... I added the IP to the hosts file, ran it locally and it works!

**Comment by bropat** [comment]
I think some Eufy servers have problems...;)

**Comment by lolouk44** [comment]
tried to add this line to my docker-compose to no avail, in case it helps
```
    extra_hosts:
        - "security-app-eu.eufylife.com:3.73.97.139"
```

**Comment by Palmke** [comment]
Succeeded the captcha and got all my data again!

**Comment by lolouk44** [comment]
> Succeeded the captcha and got all my data again!

can you share how you did this?

**Comment by Palmke** [comment]
> > Succeeded the captcha and got all my data again!
> 
> can you share how you did this?

Check the comment above.
https://github.com/bropat/eufy-security-client/issues/242#issuecomment-1309368303

**Comment by lolouk44** [comment]
> > > Succeeded the captcha and got all my data again!
> > 
> > 
> > can you share how you did this?
> 
> Check the comment above. [#242 (comment)](https://github.com/bropat/eufy-security-client/issues/242#issuecomment-1309368303)

Brilliant, for others in the same situation, I just added an environment var in my docker-compose file
```

    environment:
        - TRUSTED_DEVICE_NAME=somerandomothername
```

**Comment by lolouk44** [comment]
Oh and I didn't see any captcha in the docker logs :)

**Comment by Morphy99** [comment]
> Brilliant, for others in the same situation, I just added an environment var in my docker-compose file

This isn't possible with HASS addon is it?

**Comment by Palmke** [comment]
That's because I've been tinkering all evening trying to figure this sh*t out xD

**Comment by rjing001** [comment]
So how do we fix it if we're running the HASS addon?!

**Comment by fuatakgun** [comment]
Any random value would be fine?

**Comment by dfournie** [comment]
@fuatakgun it seems to be the workaround. I've tried this in the evening yesterday, and the server was able to login again. It works with your Home Assistant integration. Maybe no related but I've observe another error after login:

`
 ERROR Invalid Property wifiSignalLevel error
`

**Comment by bropat** [comment]
@Palmke 

> Well no actually. I apparently tested locally with a different `config.json`. I found `extra_hosts` exists for Docker Compose so I tried that with the default config settings I used all the time. It failed.
> 
> I then changed the `trustedDeviceName` field to something other than the default, with default hosts and now I get a captcha request in Docker with the default eufy-security-ws image (1.0.2).
> 
> ## This is short term good news, long term bad news... It likely means that they're now actively countering this client. :-(
> **Omitting `data` from the initial login response in specific scenarios is a deliberate action!**

The `trustedDeviceName` setting sets the header property `PhoneModel` in the background. I intended this setting to be adjustable because if you use the 2FA, the value set here will then appear under Trusted Devices in the Eufy App. This makes it easier to identify where it comes from.
This setting can also be set in the `eufy-security-ws` project (it is also already provided in the Docker container).

Eufy actually expects the phone model here, so if we use values here that are not phone models, Eufy can intercept them. Random values should also work, but again can be detected as no phone model.

**Comment by bropat** [comment]
I think the problem here is simply that no one has set this value themselves and so the default value I have provided is used. This made it very easy for Eufy to intervene...

**Comment by Palmke** [comment]
The main and only concern here is that eufy started to intervene with this client.
This measure is easily circumvented, but what's next? How long until the next countermeasure, and most importantly, when will one be of a kind we cannot circumvent? 

I know what I'd do... sell all of my eufy products and get cameras with proper API's!

**Comment by naikn05** [comment]
How would you fix this issue on HASS ?

**Comment by lolouk44** [comment]
> How would you fix this issue on HASS ? 

@fuatakgun  would need to build a new version of the add-on I'm afraid

**Comment by fuatakgun** [comment]
i am working on this

**Comment by TaZZaT** [comment]
Thanks for all the clues...  I have been using the bropat/eufy-security-ws for quite a while and it's awesome.  I wanted share what I had to do to fix the issue in case it helps someone else. 

First, I don't use docker. I start the service as follows from a systctl script using ts-node:
e.g. ts-node /opt/eufy-security-ws/src/bin/server.ts --config config.json

Based on what I read above, I changed "trustedDeviceName?": "eufyclient",  to "trustedDeviceName?": "somerandomothername",  in the config.json file.   This didn't help.... continued to get the user_id error.

To fix the issue,I had to edit line 65 in /opt/eufy-security-ws/node_modules/eufy-security-client/build/eufysecurity.js and recompile.

                            if (this.config.trustedDeviceName === undefined) {
 -edit line 65 -> this.config.trustedDeviceName = "somerandomothername";

This seems to indicate that changing the variable trustedDeviceName in config.json doesn't work for some reason.

Thanks again.

**Comment by bropat** [comment]
In the next version, if you do not set the parameter `trustedDeviceName`, a random model of an existing Android phone will simply be set and kept at the first login. This way, not so many people should use "eufyclient" (default value).
If someone subsequently sets the above-mentioned parameter anyway, then this will of course take precedence.

**Attention:** If someone uses the 2FA and changes this parameter after a successful authentication, they will be asked to check again (new trust).

**Comment by buzurk26** [comment]
How do you edit this file when your using supervised HA and eufy addon all via hacs?

**Comment by fuatakgun** [comment]
Please check eufy_security repository for the issue and how to edit the parameters
