### ISSUE TITLE
[Bug]: Enabled property change via Eufy app doesn't emit a "property changed" event during the next poll_refresh

### ISSUE THREAD

**Issue by oNSXo** [bropat/eufy-security-client#243]
### Client version

2.2.3

### Node version

16.14.2

### Operating System type

Docker

### Operating system version

Docker img

### Describe the bug

If I disable or enable a camera via the Eufy Security app, I don't see any events emitted for that particular property if I attempt a `poll_refresh`.  Whenever I attempt a `poll_refresh`, I'm just seeing the `pictureUrl` property changed event come across.

I am using the latest version of your `eufy-security-ws` library to interact with the client, not sure if it's more appropriate to log the issue here or there.

### To reproduce

1. Open Eufy app and change Enabled status of Camera
2. Observe no events emitted related to the Enabled property
3. Trigger a `poll_refresh`
4. Still observe no events emitted related to the Enabled property

**Comment by bropat** [comment]
I need the log files where you reproduced the problem.
Furthermore, eufy handles the activation/deactivation differently depending on the device. Here you did not even provide this information.
So I can not help you.

**Comment by oNSXo** [comment]
I've attached  the debug log of eufy-security.  The camera is a eufyCam 2C Pro.

A wscat output looks like the following:
`
╰─ .\wscat -c ws://192.168.2.136:3000                                                                                                                                                       ─╯ Connected (press CTRL+C to quit)
< {"type":"version","driverVersion":"2.2.2","serverVersion":"1.0.2","minSchemaVersion":0,"maxSchemaVersion":13}
> {"messageId": "start_listening", "command": "start_listening"}
< {"type":"result","success":true,"messageId":"start_listening","result":{"state":{"driver":{"version":"2.2.2","connected":true,"pushConnected":true},"stations":[{"name":"My Station","model":"T8010","serialNumber":"T8010N0000000000","hardwareVersion":"P0","softwareVersion":"3.2.1.5h","lanIpAddress":"192.168.2.110","macAddress":"WifiMac","currentMode":1,"guardMode":1,"connected":true}],"devices":[{"name":"Porch","model":"T8142-Z","serialNumber":"T8142N0000000000","hardwareVersion":"T8142-Z","softwareVersion":"5.4.7","stationSerialNumber":"T8010N0000000000","enabled":false,"state":1,"battery":73,"batteryTemperature":18,"lastChargingDays":152,"lastChargingTotalEvents":6,"lastChargingRecordedEvents":3,"lastChargingFalseEvents":3,"batteryUsageLastWeek":0,"motionDetected":false,"personDetected":false,"personName":"","antitheftDetection":false,"motionDetection":false,"rtspStream":false,"watermark":1,"wifiRSSI":-23,"pictureUrl":"https://cdn-us.eufylife.com/thumb/2022/09/18/station/T8010N...","ledStatus":false}]}}}
> {"messageId": "poll_refresh", "command": "driver.poll_refresh"}
< {"type":"event","event":{"source":"device","event":"property changed","serialNumber":"T8142N0000000000","name":"pictureUrl","value":"https://cdn-us.eufylife.com/thumb/2022/09/18/station/T8010N...","timestamp":1668349018047}}
< {"type":"result","success":true,"messageId":"poll_refresh","result":{}}
< {"type":"event","event":{"source":"device","event":"property changed","serialNumber":"T8142N0000000000","name":"pictureUrl","value":"https://cdn-us.eufylife.com/thumb/2022/09/18/station/T8010N...","timestamp":1668349618716}}
< {"type":"event","event":{"source":"device","event":"property changed","serialNumber":"T8142N0000000000","name":"pictureUrl","value":"https://cdn-us.eufylife.com/thumb/2022/09/18/station/T8010N...","timestamp":1668350219389}}
< {"type":"event","event":{"source":"device","event":"property changed","serialNumber":"T8142N0000000000","name":"pictureUrl","value":"https://cdn-us.eufylife.com/thumb/2022/09/18/station/T8010N...","timestamp":1668350274582}}
< {"type":"event","event":{"source":"device","event":"property changed","serialNumber":"T8142N0000000000","name":"pictureUrl","value":"https://cdn-us.eufylife.com/thumb/2022/09/18/station/T8010N...","timestamp":1668350679949}}
>
`

[eufy-security-ws.txt](https://github.com/bropat/eufy-security-client/files/9997494/eufy-security-ws.txt)

**Comment by bropat** [comment]
You forgot to set the schema version as described [here](https://bropat.github.io/eufy-security-ws/#/api_introduction?id=schema-version).
If you do not set it, version `0` is assumed, although it is easily possible that there was still an error with this version.
