### ISSUE TITLE
[Bug]: Motion detected notification not correctly handled for eufycam 2 on HB3

### ISSUE THREAD

**Issue by Palmke** [bropat/eufy-security-client#244]
### Client version

2.2.3

### Node version

v16.18.0

### Operating System type

Docker

### Operating system version

Raspberry OS

### Describe the bug

It appears that notifications from a eufycam 2 (Pro) connected to a HB3 are not processed correctly.

### To reproduce

1. Attach Eufycam2 to HB3
2. Trigger motion
3. Observe no 'motion detected' event is emitted

### Screenshots & Logfiles

```
2022-11-13 14:42:12.079  DEBUG [src/eufy-security-client/src/eufysecurity.ts:920  EufySecurity.onPushMessage] Received push message 
{
  name: 'Cam 2',
  event_time: 1668350529310,
  type: 14,
  station_sn: 'T8030ZZZZZZZZZZZ',
  device_sn: 'T8140ZZZZZZZZZZZ',
  title: 'HomeBase3',
  content: 'Motion detected',
  push_time: 1668350532029,
  channel: 6,
  cipher: 0,
  event_session: '20221113_154209',
  event_type: 3101,
  file_path: '/zx/hdd_data0/Camera06/202211/20221113154204/20221113154204.zxvideo',
  pic_url: '',
  push_count: 1,
  notification_style: 1,
  storage_type: 1,
  msg_type: 18,
  person_name: undefined,
  person_id: undefined,
  tfcard_status: undefined,
  user_type: undefined,
  user_name: undefined,
  station_guard_mode: undefined,
  station_current_mode: undefined,
  alarm_delay: undefined,
  sound_alarm: undefined
}
```

**Comment by Palmke** [comment]
@bropat I see the source is correct, but still find it strange I'm not getting an event :p
Will try later with the latest version of the client and re-open if still applicable.

**Comment by Palmke** [comment]
Still applicable. eufycam 2 Pro notification is received in the client, but not handled.

**Comment by bropat** [comment]
@Palmke 

The `motionDetected` property of the unit, on the other hand, works?
Or neither?

**Comment by Palmke** [comment]
I am unfortunately not in possession of a eufycam 2 anymore. Therefore I cannot continue providing information regarding this issue.
