### ISSUE TITLE
Feature request: Trigger pre recorded response

### ISSUE THREAD

**Issue by swavans** [bropat/eufy-security-client#25]
Could you please add the option to trigger the voice reply. 
I can in example trigger the default sentence "Please leave it at the door" from the app and would like to be able to do this from code. Basically like the current quick response but with the custom recorded messages.

**Comment by bropat** [comment]
@swavans Are the current methods not enough?

1. get the VoiceIDs with the method `getVoices` of the class `HTTPApi`, the self-recorded ones should also be included.
2. pass the self-recorded ID to the `quickResponses` method of the `Station` class

**Comment by swavans** [comment]
Didn't know about the getVoices, thnx for that.
