### ISSUE TITLE
[Bug]: Sequence number reset (Maximum->0) can lead to unexpected behaviour on certain network conditions

### ISSUE THREAD

**Issue by thieren** [bropat/eufy-security-client#256]
### Client version

newest

### Node version

all

### Operating System type

Other

### Operating system version

all

### Describe the bug

The current implementation of queueing messages can fail if it encounters a sequence number overflow (aka reseting the sequence number back to zero).

Assume the following scenario: The sequence number has almost reached the maximum, say 65540, and due to network congestion the next package (65541) is not received.
The client goes on to receive the next few packages 65542, 65543, ... And stores them in the message queue. Until the maximum sequence number is reached that is. Packages 0, 1, 2, ... will not be stored since they are evaluated as 'already processed', due to:

https://github.com/bropat/eufy-security-client/blob/e9fb79b15007bf0f6072cf4d4eae684795cda89c/src/p2p/session.ts#L952-L958

When 65541 is eventually received the message queue is worked off, but now the packages after the reset of the sequence number will be missing.

This not only prevents the streaming from continuing. It also prevents all subsequent streams to fail, since the expected sequence numbers will not match up anymore.

Even further it seems that the automatic closing after the stream is prevented, since the timeout for this is in another conditional branch:

https://github.com/bropat/eufy-security-client/blob/e9fb79b15007bf0f6072cf4d4eae684795cda89c/src/p2p/session.ts#L959-L964

I've encountered at least two streams that did seem to go on, although the streaming was stopped from client side. It even seemed to drain the battery of my doorbell (which has a batter AND is wired with bell wire).

PR #255 should fix this.

### To reproduce

Hard to reproduce, but should be understandable from looking at the code.

**Comment by bropat** [comment]
Good Work! You explained it very well.

**Comment by bropat** [comment]
Pull request #255 merged.
