### ISSUE TITLE
[Bug]: downloaded video data is not correct for recent-bought cam

### ISSUE THREAD

**Issue by tyware** [bropat/eufy-security-client#257]
### Client version

2.2.3

### Node version

1811.0

### Operating System type

Linux

### Operating system version

Raspberry Pi 4B

### Describe the bug

The downloaded video data from recent-bought cam cannot be recognized by ffmpeg. It works well for older eufy cam.

I had found the root cause. The signCode should be UInt8 rather than Int8 in function parseDataMessage of session.js (readUInt8 should be used). My new cam has signCode 203. It was read as -53, that is wrong.

### To reproduce

NA

**Comment by bropat** [comment]
Fixed in version `2.3.0`.
