### ISSUE TITLE
[Feature request]: Add support for T8790 SmartDrop

### ISSUE THREAD

**Issue by tgryphon** [bropat/eufy-security-client#261]
### Describe the solution you'd like

Looks like I might be the only one trying to use a SmartDrop with HA... getting invalid DEVICE_TYPE.
Here's the error log from the integration for this device:

`Exception - process_messages: 90 is not a valid DEVICE_TYPE - traceback: Traceback (most recent call last): File "/config/custom_components/eufy_security/websocket.py", line 57, in process_messages await self.on_message(msg) File "/config/custom_components/eufy_security/websocket.py", line 68, in on_message await self.message_callback(message) File "/config/custom_components/eufy_security/coordinator.py", line 313, in on_message await self.process_get_device_properties_response( File "/config/custom_components/eufy_security/coordinator.py", line 258, in process_get_device_properties_response device.set_properties(properties) File "/config/custom_components/eufy_security/const.py", line 452, in set_properties type = DEVICE_TYPE(self.type_raw) File "/usr/local/lib/python3.10/enum.py", line 385, in __call__ return cls.__new__(cls, value) File "/usr/local/lib/python3.10/enum.py", line 710, in __new__ raise ve_exc ValueError: 90 is not a valid DEVICE_TYPE - message: WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":"result","success":true,"messageId":"get_device_properties","result":{"serialNumber":"T8790N[redacted]","properties":{"name":"SmartDrop","model":"T8790","serialNumber":"T8790N[redacted]","type":90,"hardwareVersion":"P1","softwareVersion":"1.3.3.1","stationSerialNumber":"T8010P[redacted]"}}}', extra='')`

**Comment by julianrinaldi** [comment]
I also use the SmartDrop, so an integration with Home Assistant would be great. Unfortunately most of my delivery people don't use it, haha.

**Comment by Freekers** [comment]
+1

**Comment by wilbsww** [comment]
Came to request this, glad I'm not alone!

**Comment by iotemylabs** [comment]
Also came to request the SmartDrop as well, hopefully this comes!

**Comment by hsvjez** [comment]
+1

**Comment by bropat** [comment]
I need someone to share the device with admin rights.

If someone wants to share it:

* patrick.broetto+eu1@gmail.com
* patrick.broetto+us1@gmail.com

**Comment by thomasdg** [comment]
Would also love to get it into Home Assistant as the numpad of my Dropbox slowly died. Thinking on building (or linking) a custom numpad and connecting it to the smartdrops "Open" feature using home assistant... If you need acces to mine as well to developer/debug, just let me know!

**Comment by thomasdg** [comment]
Thanks a lot for adding the smartdrop! Just one question remains: is it possible to trigger the "open" button as in the app to open the dropbox in an automation?

**Comment by bropat** [comment]
> is it possible to trigger the "open" button as in the app to open the dropbox in an automation?

yes

**Comment by thomasdg** [comment]
Forgive me my ignorance, but what service do I have to call in home assistant to get the cover to open? Looked around at the offered services in the eufy devices but couldn't see anything relevant... Thanks!

**Comment by bropat** [comment]
This project is not a Home Assistant integration.
It must first be implemented [here](https://github.com/fuatakgun/eufy_security).
