### ISSUE TITLE
[Question]: Send audio file via talkback to Eufy 2C camera?

### ISSUE THREAD

**Issue by dffitch** [bropat/eufy-security-client#263]
### Ask your question

Successfully using eufy-security-ws from node red, I have been looking at the "Send talkback audio data" command.
I have recently moved to a Greek speaking part of the world and am still learning the language.  I wondered  if there is any way to send a pre recorded message to the camera when a person detected occurs.  Thanks in advance

**Comment by thieren** [comment]
You'll have to encode the prerecorded audio in the right format as described [here](https://github.com/bropat/eufy-security-client/issues/153). You could use `ffmpeg` to use something like this:

`ffmpeg -i input-file.mp3 -acodec libfdk_aac -b:a 20k -ar 16k -ac 1 -f adts output.aac`

The output.aac is then what you send through this command. Unfortunately I don't know if you can send the whole file at once, or if you'll have to chop it into the individual ADTS frames.

Our [homebridge-eufy-plugin](https://github.com/homebridge-eufy-security/plugin) does it by starting a ffmpeg process and piping the output directly to the client. This way every single ADTS frame is being send with one command.

**Comment by dffitch** [comment]
@thieren  thanks for the information.  Tried to recompile ffmpeg on my host machine with libfdk_aac without much success. I ran up your homebridge plugin in docker and was able to do the conversion in the console.   Is there any specific place I can test sending my file to my cameras from your homebridge plugin?  I have tried sending the .aac file as a buffer in node red and receive a success message but there is no audio coming from the camera.  You mentioned chopping it into the individual ADTS frames which I still have yet to research and try out - any pointers gratefully received.  Thanks for the help

**Comment by thieren** [comment]
The plugin itself cannot send prerecorded files. The talkback feature processes input from the HomeKit source in realtime and encodes this into the ADTS format needed by the camera.
We use the data coming out of the ffmpeg process which is already (conveniently) chopped into the individual adts frames.

So you could either write your own ffmpeg process pipe which sends the frames accordingly, or you'll have to write something that chops the already encoded file into the individual pieces.

Each adts frame begins with an adts header. You could split the file by that. You can read more about this here: https://wiki.multimedia.cx/index.php/ADTS

**Comment by dffitch** [comment]
Spent quite a while today trying to work out how to split the file using your second suggestion.  Trying to do this in node red is probably not the best approach.  It's starting to get a little beyond my scope tbh, but thanks for the advice.
