### ISSUE TITLE
[Question]: Anyone else having issues with Eufy's API?

### ISSUE THREAD

**Issue by ema-dev** [bropat/eufy-security-client#268]
### Ask your question

Eufy has been in the news lately over privacy concerns. It appears they've changed the response to their "start_stream" request. It appears they're encrypting the data ("data": "url": "rtmp://...." is now "data": "encrypted string") that is returned. I've been using a combination of the API their website uses and the eufy-security-client/ws container for my personal use cases. When I attempt to recreate some of their website API calls I am sometimes given a 403 forbidden response. I've found that changing the user-agent sometimes fixes this, but that doesn't appear to be the case with the "start_stream" request, and now they've changed the response structure, it doesn't matter.

For my use case, I have my AgentDVR (surveillance software) make a call to my API that then makes a call to Eufy's API and calls "start_stream", grabs the URL from the response and sets the camera source URL in AgentDVR. Is there a way to get the public facing stream URL from the eufy-security-client/ws container after I send the "device.start_livestream" command?

**Comment by martijnpoppen** [comment]
Yes see: https://github.com/bropat/eufy-security-client/issues/259#issuecomment-1343319897

**Comment by ema-dev** [comment]
@wystewart @martijnpoppen 
Thank you for the info. I've updated my integration to use the "livestream video data" event data, ffmpeg, and rtsp-simple-server instead of the web API.
