### ISSUE TITLE
[Question]: How do I access the p2p stream of a eufy floodlight 2k without a base station

### ISSUE THREAD

**Issue by freemyman122** [bropat/eufy-security-client#269]
### Ask your question

Just read the subject at this point.

**Comment by ema-dev** [comment]
@freemyman122 
You can set up a https://github.com/bropat/eufy-security-ws docker container connected your Eufy account, connect to the WebSocket server, send the "set_api_schema" command, then "start_listening" command", and lastly the "device.start_livestream" command for the serial number of your floodlight. Afterwards, the WebSocket server will start broadcasting "livestream video data" and "livestream audio data" events for you to read and process. Here's some documentation https://bropat.github.io/eufy-security-ws/#/tryitout.

Without knowing your current setup and skillset I can't give you specific instructions/tips.

**Comment by bropat** [comment]
Meanwhile, the client in `eufy-security-ws` also supports individual command line commands. See e.g. [here](https://github.com/bropat/eufy-security-ws/issues/29) or [here](https://bropat.github.io/eufy-security-ws/#/tryitout?id=start-client).
