### ISSUE TITLE
[Question]: simple example

### ISSUE THREAD

**Issue by kinatron** [bropat/eufy-security-client#281]
### Ask your question

Will you provide a simple example of creating a client to connect to a camera?

**Comment by bropat** [comment]
As an example, you can look at the following projects: [ioBroker.eufy-security](https://github.com/bropat/ioBroker.eufy-security), [eufy-security-ws](https://github.com/bropat/eufy-security-ws), [eufy_security](https://github.com/fuatakgun/eufy_security)

**Comment by SiobhanBaynes** [comment]
None of which can readily be described as "a simple example" :)
This looks like a great project which is just missing some simple Getting Started type docs for newcomers.

Thanks for all the work though!
