### ISSUE TITLE
[Bug]: Getting bad decrypt when decrypting v2 response

### ISSUE THREAD

**Issue by hao1300** [bropat/eufy-security-client#283]
### Client version

2.3.0 (develop branch)

### Node version

16.18.1

### Operating System type

Mac OS X

### Operating system version

Ventura 13.0.1

### Describe the bug

I started getting 403 errors from the v1/passport/profile response, and after looking around a bit, I found https://github.com/bropat/eufy-security-client/pull/282. When trying out that patch, I got 
error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt at this.decryptAPIData(result.data). I also got the same error when trying to decrypt the response for v2/house/device_list and v2/house/station_list.

### To reproduce

1. Sync to https://github.com/bropat/eufy-security-client/pull/282
2, Initialize eufy-security-client, then call connect()

### Screenshots & Logfiles

Error: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt at Decipheriv.final (node:internal/crypto/cipher:193:29) at decryptAPIData (/Users/hao/modheader-workspace/scripts/eufy-security-client/build/http/utils.js:169:16) at HTTPApi.decryptAPIData (/Users/hao/modheader-workspace/scripts/eufy-security-client/build/http/api.js:1010:51) at HTTPApi.getPassportProfile (/Users/hao/modheader-workspace/scripts/eufy-security-client/build/http/api.js:1192:46) at processTicksAndRejections (node:internal/process/task_queues:96:5) at async HTTPApi.login (/Users/hao/modheader-workspace/scripts/eufy-security-client/build/http/api.js:346:33) at async EufySecurity.connect (/Users/hao/modheader-workspace/scripts/eufy-security-client/build/eufysecurity.js:651:9) at async process (file:///Users/hao/modheader-workspace/scripts/timed-token/timed-token/index.js:155:3) {library: "digital envelope routines", function: "EVP_DecryptFinal_ex", reason: "bad decrypt", code: "ERR_OSSL_EVP_BAD_DECRYPT", stack: "Error: error:06065064:digital envelope routines:EV…e/scripts/timed-token/timed-token/index.js:155:3)", ...}

**Comment by nackerr** [comment]
@bropat seems to be an urgent, widespread issue.

**Comment by martijnpoppen** [comment]
Workaround: Remove your persistent.json and try again :)

**Comment by nackerr** [comment]
Does not work. Tried numerous times.

**Comment by nackerr** [comment]
If it does succeed in logging in, it will fail to fetch device list. Upon restarting, you won't be able to login again.

**Comment by martijnpoppen** [comment]
oh hmm, that did it for me,
I saw some comment from bropat in the code that the decryption resets the authentication...

Guess we have to patiently wait ;)

**Comment by PhilippEngler** [comment]
I think I got it. @martijnpoppen you decrypt the complete response, instead of response.data.data.

take a look at https://github.com/PhilippEngler/eufy-security-client/blob/4d529cce2ab4bc70720d5196fc3fd801d1001411/src/http/api.ts#L1180

**Comment by martijnpoppen** [comment]
@PhilippEngler yes same as this: https://github.com/PhilippEngler/eufy-security-client/blob/4d529cce2ab4bc70720d5196fc3fd801d1001411/src/http/api.ts#L482

**Comment by hao1300** [comment]
Thank you so much. It works now!

**Comment by PhilippEngler** [comment]
Maybe some remaining hiccups on eufy side? It is strange, I have received also the decrypt error messages, so I have reworked the function.

From the v1-api ones, I have tested until now, the house/detail call now returns also a 403 error. It seems, that we will need to have more to change to keep it running...

**Comment by nackerr** [comment]
I think this should stay open until the issue is fixed?

Because referencing [https://github.com/homebridge-eufy-security/plugin/issues/250](this) and from personal experience, it is most definitely not fixed.

**Comment by outrageouskiwi** [comment]
@nackerr Agreed—not sure why this issue is closed, I am still having persistent issues.

**Comment by nackerr** [comment]
@hao1300 consider reopening as it still exists.

**Comment by hao1300** [comment]
Reopened the bug
