### ISSUE TITLE
[Bug]: request to v1/passport/profile start to return 403 error

### ISSUE THREAD

**Issue by Yuliya-bezz** [bropat/eufy-security-client#287]
### Client version

2.3.0

### Node version

16.13.0

### Operating System type

Windows

### Operating system version

11

### Describe the bug

Login request stopped working and now, during connection to the API it returns `403` error.

Request that returns error: https://security-app-eu.eufylife.com/v1/passport/profile. Also during the investigation I found that API used on mysecurity.eufylife.com also was change to new v2 version, possibly this is a cause of the issue.

### To reproduce

To reproduce the issue simply initialize eufy instance and try to connect with login and password.

### Screenshots & Logfiles

Loaded API_BASE: https://security-app-eu.eufylife.com
[EufySecurity._initializeInternals] Load previous login_hash: ["****"]
[EufySecurity._initializeInternals] Load previous token: [{"token":"****","tokenExpiration":****}]
[HTTPApi.login] Login and get an access token [{"token":"****","tokenExpiration":"****"}]
[HTTPApi.request] Request: [{"method":"get","endpoint":"v1/passport/profile","token":"****"}]
EufyError - Code: undefined Message: undefined (HTTP Code: 403) - requestUrl: https://security-app-eu.eufylife.com/v1/passport/profile
Generic Error: [{"name":"EufyError","code":"ERR_NON_2XX_3XX_RESPONSE","timings":{"start":****,"socket":****,"lookup":****,"connect":****,"secureConnect":****,"upload":****,"response":****,"end":****,"phases":{"wait":0,"dns":51,"tcp":16,"tls":39,"request":0,"firstByte":19,"download":1,"total":126}}}]
Connection error: ApiInvalidResponseError: Invalid passport profile response
    at HTTPApi.login (***/node_modules/eufy-security-client/build/http/api.js:340:51)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async EufySecurity.connect (***/node_modules/eufy-security-client/build/eufysecurity.js:643:9)
    at async EufyManager.connect (/***/src/services/eufy-manager.js:53:9)
    at async ***/src/controllers/auth.js:9:27

**Comment by wexstorm** [comment]
I have the same issue. Tried the development Branch. The login works, but all following requests to API v1 fail again.

**Comment by martijnpoppen** [comment]
See https://github.com/bropat/eufy-security-client/pull/282
