### ISSUE TITLE
[Bug]: Fehler im Merge #286 im Develop?

### ISSUE THREAD

**Issue by Baenker** [bropat/eufy-security-client#288]
### Client version

develop

### Node version

egal

### Operating System type

Linux

### Operating system version

egaal

### Describe the bug

Im Merge #286 wurde in der Api.ts z. B. Zeile 899 gelöscht und Zeile 900 hinzugefügt. Dort wurde die Variable von fifthyYearsinMiiseconds zu fiftteenyearsinMilliseconds geändert. Was auch besser zu der Rechnung passt. Aber die Zeile 901 wird weiternhin mit der alten Variable fifthy gerechnet. Das gleiche wurde an div. Stellen ebenso gemacht.

Ist dass wirklich richtig oder hätte die Zeile 901 dann nicht auch verändert werden müssen?

Betrifft den Developbranch.

### To reproduce

Merge prüfen

**Comment by bropat** [comment]
Nein ist nicht richtig und wurde im neuen Kode bereits behoben (noch nicht veröffentlicht).
Eine neue öffentliche Version ist nur einige Minuten entfernt ;)
