### ISSUE TITLE
Preview images no longer open

### ISSUE THREAD

**Issue by Sprocket02** [bropat/eufy-security-client#289]
### Ask your question

The preview jpgs downloaded from the following address `..."name":"pictureUrl","value":"https://security-app-eu.eufylife.com/v1/s/g/TXXXXQP5f"...` can no longer be opened. Unknown file format. It worked a few days ago. In the meantime I updated the cameras (S300) to version 3.2.1.1 and the station (S380) to version 3.1.4.1.

Can it be that the files are now encrypted? Or what else am I doing wrong?

**Comment by martijnpoppen** [comment]
Take a look here: https://github.com/bropat/eufy-security-client/issues/273
