### ISSUE TITLE
[Feature request]: Support "eufy Security WiFi Smart Lock" T8502

### ISSUE THREAD

**Issue by jem** [bropat/eufy-security-client#291]
### Describe the solution you'd like

T8502 appears to be similar to the Eufy Smart Lock Solo (and request #226), but has a different model number of T8502. It is marketed as "eufy Security WiFi Smart Lock". It has a keypad but no touch sensor, and it has WiFi built in, with no bridge.

It would be great to get support for this in your great library (which I use via Home Assistant). I have three other locks that are working well via the same path.

Happy to provide access if desired, just let me know when. Or can provide debug logs etc.

It is currently picked up by the library, and supports some functionality ('Alarm Volume' and 'Prompt Volume') but does not support locking or showing lock status.

**Comment by jem** [comment]
I have shared one of these locks, with admin access, with [patrick.broetto+us1@gmail.com](mailto:patrick.broetto+us1@gmail.com).

**Comment by vivekvkk** [comment]
@bropat I am having the same issue as well. Is there any plan to support this in the near future? I can provide device access if needed.

**Comment by sjbarkey** [comment]
I am having the same issue as well and would like to see this device supported by HA.

**Comment by coddipm** [comment]
I'd also like to see the device supported if possible. Appreciate your help.

**Comment by IlPicasso** [comment]
In search for this ! How can I Help ?

**Comment by vivakkal** [comment]
@bropat Can you please shed some light on this? Is there any tentative plan to support T8502? I am more than happy to help you in any way possible.

**Comment by Mcgillicutty1879** [comment]
Hello, hoping to get support for the T8502 as well. I have 2 devices running. Let me know if access is still needed or any information. Thank you for all your hard work Bropat!

**Comment by IlPicasso** [comment]
> I need someone to share the device with admin rights.
> 
> If someone wants to share it:
> 
> * [patrick.broetto+eu1@gmail.com](mailto:patrick.broetto+eu1@gmail.com)
> * [patrick.broetto+us1@gmail.com](mailto:patrick.broetto+us1@gmail.com)

Request Sent!

**Comment by timleeds15** [comment]
Any update on this?

**Comment by bropat** [comment]
@timleeds15 
Unfortunately not, because I didn't have time before and now I don't have access to a device, so I can't implement it.

If someone grants me access, I can give it a try.

**Comment by timleeds15** [comment]
How would I go about giving you access? I plan on buying one of these locks soon due to the ridiculously low price point for a smart lock and would love to get it in home assistant

**Comment by bropat** [comment]
How would I go about giving you access? I plan on buying one of these locks soon due to the ridiculously low price point for a smart lock and would love to get it in home assistant

**Comment by bropat** [comment]
You can share the device with other accounts via the Eufy app (my accounts are listed above).

**Comment by IlPicasso** [comment]
> You can share the device with other accounts via the Eufy app (my accounts are listed [above](https://github.com/bropat/eufy-security-client/issues/291#issuecomment-1837421375)).

Hello! I thought you already had access to mine 

> > I need someone to share the device with admin rights.
> > If someone wants to share it:
> > 
> > * [patrick.broetto+eu1@gmail.com](mailto:patrick.broetto+eu1@gmail.com)
> > * [patrick.broetto+us1@gmail.com](mailto:patrick.broetto+us1@gmail.com)
> 
> Request Sent!



I will try resending the device

**Comment by timleeds15** [comment]
Ah great! And I will donate to @bropat via KoFi to help support his efforts on this

**Comment by IlPicasso** [comment]
![Screenshot_2024-01-30-18-23-01-42_ff785028b59b747d09873fc0674450df](https://github.com/bropat/eufy-security-client/assets/5110242/db2f9300-a684-437b-926f-860b67c3ec1e)

@bropat Is that good?

**Comment by timleeds15** [comment]
Will this be back in the 3.0.0 milestone? :)

**Comment by bropat** [comment]
@IlPicasso

I hereby confirm that I have access to the device.

@timleeds15 

It depends on whether this device communicates in a similar way to those already implemented.

**Comment by ujwalkoirala0** [comment]
Any updates on when the new version will be released?

**Comment by sjbarkey** [comment]
Happy to see the lock is now supported!  Thank you @bropat!

**Comment by adamjonfuller** [comment]
It appears that this may not be working correctly as the lock is being assigned an entity category of "Diagnostic". I believe the intended category would be "Control".

**Comment by HartR** [comment]
I am not able to lock/unlock my T8502 lock, but I am able to see all diagnostic info on it

**Comment by HartR** [comment]
> It appears that this may not be working correctly as the lock is being assigned an entity category of "Diagnostic". I believe the intended category would be "Control".

Did you ever get this working?
