### ISSUE TITLE
[Feature request]: adding lock t8503

### ISSUE THREAD

**Issue by Zachary8893** [bropat/eufy-security-client#294]
### Describe the solution you'd like

If you have time, could you look into adding T8503. It has built in WiFi. Super easy lock that just replaces the front of your currently installed lock. I’m not sure of any information you need, but I’m happy to help in any way I can.

**Comment by Zachary8893** [comment]
Cancel this request, it already integrates. For anyone else seeing this you may just have to allow permission for the user, if set up with accounts as suggested. (home assistant account) ie share device with user.

**Comment by richrosa** [comment]
@Zachary8893 is there any way to turn on/off the lock? I don't see an entity for that lock.

**Comment by Zachary8893** [comment]
@richrosa all I can really tell you is I have a main eufy account and then added another user to use for home assistant. I Then had to go in to the eufy app and go to settings for the lock, then down to share device and added it to the home assistant account. After that it showed up in HA and after some time, works. The battery sensor is there and some stuff with the keypad that came with it.

**Comment by bropat** [comment]
#208
