### ISSUE TITLE
[Question]: Interface to delete a video recording?

### ISSUE THREAD

**Issue by dhwalker** [bropat/eufy-security-client#295]
### Ask your question

Is there an interface to delete a video recording? I'd like to implement a small application that I'd run nightly to prune old recordings to prevent local storage from running out.

**Comment by fuatakgun** [comment]
Local storage clears out itself on homebase if it runs out of space, right?

```
What is the HomeBase storage type?
The HomeBase 2 comes with a non-removable 16GB EMMC local storage. System files will occupy a very small amount of storage space.

It can store 2 months’ worth of videos for a system with 1 camera, or 1 month for a system with 2 cameras (30 motion detections a day and 60 seconds recording each time). The old video clips will be overwritten by a loop when the space is full.

```

**Comment by dhwalker** [comment]
Ah, sorry, I wasn't specific. I have two SoloCam S40 cameras, each with 8GB local storage; I don't have a HomeBase. Thanks for pointing that out, though; you pointed me in the right direction. After a little research, I found that the SoloCam also overwrites old videos at https://support.eufy.com/s/article/eufy-SoloCam-S40-FAQ

  Does eufy SoloCam S40 still record when its internal memory card is full?

  Yes. eufy SoloCam S40 will continue to function normally and it will overwrite the oldest video recordings when it 
  records new videos.

Thanks again!
