### ISSUE TITLE
[Bug]: Alarm Status unknown after HA restart

### ISSUE THREAD

**Issue by RienduPre** [bropat/eufy-security-client#296]
### Client version

6.2.0

### Node version

??

### Operating System type

Linux

### Operating system version

??

### Describe the bug

After a restart of HA the alarm state is lost/unknown. I manually have to change the state to update the Alarm state

### To reproduce

1. Set the Alarm to "Home"
2. Restart HA
3. Check Alarm (entity: alarm_control_panel.eufy_homebase)

**Comment by bropat** [comment]
Wrong repo
