### ISSUE TITLE
[Bug]: getVideoEvents and getAllVideoEvents returns no records

### ISSUE THREAD

**Issue by alinhayati** [bropat/eufy-security-client#298]
### Client version

2.4.0

### Node version

14.16

### Operating System type

Linux

### Operating system version

Debian

### Describe the bug

The following methods for getting the video events in `api.js` return empty records:
`getVideoEvents(startTime: Date, endTime: Date, filter?: EventFilterType, maxResults?: number): Promise<Array<EventRecordResponse>>;`
`getAllVideoEvents(filter?: EventFilterType, maxResults?: number): Promise<Array<EventRecordResponse>>;`

I have rooted this down to this part (lines 866-880 of `api.js`):
`                if (response.status == 200) {
                    const result = response.data;
                    if (result.code == 0) {
                        const dataresult = this.decryptAPIData(result.data);
                        if (dataresult) {
                            dataresult.forEach(record => {
                                this.log.debug(`${functionName} - Record:`, record);
                                records.push(record);
                            });
                        }
                    }
                    else {
                        this.log.error(`${functionName} - Response code not ok`, { code: result.code, msg: result.msg });
                    }
                }`
where the `dataresult` returns `null`.

This is the response of the `v2/event/app/get_all_video_record` api.

It used to work properly until lately.  Deleting the `persistent.json` did not help.

### To reproduce

2. Click on '...'

**Comment by PhilippEngler** [comment]
The return values of the `getVideoEvents`, `getAlarmEvents` and `getHistoryEvents`-functions in my case are not updated since mid of January 2023 and returned until mid of February the "old" events. I think, they will not used anymore and the events will be queried over the new encrypted p2p method like it was done for the HomeBase 3 from the beginning.

**Comment by bropat** [comment]
It's like @PhilippEngler writes.
Eufy now stores the events locally and no longer in the cloud, so these functions are now obsolete.
