### ISSUE TITLE
Request: generate an event if live stream was forcibly closed

### ISSUE THREAD

**Issue by fuatakgun** [bropat/eufy-security-client#30]
I have learnt that there is a time limit to go with live stream and it is around 3 minutes.

Can you generate an event to notify listeners on this?

More information: https://github.com/fuatakgun/eufy_security/issues/10#issuecomment-886831030

I am sure you are much more informed than me on this topic.

**Comment by bropat** [comment]
@fuatakgun I have already looked in the code and confirm that this is a bug. I will probably fix it this weekend.

**Comment by bropat** [comment]
Fixed in last release (1.0.0)
