### ISSUE TITLE
[Question]: How do I even launch this?

### ISSUE THREAD

**Issue by deemeetree** [bropat/eufy-security-client#300]
### Ask your question

Your documentation and your Readme does not provide any information on how to launch it or how to install it. Is this intentional?

**Comment by ABrolund** [comment]
Is there somewhere Something like a python sample to use your library, would like to write a small MQTT Wrapper to use it in my Home automation.
And a big thx for work !

**Comment by fuatakgun** [comment]
Might be a good starting point: https://github.com/fuatakgun/eufy_security
