### ISSUE TITLE
[Feature request]: Battery doorbell that is wired 24/7 RTSP support

### ISSUE THREAD

**Issue by DavithkbY** [bropat/eufy-security-client#303]
### Describe the solution you'd like

Hello, 

Currently I am trying to use the eufy security client to enable 24/7 RTSP streaming on my battery doorbell but that I have wired and is receiving 24/7 power. The RTSP stream stops after I think 3 minutes and then goes offline for a while. 
Is it possible to make the stream be available 24/7? 
As I am trying to record the stream through Scrypted(homekit platform) using this RTSP url. 

Thanks in advance!

**Comment by liudger** [comment]
This is by hardware/firmware that is only can stream for 3 min. That is what I remembered from a discussion a while back

**Comment by liudger** [comment]
I was also thinking about integrating this client into scrypted. 

There is a command to start/stop the stream. It could be triggered from scrypted to resume the stream when the stream stops. It will cause a small hiccup I guess. First start is to make this plugin available in scrypted 😄

**Comment by bropat** [comment]
It is like already written by @liudger
