### ISSUE TITLE
[Question]: Can I use this library to activate RTSP stream on Solo cameras?

### ISSUE THREAD

**Issue by deemeetree** [bropat/eufy-security-client#308]
### Ask your question

Eufy solo battery-powered cameras don't have RTSP activated due to battery life concerns. Can I use this library to activate RTSP streams on them bypassing the default setting? I see in your readme that this can be done? Thanks!

**Comment by andiweli** [comment]
Any update if this can be done? I am interested too.

**Comment by Daneish** [comment]
If it helps at all, I have seen that it is possible to enable RTSP on Battery Doorbells by modifying the Android APK - [instructions here.](https://www.reddit.com/r/EufyCam/comments/nal27f/enabling_rtsp_on_battery_doorbell/)

It also looks like the Eufy HomeBridge plugin (which is based on this library) has enabled an [Experimental Feature](https://github.com/homebridge-eufy-security/plugin/wiki/RC---Beta-Version#experimental-mode) to “Enable RTSP streaming on devices, which are not natively able to utilise RTSP.”

Perhaps a similar feature could work for the Solo Battery cameras. Bropat would you be interested in adding this option to your library?

If this is unrelated to the Solos, I’m happy to raise a separate issue to not hijack this post further.

Thank you for all of your great work providing extra functionality to our Eufy devices!

**Comment by bropat** [comment]
With some changes in the library, this would be possible.
But I don't know if it would work then, because it still has to be supported by the firmware of the device.

**Comment by Daneish** [comment]
Sorry for the late response. I would be happy to test it on my 2K Battery Doorbell (T8210) and Homebase 2 (T8010) if you were interested in adding the RTSP option. It has potential to greatly simplify my video pipeline into Scrypted and HomeKit Secure Video.
