### ISSUE TITLE
[Question]: unable to start camera stream

### ISSUE THREAD

**Issue by vajonam** [bropat/eufy-security-client#309]
### Ask your question

I have enabled the camera stream with camera.turn_on, however when I stream the image it shows and empty grey window, with some encoding artifacts, sometimes it becomes green. 

![image](https://user-images.githubusercontent.com/152501/221964950-046ad952-aa74-40f2-aab0-9ca9d14f3ec8.png)

However I can see the video queue jumping around, not sure what I am missing. 

![image](https://user-images.githubusercontent.com/152501/221965386-c5d0cf03-afdd-4508-882e-e0643f537bae.png)

**Comment by vajonam** [comment]
![image](https://user-images.githubusercontent.com/152501/221968995-f4c03bf0-66d8-4a52-b029-a8dbb95bf3ac.png)

**Comment by bropat** [comment]
Wrong repo
