### ISSUE TITLE
Request: RTSP Stream Support for T8111

### ISSUE THREAD

**Issue by dmnsgit** [bropat/eufy-security-client#31]
Sorry to be a pain with these older cameras but may I ask for some help with RTSP stream support? 

• station.ts:815 setRTSPStream
    node_modules/eufy-security-client/src/http/station.ts:815:19

• message_handler.ts:35 handle
    src/lib/device/message_handler.ts:35:31

• server.ts:46 device
    src/lib/server.ts:46:34

• server.ts:98 receiveMessage
    src/lib/server.ts:98:58

• server.ts:57 <anonymous>
    src/lib/server.ts:57:53

• events.js:376 emit
    events.js:376:20

• websocket.js:834 receiverOnMessage
    node_modules/ws/lib/websocket.js:834:20

• events.js:376 emit
    events.js:376:20

• receiver.js:437 dataMessage
    node_modules/ws/lib/receiver.js:437:14

• receiver.js:367 getData
    node_modules/ws/lib/receiver.js:367:17

2021-07-28 17:14:06.861  ERROR Message error
 NotSupportedFeatureError  This functionality is not implemented or supported by T8111H1219031E29

**Comment by bropat** [comment]
@dmnsgit 
This weekend I will return from vacation, if you can share the camera briefly then I can unlock the RTSP support (if supported) and also the other features. If ok I will get back to you this weekend.

**Comment by fuatakgun** [comment]
enjoy your vacation :)

**Comment by dmnsgit** [comment]
> @dmnsgit
> This weekend I will return from vacation, if you can share the camera briefly then I can unlock the RTSP support (if supported) and also the other features. If ok I will get back to you this weekend.

Of course, happy to. Take your time and enjoy your vacation. I'm GMT - 7 when you return so forgive me if it takes me a bit to reply.

**Comment by bropat** [comment]
ok, no problem. I'm GMT+2 ;)

**Comment by bropat** [comment]
@dmnsgit 

Please share me a camera with admin rights to this account: patrick.broetto+us1@gmail.com

**Comment by bropat** [comment]
I will run some tests to implement and activate the other functionalities.

**Comment by dmnsgit** [comment]
@bropat 
 
I'm just going to leave my cameras shared until you tell me otherwise. Take all the time you need.

**Comment by bropat** [comment]
@dmnsgit 

You can revoke the sharing. I have implemented everything in the driver, will be released in the next release.
I have to finish a few other things before I publish, so please be patient.

**Comment by bropat** [comment]
@dmnsgit Released. Sorry missed to update here.

**Comment by dmnsgit** [comment]
@bropat Thank you SO MUCH! Removing sharing now and sending you some coffees.
