### ISSUE TITLE
[Feature request]: Disable Maximum Stream Timeout

### ISSUE THREAD

**Issue by leedsalex** [bropat/eufy-security-client#313]
### Describe the solution you'd like

I would like to add the ability to disable the maximum stream time out. I realize that the functionality to set the `cameraMaxLivestreamSeconds` already exists, but the system I am implementing this client into already has functionality to handle stream timeouts built-in and it is conflicting with this functionality. Could we make this property an optional type and set it to `undefined`, or handle the `-1` case, to disable it?

I am happy to make a PR for this feature, please let me know if this would be acceptable.

**Comment by bropat** [comment]
Implemented in version `2.4.4`.
Setting `cameraMaxLivestreamSeconds ` to `0` disables this feature.
