### ISSUE TITLE
[Bug]: No devices found, need help

### ISSUE THREAD

**Issue by alikamranch** [bropat/eufy-security-client#316]
Hi,

I'm trying to use this package in a node js environment within an AWS LAMBDA function, the function code looks something like this:

`
const { EufySecurity } = require("eufy-security-client");

/**
 * @param {Object} event - API Gateway Lambda Proxy Input Format
 * @param {Object} context
 * @param {Object} event - API Gateway Lambda Proxy Output Format
 */

exports.getEufyConnection = async (event, context) => {
  try {
    let response;
    //Define eufy config
    const config = {
      username: "******************",
      password: "********",
      country: "US",
      language: "en",
      p2pConnectionSetup: 0,
      pollingIntervalMinutes: 10,
      eventDurationSeconds: 10,
      acceptInvitations: true,
    };

    const eufy = await EufySecurity.initialize(config);
    await eufy.connect();
    await eufy.refreshCloudData();
    const devices = await eufy.getDevices();
    console.log("devices", devices);
    response = {
      devices: devices,
    };

    return {
      statusCode: 200,
      body: JSON.stringify(response),
    };
  } catch (err) {
    console.info("err: ", err);
    // return err;
    return {
      statusCode: 500,
      body: JSON.stringify(err),
    };
  }
};

`

However, when I fire this lambda function through an HTTP trigger I get no devices in the array when I have a device registered and active against this account. 

Any sort of help would be highly appreciated.

**Comment by bropat** [comment]
Fixed in version `2.4.4`.
