### ISSUE TITLE
[Question]: RTMP CloudLiveStream migrated to WEBRTC

### ISSUE THREAD

**Issue by martijnpoppen** [bropat/eufy-security-client#317]
### Ask your question

Hey @bropat 

So once again something is patched.
The cloud livestreams which we fixed a while ago are again patched.
This time the RTMP streams do not exist anymore and everything is moved to WebRTC.
Upside is: The streams are now realtime 🎉 

I'm trying to debug the webportal code and see if i can make something useful so it might be used in this integration.

To be continued

**Comment by bropat** [comment]
@martijnpoppen 

Is there any progress here?

**Comment by martijnpoppen** [comment]
@bropat not really. Limited in time on Eufy at the moment. Have quite some projects for Homey currently

**Comment by fuatakgun** [comment]
are cloud streams used when P2P is not feasible?

**Comment by martijnpoppen** [comment]
@fuatakgun not anymore as cloud streams are webRTC now.

**Comment by OskarLebuda** [comment]
I looking how to put the stream into my app. Is there any update how should we use the webRTC stream with this plugin? 
My knowledge about the webRTC is also not that good so maybe someone can tell me how should I integrate it with my custom web app? 

Thanks for help 🫶

**Comment by bropat** [comment]
stale

**Comment by martijnpoppen** [comment]
Agreed with closing @bropat , this will probably never work again ;)
