### ISSUE TITLE
[Bug]: T8424 & T8210 Streams Stays Idle and wont connect to P2P.

### ISSUE THREAD

**Issue by kvanbiesen** [bropat/eufy-security-client#321]
### Client version

Latest avaible one in Home assistant

### Node version

same as above

### Operating System type

Other

### Operating system version

HASSOS

### Describe the bug

The state of the Camera T8424 stays idle. all the time. IF i watch tru the app or enable the stream with the button press....State stays idle

TRied from the app, i can see the video but the system doesnt update the state. It stays idle.

Also, enable motion detection doest work. when flipping the switch to on, it say not detected and flips back.

### To reproduce

2. Click on '...'

**Comment by kvanbiesen** [comment]
Updated to latest WS 1.3.5. Removed the addon and re-added it again.

Now i get more: When i press start stream....it says preparing stream and stays on preparing and is flooding he loogook on the right of the addon.
Diagnostic sensor says: Stream.PREPARING.
Webcamsensor stays black

Looks like this:

`
Back door Video Queue Size changed to 1305
18:13:20 - 4 minutes ago
Back door Video Queue Size changed to 1304
18:13:20 - 4 minutes ago
Back door Video Queue Size changed to 1303
18:13:20 - 4 minutes ago
Back door Video Queue Size changed to 1302
18:13:20 - 4 minutes ago
Back door Video Queue Size changed to 1301
18:13:20 - 4 minutes ago
Back door Video Queue Size changed to 1300
18:13:20 - 4 minutes ago
Back door Video Queue Size changed to 1299
18:13:20 - 4 minutes ago
Back door Video Queue Size changed to 1298
18:13:20 - 4 minutes ago
Back door Video Queue Size changed to 1297
18:13:20 - 4 minutes ago
Back door Video Queue Size changed to 1296
18:13:20 - 4 minutes ago
Back door Video Queue Size changed to 1295
18:13:20 - 4 minutes ago
Back door Video Queue Size changed to 1294
18:13:20 - 4 minutes ago
Back door Video Queue Size changed to 1293
18:13:20 - 4 minutes ago
Back door Video Queue Size changed to 1292
18:13:20 - 4 minutes ago
Back door Video Queue Size changed to 1291
18:13:20 - 4 minutes ago
Back door Video Queue Size changed to 1290
18:13:20 - 4 minutes ago


Back door Video Queue Size changed to 1289
18:13:20 - 4 minutes ago
Back door Video Queue Size changed to 1288
`



attached the DEBUG log (quite large, it deals with the T8424N1021291061 station)...

[T8424.log](https://github.com/bropat/eufy-security-client/files/11324761/T8424.log)

**Comment by kvanbiesen** [comment]
Noticed similar thing happing to doorbell 2K (battery but wired here)

**Comment by kvanbiesen** [comment]
@bropat foudn some time and seems like similar to the floodcam.

EVerything works fine with the eufy app, doorbell and floodcam are a nogo. The PAn & tilt's seem to works fine (over P2P)
[T8210.log](https://github.com/bropat/eufy-security-client/files/11422333/T8210.log)

**Comment by codyc1515** [comment]
I am facing the same issue with the T8423 (Eufy Security Floodlight 2K Pro). Just purchased and happy to provide logs or support in any way.

**Comment by codyc1515** [comment]
Never mind - found the issue (can't read!). I had not installed the RTSP server as described [here](https://github.com/fuatakgun/eufy_security#2-install-rtsp-simple-server-add-on---required-for-p2p-based-video-streaming---not-required-for-rtsp-based-video-streaming). I wonder if there could be some sort of time out if the status stays on pending for too long which could hint users towards this.
