### ISSUE TITLE
[Bug]: Wrong Password Protection being activated unlocks the door still

### ISSUE THREAD

**Issue by nackerr** [bropat/eufy-security-client#329]
### Client version

1.6.1

### Node version

18.13.0

### Operating System type

Linux

### Operating system version

Ubuntu 22.04

### Describe the bug

I've never used my Eufy T8520 with wrong try protection. Recently, I enabled it.

Today, my dog walker stopped by to walk my dog. She entered her password in a few times wrong, the wrong password protection got enabled, and then wa-la... Homebridge sent the "unlock" signal to my lock.

This is a serious flaw, and only happens with wrong try protection enabled. Maybe this is not handled properly in the code? I'm assuming the wrong try event is not handled properly, and homebridge eufy interprets it as an unlock which then in turn actually unlocks the door.

### To reproduce

1. Enable wrong try protection
2. Trigger wrong try protection
3. Door should unlock at this point

**Comment by bropat** [comment]
Nothing in this library sends a command without an explicit order. 
If this is the case, the cause must be sought in the application that uses this library.
