### ISSUE TITLE
eufyLog: No devices found.

### ISSUE THREAD

**Issue by semmtex** [bropat/eufy-security-client#34]
**Describe the bug**  
No devices are found. Using a guest account for Eufy which only has access to the Doorbell.

**To Reproduce**  
I installed the _samemory/homebridge-eufy-security_ plugin for HomeBridge that utilises your repo to connect to Eufy accounts. However, It seems no devices are found. I have created a guest account that has access to the Eufy Battery Powered Doorbell. I tried using _birkir/homebridge-plugin-eufy-security_ with which the Doorbell did show up in the Home app.

**Expected behavior**  
I'm expecting the doorbell to show up in HomeBridge as an accessory and thus in the Home app as well.

**Screenshots & Logfiles**  
Starting to advertise 'Homebridge 0BDF' using bonjour-hap backend!
[8/1/2021, 2:01:52 PM] Homebridge v1.3.4 (Homebridge) is running on port 51826.
{"name":"eufyLog","hostname":"redacted","pid":350,"level":30,"msg":"No stations found.","time":"2021-08-01T12:01:52.949Z","v":0}
{"name":"eufyLog","hostname":"redacted","pid":350,"level":30,"msg":"No devices found.","time":"2021-08-01T12:01:53.300Z","v":0}
{"name":"eufyLog","hostname":"redacted","pid":350,"level":30,"msg":"No stations found.","time":"2021-08-01T12:01:53.345Z","v":0}
�[0;37m[8/1/2021, 2:01:53 PM] �[0m�[0;36m[Homebridge UI]�[0m �[0;33mHomebridge Config UI X v4.41.2 is listening on 0.0.0.0 port 8124�[0m
{"name":"eufyLog","hostname":"redacted","pid":350,"level":30,"msg":"No devices found.","time":"2021-08-01T12:01:53.727Z","v":0}
{"name":"eufyLog","hostname":"redacted","pid":350,"level":30,"msg":"Push notification connection successfully established","time":"2021-08-01T12:02:04.399Z","v":0}
{"name":"eufyLog","hostname":"redacted","pid":350,"level":30,"msg":"Push notification connection successfully established","time":"2021-08-01T12:02:04.399Z","v":0}

**Versions:**  
 - Client version: 0.9.1
 - Node version: v0.9.4
 - Operating system: Docker

**Comment by bropat** [comment]
@semmtex Can you please test it with the client version 1.0.0?

**Comment by bropat** [comment]
@semmtex Have you tried the latest version?

**Comment by semmtex** [comment]
@bropat Sorry, had a busy week. Finally got the chance to try out v1.0.0-rc.0, alas to no avail. 

`Starting to advertise 'Homebridge 0BDF' using bonjour-hap backend!
[8/18/2021, 2:01:19 PM] Homebridge v1.3.4 (Homebridge) is running on port 51826.
[[37m2021-08-18T12:01:20.266Z[39m] [90mDEBUG[39m: ef/349 on v1.0.0-rc.0: [36mFound 0 stations.[39m
[[37m2021-08-18T12:01:20.266Z[39m] [90mDEBUG[39m: ef/349 on v1.0.0-rc.0: [36mFound 0 devices.[39m
[[37m2021-08-18T12:01:20.318Z[39m] [35m WARN[39m: ef/349 on v1.0.0-rc.0: [36mPush Closed![39m
[0;37m[8/18/2021, 2:01:20 PM] [0m[0;36m[Homebridge UI][0m [0;33mHomebridge Config UI X v4.41.2 is listening on 0.0.0.0 port 8124[0m
[[37m2021-08-18T12:01:21.130Z[39m] [90mDEBUG[39m: ef/349 on v1.0.0-rc.0: [36mPush Connected![39m
[[37m2021-08-18T12:01:26.260Z[39m] [90mDEBUG[39m: ef/349 on v1.0.0-rc.0: [36mPush Connected![39m
[[37m2021-08-18T12:01:26.260Z[39m] [90mDEBUG[39m: ef/349 on v1.0.0-rc.0: [36mPush Connected![39m`

**Comment by bropat** [comment]
@semmtex 

I think the problem lies in the sharing of the device. Can you share it with administrator rights for the account configured in the Homebridge plugin?

**Comment by semmtex** [comment]
@bropat I've upgraded the permission of the guest account to admin, but the problem persists. When onboarding in the HomeBridge GUI, it doesn't show any devices after connecting either...? Maybe there's something there?

**Comment by bropat** [comment]
> NEW PROBLEM: The live view will not load. It has FFMPEG installed and the preview thumbnail was loaded... any ideas?

@semmtex That's a different issue and I think it's best if you ask them.
