### ISSUE TITLE
[Question]: Is T8502 Firmware version 2.1.1.1 supported?

### ISSUE THREAD

**Issue by vivekvkk** [bropat/eufy-security-client#340]
### Ask your question

Device: Eufy Security lock T8502
Firmware version: 2.1.1.1 (2023-06-10)

Hi. I got a new security lock T8502, but in the "Eufy Security" integration, I do not see the device whereas my eufy app shows it. There is one device in the integration that says "UNSUPPORTED", but not sure if that is the lock.

Is there support for this version yet?

Thanks,
Vivek Vakkalanka.

**Comment by vivekvkk** [comment]
@bropat Can you please take a look at this when you get a chance?

**Comment by GHanthorn** [comment]
I am having the same issue as well. I have 2 T8502 (Branded as SmartLock E110) with firmware E110

**Comment by bropat** [comment]
This device is not supported as specified [here](https://bropat.github.io/eufy-security-client/#/supported_devices).
There is already a feature request [here](https://github.com/bropat/eufy-security-client/issues/291).
