### ISSUE TITLE
[Feature request]: S220 Solo Cam Support

### ISSUE THREAD

**Issue by FeromonDE** [bropat/eufy-security-client#343]
### Describe the solution you'd like

Please, can you add support for S220 Solo Cam.
I can give access.

Thanks.

**Comment by ScratMan** [comment]
Hello, I can give access to my camera too if needed.

**Comment by marcjeno1** [comment]
Hello, is this something that is being worked on?

Would like this feature as well

**Comment by ckworkshop** [comment]
Currently says: Unsupported.
S220 SoloCam, Version: 3.2.4.4

**Comment by martijnpoppen** [comment]
https://github.com/bropat/eufy-security-client/pull/353

**Comment by toshibochan** [comment]
love to see s220 working to. I have one and I want buy more. but waiting till support on homebridge.

**Comment by akno2205** [comment]
Please add support for S220 Solo can. I have a lot of them and love to see them in HomeKit. Nice work. Keep going.
