### ISSUE TITLE
[Feature request]: Use P2P to get battery level data.

### ISSUE THREAD

**Issue by ersan** [bropat/eufy-security-client#345]
### Describe the solution you'd like

Eufy hardly ever updates the cloud API with the battery level of any devices, resulting in incorrect battery levels for days or weeks at a time (my 2C camera has been at 39% for 18 days now according to the API). It would be much better if you could get battery levels via P2P instead.

**Comment by PhilippEngler** [comment]
bropat has this already implemented and it works definitively with the 2c cameras. After starting the client, it can take some minutes to grab the correct values.
Please check if
- you have a P2P connection to the base and
- you have added the "RuntimeState" listener to your station object

**Comment by ersan** [comment]
Ah, I'm using https://github.com/bropat/eufy-security-ws rather than this library.  I suppose I'll have to open an issue over there instead?

**Comment by bropat** [comment]
Fixed in version `2.7.1`.
