### ISSUE TITLE
Request: Support for Smart Lock Touch with Wifi 8520

### ISSUE THREAD

**Issue by thewolf-oz** [bropat/eufy-security-client#35]
I have recently fitted the Smart Lock Touch with Wifi (https://myanker.com.au/smart-lock-touch-wifi.html)

While the name, software version and serial number detect correctly, it appears no other information is coming through. I'm happy to assist with anything required to gather the other data

![T8520](https://user-images.githubusercontent.com/86336633/127796595-ac89f2ba-785f-4143-bb6a-e90ab9e2d7c2.png)

**Comment by thewolf-oz** [comment]
Note this screenshot is using the ioBroker integration that leverages this repo, if the issue is in ioBroker I'll move it there however I just wanted to list it here as it's not on the support list yet

**Comment by bropat** [comment]
https://github.com/bropat/ioBroker.eufy-security/issues/138

**Comment by thewolf-oz** [comment]
Thanks for that - I thought I searched and couldn't find it so good to know you're already on it :)

I'll close this off and follow the other
