### ISSUE TITLE
[Bug]: Decryption Error

### ISSUE THREAD

**Issue by nitram-rem** [bropat/eufy-security-client#350]
### Client version

1.6.0

### Node version

command not found error in console

### Operating System type

Other

### Operating system version

Hass 10.3 Core 2023.7.3

### Describe the bug

Since today after the update i get the followinf error:

2023-08-02 05:35:00.493  INFO  Eufy Security server listening on host 0.0.0.0, port 3000 
2023-08-02 05:35:00.646  ERROR Data decryption error, invalidating session data and reconnecting... 
 Error  error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
details:
{
  library: 'digital envelope routines',
  function: 'EVP_DecryptFinal_ex',
  reason: 'bad decrypt',
  code: 'ERR_OSSL_EVP_BAD_DECRYPT'
}

### To reproduce

Direkt in the log at start the error occurs.

**Comment by fuatakgun** [comment]
This is happening one time only right?

**Comment by nitram-rem** [comment]
right

**Comment by nitram-rem** [comment]
the new version from yesterday it works again. Better than bevor.

**Comment by nitram-rem** [comment]
solved
