### ISSUE TITLE
[Bug]: LOCK_8502 and LOCK_8506 shares the same ID (180)

### ISSUE THREAD

**Issue by lenoxys** [bropat/eufy-security-client#355]
### Client version

2.7.1

### Node version

18.17.0

### Operating System type

Linux

### Operating system version

Debian 11

### Describe the bug

Hello @bropat,

how are you ? Found this one while publishing into npm.

LOCK_8502 and LOCK_8506 shares the same ID (180)

It shouldn't be the case.

https://github.com/bropat/eufy-security-client/blob/master/src/http/types.ts#L66

**Comment by justinlindh** [comment]
@bropat - T8506 uses 184; patched in my PR, here: https://github.com/bropat/eufy-security-client/pull/377
