### ISSUE TITLE
[Question]: Bulk download videos with HB3

### ISSUE THREAD

**Issue by IKIKN** [bropat/eufy-security-client#358]
### Ask your question

Hi,

Is there a way with the HB3 to download multiple record videos (I'm trying to use this library because the "Archive video" feature on the app doesn't work).

When I use "device.start_download", it's asking me for a cipher, that I can't find anywhere, I tried to get the events with driver.get_video_events, but it just returns an empty events array.

What can I do? Thanks!

**Comment by bropat** [comment]
Eufy has changed some things and therefore this functionality is now deprecated.
Here everything must be reimplemented from scratch.

**Comment by bropat** [comment]
#336

**Comment by IKIKN** [comment]
Thanks for answering!
