### ISSUE TITLE
[Feature request]: eufy Security SoloCam S220, Solar Security Camera

### ISSUE THREAD

**Issue by shedman214** [bropat/eufy-security-client#361]
### Describe the solution you'd like

Can You add support for the eufy Security SoloCam S220, Solar Security Camera Please and thank you.

**Comment by NeriedAU** [comment]
PR is already in [here](https://github.com/bropat/eufy-security-client/pull/353)

**Comment by akno2205** [comment]
I would also like to see the support for the S220 solo cam. I like this project. Go one line this.
