### ISSUE TITLE
[Feature request]: Check support for Eufy 4G LTE Starlight (T8151)

### ISSUE THREAD

**Issue by witold-gren** [bropat/eufy-security-client#365]
Hey @bropat 

I have device Eufy 4G LTE Starlight (T8151) and would be happy to share it with you to check its support in this library 😀

**Comment by witold-gren** [comment]
Hey @bropat, 
I again shared my device with you 😀 I use email `patrick.broetto+eu1@gmail.com`

![image](https://github.com/bropat/eufy-security-client/assets/2304938/368fcc14-f311-4f3d-a3b0-5cd8c293c5ae)

**Comment by bropat** [comment]
@witold-gren 

I just wanted to have a look at the camera T8151, but it is also not accessible from the Eufy app. Can you have a look?

Thank you!

**Comment by witold-gren** [comment]
Hey @bropat , I again send to you invitation to my camera. Please check it now.. but to be honest I don't know why it is not accessible for you 🤔 I share with you full admin access.

**Comment by witold-gren** [comment]
I see that your account still didn't accept my invitation. I'm wondering what else I can do to give you access to the camera? I checked it with my wife, and sharing work properly 🤔

**Comment by witold-gren** [comment]
@bropat I can share with you also other cameras with I have if current share camera don't work 😀

**Comment by bropat** [comment]
Everything tested successfully

**Comment by witold-gren** [comment]
Thank you very much for a lot of work on this add-on 😁 💪🏻
