### ISSUE TITLE
[Feature request]: Solar Wall Light Cam S120

### ISSUE THREAD

**Issue by ch5k** [bropat/eufy-security-client#366]
### Describe the solution you'd like

Please add the new solar wall light cam S120.

**Comment by ibmaster** [comment]
I also would like to see standalone support for this (since can't add the device via HB3). Thanks!

**Comment by jaylara8** [comment]
+1 Thank you!

**Comment by JGargas** [comment]
+1 Thanks!

**Comment by Chrisburns75** [comment]
+1 Thanks!

**Comment by s3n3rgy** [comment]
@bropat I have the S120 and can share with you. At the moment all I see is 
Sensors - Debug (Device), Debug (Station)
Diagnostics - Reset Alarm, Trigger Alarm

name: Side Camera
model: T81A0
serialNumber: T81A0P1023*******
hardwareVersion: 1.0.0.0
softwareVersion: 1.1.6.7
type: 10005
stationSerialNumber: T81A0P1023*******
motionDetected: false
personDetected: false
personName: ''

**Comment by goncalorodrigues** [comment]
+1 Thanks

**Comment by roberohn** [comment]
+1 Thanks

**Comment by CashMichi** [comment]
+1 Thanks

**Comment by Thazar** [comment]
Hello @bropat, 
any ETA about this one?
I can share the Device with You.

**Comment by bropat** [comment]
I need someone to share the device with admin rights.

If someone wants to share it:

* patrick.broetto+eu1@gmail.com
* patrick.broetto+us1@gmail.com

**Comment by Williamysays** [comment]
Shared!
