### ISSUE TITLE
[Bug]: Door sensors not reporting

### ISSUE THREAD

**Issue by martijnpoppen** [bropat/eufy-security-client#367]
### Client version

2.8.0

### Node version

16.9

### Operating System type

Other

### Operating system version

N/a

### Describe the bug

Hey @bropat 

I got reports from my Homey users that the door sensors are not reporting for the last 14 days 

In the logs of the library i dont see any events coming in for door sensors.

Do you have any idea ?

### To reproduce

N/A

**Comment by bropat** [comment]
If you run the library in debug mode and you don't see a corresponding log entry, then I can't say where the problem is.
If you send me a log of my library, I can take a look at it.

**Comment by martijnpoppen** [comment]
Will try to get a debug report :)

**Comment by martijnpoppen** [comment]
@bropat 

Notification looks incorrect:
The content says it's open, but `sensor_open` is `false`

```
[EufyLibrary] Received push message {
  name: 'Brevlåda',
  event_time: 1693490002215,
  type: 2,
  station_sn: 'T8010NREDACTED',
  device_sn: 'T8900REDACTED',
  title: 'Eufy Security',
  content: 'Brevlåda is open',
  push_time: 1693490002547,
  channel: 16,
  cipher: undefined,
  event_session: undefined,
  event_type: 3,
  file_path: '',
  pic_url: '',
  push_count: 1,
  notification_style: undefined,
  tfcard_status: undefined,
  alarm_delay_type: undefined,
  alarm_delay: undefined,
  alarm_type: undefined,
  sound_alarm: undefined,
  user_name: undefined,
  user_type: undefined,
  user_id: undefined,
  short_user_id: undefined,
  station_guard_mode: undefined,
  station_current_mode: undefined,
  person_name: undefined,
  sensor_open: false,
  device_online: undefined,
  fetch_id: undefined,
  sense_id: undefined,
  battery_powered: undefined,
  battery_low: undefined,
  storage_type: 1,
  unique_id: undefined,
  automation_id: undefined,
  click_action: undefined,
  news_id: undefined
}
```

**Comment by Palmke** [comment]
I just opened my door and saw the event being emitted. I'm on 1.6.3 (ws project) thus 2.8.0 of the client.

**Comment by martijnpoppen** [comment]
@Palmke Homebase 2 or 3?

**Comment by Palmke** [comment]
Homebase 3

**Comment by lenoxys** [comment]
looks like an issue with a new Homebase version : 3.3.0.1h
firmware 3.2.9.5h looks fine

I still have on my setup the 3.2.9.5h and try to force to 3.3.0.1h but Eufy told me that I got the latest version. I think Eufy is doing upgrade by batch.

https://github.com/homebridge-eufy-security/plugin/issues/394#issuecomment-1703832918

**Comment by martijnpoppen** [comment]
Hi @bropat 

Made a fix for this issue: https://github.com/bropat/eufy-security-client/pull/371
