### ISSUE TITLE
[Feature request]: Support for SoloCam C210 (T8B00)

### ISSUE THREAD

**Issue by johannes1984** [bropat/eufy-security-client#369]
### Describe the solution you'd like

I would really apprechiate the support for the SoloCam C210. So far it only shows basic information in ioBroker but no possibilities for control. Thank you. 

![Bildschirmfoto 2023-08-31 um 09 38 47](https://github.com/bropat/eufy-security-client/assets/13599499/a1031c6a-053a-4cb7-8b9b-97db7230c6f4)

**Comment by aliry** [comment]
+1

**Comment by bropat** [comment]
I need someone to share the device with admin rights.

If someone wants to share it:

* patrick.broetto+eu1@gmail.com
* patrick.broetto+us1@gmail.com

**Comment by meanandpinchy** [comment]
I sent you an invitation for share with admin rights.

**Comment by heckmic** [comment]
+1

**Comment by Michael171185** [comment]
+1

**Comment by djdaz31** [comment]
Hi, i'm also interested with C210 support, thanks for your work @bropat

**Comment by mattkinnia** [comment]
+1 Looking forward to C210 support, thanks!
