### ISSUE TITLE
plugin available for hoobs ?

### ISSUE THREAD

**Issue by pcziesch** [bropat/eufy-security-client#37]
Hello i am using hoobs on my raspberry. but didn't found your plugin in the library for installing.
maybe a stupid question but iam ot a professional.

thanks

**Comment by schliemann** [comment]
@pcziesch For hoobs you can use the [Homebridge eufy security plugin](https://github.com/samemory/homebridge-eufy-securitY)

**Comment by bropat** [comment]
I don't know hoobs and @schliemann has already answered ;)
