### ISSUE TITLE
Using speaker and microphone from Eufy cam?

### ISSUE THREAD

**Issue by fragger42** [bropat/eufy-security-client#38]
Hello,
Some devices like the Eufy Solo IndoorCam 2k Pan&Tilt P24 allow two way communication. Is there some way to use the speaker and microphone of these devices by this library? I looked through the code but could not find something but maybe I overlooked something.

**Comment by bropat** [comment]
Hi,

this functionality has not yet been implemented in this library.

**Comment by bropat** [comment]
#153
