### ISSUE TITLE
[Feature request]: Add Solo Cam S340 to plugin

### ISSUE THREAD

**Issue by ccanalia82** [bropat/eufy-security-client#383]
### Describe the solution you'd like

I have a dual camera S340 that I would like to add to HomeKit via this plugin.

**Comment by casperleenheer** [comment]
Yes please!

**Comment by Quellweg22** [comment]
Yes please to use it in Home Assistant

**Comment by udouble** [comment]
For me 2!

**Comment by denzhel** [comment]
Same

**Comment by aliry** [comment]
+1

**Comment by dvincentnok** [comment]
+1 ...Just got a S340 as well.  What is involved in addng a plugin?

**Comment by doe81** [comment]
+1
looks like it is coming soon: #410
