### ISSUE TITLE
[Feature request]: SmartTrack Link (and Card)

### ISSUE THREAD

**Issue by hvorragend** [bropat/eufy-security-client#385]
Hello, I can already see smaller pieces of code, but are there plans to support the Eufy SmartTrack Link and SmartTrack Card in any form? 

Thanks so much.

**Comment by bropat** [comment]
@hvorragend 
I do not have these devices and therefore I cannot support them.
If they are sharable and someone shares them with me, I can implement them, otherwise someone has to provide me with a test account where the devices are registered and visible.
Alternatively, someone has to donate the devices to me ;)

**Comment by hvorragend** [comment]
I know the [instructions from fuatakgun](https://github.com/fuatakgun/eufy_security#debugging-issues) to get access to the systems. Technically it seems to be possible to share the device. Which email address should I use to do this?

**Comment by bropat** [comment]
One of the following:

* patrick.broetto+eu1@gmail.com
* patrick.broetto+us1@gmail.com

**Comment by hvorragend** [comment]
Thank you. I've shared my tracker with you.

**Comment by bropat** [comment]
@hvorragend 

I have now implemented the device.
What I am still missing are the push notifications.
For example, can you now run the "Find Phone" and the "Left-Behind Alarm" function?

**Comment by bropat** [comment]
Nothing happened on my end.
Did you receive a notification on your mobile phone?
For the "Find Phone" functionality, I can imagine that the notification only goes to the primary device.

**Comment by bropat** [comment]
I also think that the "Find Phone" functionality works only via Bluetooth.

**Comment by hvorragend** [comment]
> I also think that the "Find Phone" functionality works only via Bluetooth.

You are right. No push notification with Bluetooth disabled.

**Comment by bropat** [comment]
Then I think I have implemented everything (except Bluetooth).
So you can remove the sharing of the device.

Thank you!

**Comment by hvorragend** [comment]
> Nothing happened on my end. Did you receive a notification on your mobile phone? For the "Find Phone" functionality, I can imagine that the notification only goes to the primary device.

And the same with the "Left-behind-Alarm". Locating the tracker isn't possible if Bluetooth is disabled.

**Comment by hvorragend** [comment]
I would be happy if I could determine the pure presence. I was hoping to scan the trackers via BLE. But unfortunately that doesn't work. I'm excited to see what you made possible. Thank you for that.

**Comment by hvorragend** [comment]
I really would like to use these new features in HomeAssistant. Is there a release planned in the near future?

**Comment by hvorragend** [comment]
Thank you!
