### ISSUE TITLE
[Bug]: eufy-security-ws - Json

### ISSUE THREAD

**Issue by KennethSmit** [bropat/eufy-security-client#386]
### Client version

1.6.4

### Node version

10.5

### Operating System type

Other

### Operating system version

homeassistant

### Describe the bug

I'am using HomeAssistant and i'am having an error:

2023-10-13 07:03:01.235  ERROR JSON parse error 
{
  error: {
    message: 'SyntaxError: Unexpected end of JSON input',
    stacktrace: 'SyntaxError: Unexpected end of JSON input\n' +
      '    at JSON.parse (<anonymous>)\n' +

**Home Assistant 2023.10.2
Supervisor 2023.10.0
Operating System 10.5
Frontend-versie: 20231005.0**

### To reproduce

1. Go to eufy-security-ws
2. Click on logbook
3. See error

**Comment by bropat** [comment]
https://github.com/bropat/eufy-security-client/issues/344
