### ISSUE TITLE
[Feature request]: Add support for E340 (T8214) Video Doorbell Dual Camera

### ISSUE THREAD

**Issue by oschhus** [bropat/eufy-security-client#387]
### Describe the solution you'd like

Hello, would you be able to add support for the new E340 (T8214) Video Doorbell Dual Camera to your roadmap.

I'm using the homebridge-eufy-security plugin with a HomeBase 3 (S380, T8030). It works nicely with HomeKit. I have the E340, it would be great to have HomeKit access.

Thank you for your great project. I'm happy to support integration, beta etc.

**Comment by ianisms** [comment]
+1 to enable suppprt in Home Assistant via eufy_security integration

**Comment by nicoh88** [comment]
+1 to enable support in ioBroker via [ioBroker.eusec](https://github.com/bropat/ioBroker.eusec)

**Comment by Tygeray** [comment]
Thanks for a great plugin it would be good if the dual door bell e340 could be incorporated in the plugin. Keep up the good work

**Comment by jazDB** [comment]
+1 to enable support for this doorbell

**Comment by ajaymdesai** [comment]
+1 to enable support for this doorbell

**Comment by eversteegt** [comment]
+1 for support for this camera!  TBH, I was a bit disappointed to find out (when I upgraded to this camera from the old 'one lens' doorbell), that this one is not supported. But of course, I can't expect any new device from Eufy to appear so quickly. 

If you need any help or any information to help implementing this camera, I am happy to provide the information! 

I mainly use this web service in conjunction with the Home Assistant integration, to trigger 'quick response' recordings in the doorbell, and (most importantly), in an automation to turn off the mechanical chime at night.

**Comment by Be4fun** [comment]
+1 would be great to have this doorbell cam supported. Thanks !

**Comment by frenchish** [comment]
+1

**Comment by doe81** [comment]
+1

**Comment by Chuntoon1** [comment]
+1

**Comment by daichidan** [comment]
+1

**Comment by ad-infinatum** [comment]
Thanks for adding the support for this doorbell. I'm not sure if I'm doing something stupid, but I still only see the following entities in HA:
![Untitled](https://github.com/bropat/eufy-security-client/assets/152158563/8c1d2481-1e1d-4cc0-846e-9a728fd4d022)

I've tried deleting the Dufy integration as well as removing the doorbell from the Dufy app and reconnecting it, but with no success. Are others able to see the expected entities for this doorbell, to allow its use for various automations in HA?

**Comment by jimmeh2402** [comment]
Same issue for me although I am also likely doing something stupid.  Is the integration for this doorbell now supported or are further updates pending?

Thanks

**Comment by eversteegt** [comment]
> Thanks for adding the support for this doorbell. I'm not sure if I'm doing something stupid, but I still only see the following entities in HA: ![Untitled](https://private-user-images.githubusercontent.com/152158563/289955433-8c1d2481-1e1d-4cc0-846e-9a728fd4d022.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MTA1ODQsIm5iZiI6MTcwMzcxMDI4NCwicGF0aCI6Ii8xNTIxNTg1NjMvMjg5OTU1NDMzLThjMWQyNDgxLTFlMWQtNGNjMC04NDZlLTlhNzI4ZmQ0ZDAyMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyN1QyMDUxMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDQ3ZGZlNDgxODcyODkxNzc5MThmMGZiMWM4MzhlYWFjMDc1YTA1NDAwNGY5YjI3Mzg3OWE5YTlhNTQ4MDI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZDOCGkO2FTChUaEbzNtn1Q5cbX1on2vjem3sqdjO7zM)
> 
> I've tried deleting the Eufy integration as well as removing the doorbell from the Eufy app and reconnecting it, but with no success. Are others able to see the expected entities for this doorbell, to allow its use for various automations in HA?



> Same issue for me although I am also likely doing something stupid. Is the integration for this doorbell now supported or are further updates pending?
> 
> Thanks

The latest updates from @bropat  here state that the support for the E340 doorbell is tagged to the 3.0.0 milestone (which has no due date yet). So to my knowledge, it is not in any release yet (not the client itself, nor the Home Assistant addon, let alone the integration itself that depends on the addon). 

Admittedly, it is frustrating for me too because I really want to have the support. But since this and related project are all voluntary and in spare time, we'll just have to wait (although when I feel like it, I might try to see if I can fetch the related repos myself and patch/udpate manually)

**Comment by Fanan76** [comment]
I would love to have support for doorbell E340!
