### ISSUE TITLE
[Feature request]: Add support for Floodlight Cam E340 (T8425)

### ISSUE THREAD

**Issue by FlavienGARCIA** [bropat/eufy-security-client#388]
### Describe the solution you'd like

Hello,

Would it be possible to add support for the new Floodlight Cam E340 (T8425)?

Thank you.

**Comment by AwesomeNinou** [comment]
+1 🙏

**Comment by Nitnomart** [comment]
+1

**Comment by johannes281** [comment]
+1

**Comment by jascoet-mwb** [comment]
+1

**Comment by bropat** [comment]
I need someone to share the device with admin rights.

If someone wants to share it:

* patrick.broetto+eu1@gmail.com
* patrick.broetto+us1@gmail.com

**Comment by Williamysays** [comment]
Shared! / thank you for the hard work!

**Comment by Juanito3430** [comment]
Hello Bropat
If you need access let me know.
Hope you can find a solution soonest
Thank

**Comment by menno-h** [comment]
Hi, I have one as well and I would love this feature. I mean the camera is active already in Home Assistant (thank you) but I'm looking for all  features (change mode, manually switch on lights,... similarly as other full option devices).

Thanks in advance.

**Comment by bropat** [comment]
I'm already working on it.

**Comment by menno-h** [comment]
That's great, thanks!

**Comment by Raudi1** [comment]
In the last app update Eufy added support for RTSP for this camera. Not sure if that helps us here, but still a nice addition.
Can't wait for the next release where I can finally use the camera with Home Assistant. Is there any planned release date or something similar?

**Comment by codyc1515** [comment]
> In the last app update Eufy added support for RTSP for this camera. Not sure if that helps us here, but still a nice addition. Can't wait for the next release where I can finally use the camera with Home Assistant. Is there any planned release date or something similar?

RTSP Events or Continuous?

**Comment by Raudi1** [comment]
>RTSP Events or Continuous?

You can choose between both.
