### ISSUE TITLE
[Feature request]: Dual Cam Solo Video Doorbell E340 (T8214T11)

### ISSUE THREAD

**Issue by josh-blake** [bropat/eufy-security-client#390]
### Describe the solution you'd like

Looks like this is a new device that pulls away from the HomeBase requirement for doorbell support. I've picked one up to give it a shot. There's limited information available though except that it looks like it connects over 2.4G wifi and can use the HomeBase for additional storage. I'm wondering if this has better RTSP support.

**Comment by jazDB** [comment]
+1

**Comment by Stormbringer11** [comment]
+1 Would be great, when the new Doorbell works with ioBroker

**Comment by oschhus** [comment]
Note that there was a similar earlier request in issue #387, merge them?

**Comment by Stefan774** [comment]
+1 ;) thank you for your good work

**Comment by aliry** [comment]
+1

**Comment by frenchish** [comment]
+1

**Comment by mcoms** [comment]
May be solved by https://github.com/bropat/eufy-security-client/pull/406?
