### ISSUE TITLE
[Feature request]: Solocam s340 is not recognized as a camera

### ISSUE THREAD

**Issue by udouble** [bropat/eufy-security-client#392]
### Describe the solution you'd like

I notice the Solocam s340 is not supported. It is shown in HA, but not recognized as a camera, it seems.
Regards (from Belgium) - Herman

**Comment by town3r** [comment]
I'm also experiencing this issue.

Any ETA on if/when it might be supported?

**Comment by fuatakgun** [comment]
Is this listed in supported devices list? If yes, this could be an issue on my integration end, if not, this first needs to be supported here so you can use it in home assistant

**Comment by town3r** [comment]
I'm not seeing it listed at all on the device list :(

**Comment by fuatakgun** [comment]
So, i would rename this issue as a general support request.

**Comment by udouble** [comment]
Part of the learning process with HA is also how to rename an issue as a general support request:-).

**Comment by aliry** [comment]
+1

**Comment by adzybee** [comment]
+1

**Comment by town3r** [comment]
Is there anything I can do to help?

**Comment by bropat** [comment]
https://github.com/bropat/eufy-security-client/issues/383
