### ISSUE TITLE
[Question]: Decrypt video file (.dat) from the SDCard?

### ISSUE THREAD

**Issue by devdistro** [bropat/eufy-security-client#394]
### Ask your question

Looked online and ended up here. I wonder if this goal is possible?

### Goal: 
Save all video files from the memory card by decrypting, instead of using the app recording. I have about 60GB videos on the memory card, before I discovered that exporting files is a hassle from eufycam.
### Progress: 
I was able to copy memory card data on Ubuntu. All video files are shown as .dat. 
### Question: 
How to progress from here? Ideally some script that can help me run through all the files and decrypt.

### Additional Info:
**Device:** TP8400, Indoor Cam
**Version:** 2.1.9.7
**Technical handicap:** Not really a coder anymore. Can still write couple of scripts in Bash/Python.
**OS available:** Ubuntu and MacOS.
**HomeBase:** Not purchased. If needed for this, I can.

Please let me know what other info I can provide. e.g. sample of file, or folder structure...

**Comment by bropat** [comment]
Not currently supported.
