### ISSUE TITLE
[Question]: startDownload of video (.dat) with cipher_id=1

### ISSUE THREAD

**Issue by k-winkler** [bropat/eufy-security-client#395]
### Ask your question

**Goal:**
I am trying to download and decrypt encrypted videos with p2p API by using

`station.startDownload(device, path, cipherId)`

But the history reveals, that the cipherId is "1", which is not a cipher from the admin user (see attachment).
When using (non-existent) cipherId "1":

`Unable to start driver TypeError: Cannot convert undefined or null to object
    at Station.startDownload (/eufy-security-client/src/http/station.ts:3979:24)
`

and using the cipher from the admin user does not work either as the key can not be decrypted, because of the wrong cipher. I guess it is a cypher only available internally by eufy.

**Question:**
Is "station.startDownload" intended to download and decrypt stored local videos, or is it for streaming only?
Is there any other way to download and decrypt stored videos using the p2p API?
I can download these files with "station.downloadImage", but having the encrypted video (.dat) file in the end and still no cipher.

 
 
[response.json](https://github.com/bropat/eufy-security-client/files/13257435/response.json)

**Comment by bropat** [comment]
Is currently no longer supported (since the new encryption was implemented by Eufy).
