### ISSUE TITLE
[Feature request]: Add support for IndoorCam S350 (T8416)

### ISSUE THREAD

**Issue by neegool** [bropat/eufy-security-client#398]
### Describe the solution you'd like

Add support for their new line of cameras. [Here's the product link.](https://www.eufy.com/indoorcam-s350)

This is the error message: `This accessory is not compatible with HomeBridge Eufy Security plugin: Bedroom Camera Type: 104`

**Comment by Snowedin3** [comment]
I second this :)

**Comment by bropat** [comment]
@Radushka
I will let you know here as soon as I no longer need the device sharing.

**Comment by Radushka** [comment]
@bropat Thank you so much for looking into it.

**Comment by jackgopack4** [comment]
Agreed, currently shows as default HomeKit icon and says "This accessory is not currently supported by the Home app."

**Comment by bropat** [comment]
@Radushka 

I have removed the device from my site, so the sharing should be cancelled. Please verify.

**Comment by Radushka** [comment]
@bropat May you be blessed with a wonderful, happy New Year! Thank you so much! 

Sharing cancelled. Looking forward to an updated docker image: bropat/eufy-security-ws:latest

**Comment by Dutchy-79** [comment]
This already working? I have one and don't have any image or working controls.

Ty

**Comment by Dutchy-79** [comment]
It works but it's missing privacy mode. 
![Screenshot_20240303_162854_Home Assistant](https://github.com/bropat/eufy-security-client/assets/22749572/13e3857d-8e00-4012-a00c-3996ddc7f363)

**Comment by fkeijzer** [comment]
I'd think you can just use your 'camera enabled' switch for this?
At least that is how I will switch the privacy mode here.

**Comment by Dutchy-79** [comment]
Sure can though it doesn't match with the app so mistakes can be made.

**Comment by Snowedin3** [comment]
How are you using 3.0? I didn’t see a plugin update yet.

**Comment by Dutchy-79** [comment]
Latest is 1.8
https://github.com/bropat/hassio-eufy-security-ws
