### ISSUE TITLE
[Feature request]: C210 implementieren

### ISSUE THREAD

**Issue by hanwel** [bropat/eufy-security-client#415]
### Describe the solution you'd like

Zeigt leider nur die Station Values an, nicht die Camera Values. 
Danke.

<img width="1492" alt="Bildschirmfoto 2023-11-27 um 08 14 44" src="https://github.com/bropat/eufy-security-client/assets/303468/3526bd28-8fee-4b99-8671-2a32e59fa5ba">

**Comment by bropat** [comment]
https://github.com/bropat/eufy-security-client/issues/369
