### ISSUE TITLE
[Feature request]: Adding support for T8416

### ISSUE THREAD

**Issue by jvanschelven** [bropat/eufy-security-client#417]
### Describe the solution you'd like

I've got a new camera setup and sadly its not even on the devices page yet, would be cool to see it added.
If access is needed I can set things up for someone trying to test it out.

**Comment by Radushka** [comment]
+1 in the same boat. Support would be much appreciated.

**Comment by Red1-91** [comment]
Same here, would be really nice to have the new 24/7 cams also supported

**Comment by bropat** [comment]
I need someone to share the device with admin rights.

If someone wants to share it:

* patrick.broetto+eu1@gmail.com
* patrick.broetto+us1@gmail.com

**Comment by kratsching** [comment]
I thinks that's the same topic: https://github.com/bropat/eufy-security-client/issues/398

**Comment by Radushka** [comment]
> I need someone to share the device with admin rights.
> 
> If someone wants to share it:
> 
> * [patrick.broetto+eu1@gmail.com](mailto:patrick.broetto+eu1@gmail.com)
> * [patrick.broetto+us1@gmail.com](mailto:patrick.broetto+us1@gmail.com)

Done. It's the Living Room cam.
