### ISSUE TITLE
Eufy Solocam C210

### ISSUE THREAD

**Issue by jhenson1** [bropat/eufy-security-client#420]
### Ask your question

I have the Eufy integration working in HA and I have multiple s300's (3C) working properly. I added a C210 to my Homebase3 and it is shared in the Eufy app. The integration brought in the new camera but the only sensor I see in HA is "debug". Is this camera supported or can support be added?

**Comment by bropat** [comment]
https://bropat.github.io/eufy-security-client/#/supported_devices
