### ISSUE TITLE
[Feature request]: Support for C210 Smart Lock

### ISSUE THREAD

**Issue by rebeldronetech** [bropat/eufy-security-client#421]
### Describe the solution you'd like

Would support for the C210 (T8502) smart lock be able to be added?

**Comment by bbarnett444** [comment]
The C210 model T8502 is basically the same lock as the C220 model T8506 minus the fingerprint scanner.  Support for that lock is currently a [work in process](https://github.com/bropat/eufy-security-client/issues/356) so I'm hoping that the C210 will also start to work properly once the C220 is added.
