### ISSUE TITLE
[Feature request]: Adding support for eufyCam Professional E330 (T8600)

### ISSUE THREAD

**Issue by Red1-91** [bropat/eufy-security-client#422]
### Describe the solution you'd like

Is it possible to add the new eufy 24/7  2023 cams?

**Comment by bropat** [comment]
https://github.com/bropat/eufy-security-client/pull/408

**Comment by bropat** [comment]
@Red1-91 

Yes, but as I don't own the device, I need someone to share the device with admin rights.

If you want to share it, you can find one of my accounts as follows:

* patrick.broetto+eu1@gmail.com
* patrick.broetto+us1@gmail.com

**Comment by 3RROR-TINO** [comment]
> @Red1-91
> 
> Yes, but as I don't own the device, I need someone to share the device with admin rights.
> 
> If you want to share it, you can find one of my accounts as follows:
> 
> * [patrick.broetto+eu1@gmail.com](mailto:patrick.broetto+eu1@gmail.com)
> * [patrick.broetto+us1@gmail.com](mailto:patrick.broetto+us1@gmail.com)
Hab ich hinzugefügt!!!

**Comment by mbalsam** [comment]
Im considering buying the E330.   If i give you access how long will the upgrade take? How would I provide access? Hole in the firewall? or TeamViewer?
