### ISSUE TITLE
[Feature request]: Adding support for Solar Wall Light Cam S120 (T81A0)

### ISSUE THREAD

**Issue by geertsmichael** [bropat/eufy-security-client#428]
### Describe the solution you'd like

Could you please tell me if integrating the Solar Wall Light Cam S120 (T81A0) is possible?

And if possible, to add support for this model. I own one (Europe). 

Thanks.

**Comment by mcoms** [comment]
Duplicates https://github.com/bropat/eufy-security-client/issues/366. S120 has been added in https://github.com/bropat/eufy-security-client/pull/409 :)
