### ISSUE TITLE
[Question]: How to install V2.9.1

### ISSUE THREAD

**Issue by ges7881** [bropat/eufy-security-client#430]
### Ask your question

Hi everybody,

first of all, sorry for the stupid question, but I've problems to install v2.9.1. 
Iobroker always installs v1.2.1
When I try to to install 2.9.1 in expert mode, I get an error 25
When I try to install 2.9.1 via command line, it works, but I can't find the adapter in iobrokers list to create an instance?

I've updated NodeJS & NPM but I still have the issue.

What am I doing wrong?

Thanks in advance for your support.
GES

NodeJS: V18.19.0
NPM: 10.2.3

**Comment by PhilippEngler** [comment]
If you are using ioBroker, the latest ioBroker version is the version v1.2.1 and this one is shipped with this client in the version v2.9.1.
