### ISSUE TITLE
[Bug]: Eufy Security add-on crashes during extended P2P to RTSP streaming

### ISSUE THREAD

**Issue by V4ler1an** [bropat/eufy-security-client#431]
### Client version

1.7.1

### Node version

Unsure how to get this?

### Operating System type

Linux

### Operating system version

HASSIO (Fully updated)

### Describe the bug

When I P2P stream an S100 wall light camera through the RTSP Simple Server and leave it running it will always fail after a failry short amount of time. I would like to be able to have a camera stream up for longer periods. The Android Eufy mobile app seems to have no problem with this. My recent test crashed the add-on after 21 minutes. The HASSIO error is the screenshot. Eufy add-on logs have nothing because it crashed before logging any errors.

### To reproduce

1. Open the WebRTC card for the camera, click the 'Start P2P Stream' entity.
2. Wait till it falls over.
3. The moment it freezes, HASSIO registers the 'Connection to Eufy Security add-on is broken' error.
4. Eufy Security add-on is now non functional and must be restarted. The 'Watchdog' feature seems unable to recover/restart it.

### Screenshots & Logfiles

![image](https://github.com/bropat/eufy-security-client/assets/134781183/9cf39b98-b070-42d1-ba51-db0f9eb0ba6d)

### Additional context

I get these stream failures regardless of the camera. The cameras have very strong and reliable connections. The length of time the stream will run is variable. The shortest might be 5 minutes, the longest around 20.

**Comment by ronaldt80** [comment]
+1; although its not necessarily related to long term streaming; I will debug for the coming 24 hours to see if something pops up.

Right now I get the same message per above, addon remains running (50%+ CPU usage) with a log message:

`2024-01-02 10:44:44.129  INFO  Client disconnected with ip: 127.0.0.1 port: 43094 code: 1006 reason: Abnormal Closure`

**Comment by fuatakgun** [comment]
Same for me

**Comment by kloodhu** [comment]
Today i experinced the same every time a p2p streaming started. After ~3 seconds the started, immediatelly stopped (Idle state). Next streaming probe make the addon hangs and eventually crashes. In the mean time the memory consumption goes up to ~2 GB. Once i saw an error aftercrash-beforrestart. Something about java out of memory. I don't know, what changed, a few days ago there was no problem like this. Eufy api changed maybe?

**Comment by duffy6** [comment]
+1 same for me

**Comment by duffy6** [comment]
Is it really fixed for you guys?
I still experience this bug with my S100 Cam.

**Comment by duffy6** [comment]
Thx for the reply.

So someone should changed the status from "closed" to "open"

**Comment by V4ler1an** [comment]
If you're still having problems, maybe. I should clarify, my long term streaming is miles better now. I can run it indefinitely. There was a time when it wouldn't last more than 5 mins before the integration crashed. My issue now is the stream randomly failing to start. I should probably raise a new issue for that.
