### ISSUE TITLE
[Feature request]: Adding support for Video Doorbell E340

### ISSUE THREAD

**Issue by Tschaegged** [bropat/eufy-security-client#433]
### Describe the solution you'd like

Hi, I bought the new Video Doorbell E340 and I am not able to get a picture/video displayed in Home assistant. I followed all steps and the device is showing up but with limited entries:

![image](https://github.com/bropat/eufy-security-client/assets/142009881/249d50eb-de59-48f8-b050-37a5c6220c07)

Also when I try to configure again the entry in eufy security integration I get the following error:

![image](https://github.com/bropat/eufy-security-client/assets/142009881/12490180-b253-4454-b95f-d32c6e6728cf)

I started the debug protocol and will add it here
[home-assistant_eufy_security_2023-12-25T19-09-16.981Z.log](https://github.com/bropat/eufy-security-client/files/13767077/home-assistant_eufy_security_2023-12-25T19-09-16.981Z.log)

Thank you and merry Christmas!

**Comment by jimmeh2402** [comment]
Support for E340 Video Doorbell is being addressed as part of https://github.com/bropat/eufy-security-client/issues/387
