### ISSUE TITLE
[Bug]: Double login with develop-branch

### ISSUE THREAD

**Issue by PhilippEngler** [bropat/eufy-security-client#439]
### Ask your question

Hello @bropat, since two days I try to get the develop-branch with my addon. Did something changed in how to initialize the client? Everytime, the addon starts, the token is invalidated and a new token is crated, although I have set the token. The "connect"-event is fired twice. Going back to v2.9.3, the problem did not occur.

Could this have something to do with the update to the new got v13? I have also tried to update to got v14 (and node v20), but the problem still occurs.

Have you an idea where I could have to look at?

Sorry for bothering you with that.

Thanks,

Philipp

**Comment by bropat** [comment]
Hello @PhilippEngler,

> Did something changed in how to initialize the client?

No.

> Everytime, the addon starts, the token is invalidated and a new token is crated, although I have set the token. The "connect"-event is fired twice. Going back to v2.9.3, the problem did not occur.
>
> Could this have something to do with the update to the new got v13? I have also tried to update to got v14 (and node v20), but the problem still occurs.

It could be related to the update to got v13.
What I have noticed and have not had time to analyse in more detail is that the following call, which should check the validity of a token if it exists, returns an HTTP error code 403:

https://github.com/bropat/eufy-security-client/blob/516a79ea756971aa2d7fef89cd9564303fce995a/src/http/api.ts#L374-L389

If this part causes an error, the token is automatically reset and a new login attempt is made.
You could check this part more closely and find the cause.

A possible solution would be to simply replace this part as follows:

```typescript
        } else if (!this.connected && this.token || (this.tokenExpiration && (new Date()).getTime() < this.tokenExpiration.getTime())) {
            this.connected = true;
            this.emit("connect");
            this.scheduleRenewAuthToken();
        }
```

**Comment by PhilippEngler** [comment]
Thank you, @bropat for your fast answer.
After you have confirmed, that the initialization of the client has not changed, I have done a little more investigating.

I have confirmed that the token is really missing in the headers. This occurs, if the token is set by `setToken()` and after that a other value(s) from the header (e.g. `setSerial()`, `setOpenudid()`, etc.) are set. After setting this other values, the `X-Auth-Token` is missing in the headers.

I will take a closer look, why this happens and try to get a fix up running.

Again, thanks for your support and time,

Philipp

**Comment by PhilippEngler** [comment]
So, now it is running for the moment. I will watch for it for some time and then create a pull request.

The problem is in these lines ( 4 times in api.ts):
`this.requestEufyCloud.defaults.options.headers = this.headers;`

After executing, the `X-Auth-Token` disappears from header. This (I hope) can be solved by replacing the lines above by:

```
const updatedOptions = {
    headers: {
        "openudid": openudid
    }
};
this.requestEufyCloud.defaults.options.merge(updatedOptions);
```

The `setToken()` function kept unchanged.

Best

Philipp

**Comment by bropat** [comment]
Super! 💪
That was effectively a regression on my part when upgrading the got library to v13. 😅
In this case, I would suggest changing the corresponding points according to the following example:

```typescript
this.requestEufyCloud.defaults.options.merge({
    headers: {
        "openudid": openudid
    }
});
```

**Comment by bropat** [comment]
The above commit should fix it.

**Comment by PhilippEngler** [comment]
There might be a remaing problem, that eufy can now simple detect this client, because now there is the user agent in the headers (`"user-agent":"got (https://github.com/sindresorhus/got)"`)

**Comment by bropat** [comment]
You're right, but that was already the case before, or am I wrong? 😅

**Comment by bropat** [comment]
I had once set the user agent as follows and there were only problems with a few calls:

```
User-Agent: okhttp/3.12.12
```

That's why I had removed it.

**Comment by PhilippEngler** [comment]
No, there was no user-agent:
`{"app_version":"v4.6.0_1630","os_type":"android","os_version":"31","phone_model":"J725T","country":"DE","language":"de","openudid":"XY","net_type":"wifi","mnc":"XX","mcc":"CCCC","sn":"YX","model_type":"PHONE","timezone":"GMT+01:00","cache-control":"no-cache","X-Auth-Token":"THE_TOKEN"}`

I think, the user-agent is overwritten, when we set the header `this.requestEufyCloud.defaults.options.headers = this.headers;` because no user-agent is in the defined headers.

**Comment by PhilippEngler** [comment]
This might be a way to remove the user agent:
```
private headers: Record<string, string | undefined> = {
    "user-agent": undefined,
    App_version: ...
```
and

```
public getPhoneModel(): string {
    return this.headers.phone_model!;
}

public getCountry(): string {
    return this.headers.country!;
}

public getLanguage(): string {
    return this.headers.language!;
}
```

**Comment by PhilippEngler** [comment]
Regarding the doubled event occurrence, please take a look:

From what I have seen, if the query is failing with 401-error, the hook `afterResponse` is executed
https://github.com/bropat/eufy-security-client/blob/516a79ea756971aa2d7fef89cd9564303fce995a/src/http/api.ts#L142-L172

and there the `login()` function is called to receive a valid token. If the the new token was received, the first connect event is fired. Then `retryWithMergedOptions` is executed and now

https://github.com/bropat/eufy-security-client/blob/516a79ea756971aa2d7fef89cd9564303fce995a/src/http/api.ts#L377-L380

is executed and the connect event is fired again.

```
try {
    const profile = await this.getPassportProfile();
    if (profile !== null && !this.connected) {
        this.connected = true;
        this.emit("connect");
        this.scheduleRenewAuthToken();
    } else {
        this.emit("connection error", new ApiInvalidResponseError(`Invalid passport profile response`));
    }
} catch (err) {
    const error = ensureError(err);
    this.log.error("Login - getPassportProfile Error", { error: getError(error) });
    this.emit("connection error", new ApiGenericError("API get passport profile error", { cause: error }));
}
```

the `if (profile !== null && !this.connected)` should prevent the doubled event.

**Comment by bropat** [comment]
Implemented as you have suggested. Thanks!

**Comment by PhilippEngler** [comment]
Thank you. It's a great job you're doing here. :muscle: And it is always a pleasure to contribute to this project. :thumbsup:

One last thing: Maybe a switch to Got 14 is a good thing ([release notes of Got v14](https://github.com/sindresorhus/got/releases/tag/v14.0.0)). I have done the testing with the v14 and so long no error occurred.

**Comment by bropat** [comment]
Thank you very much! 
Thank you also for your contributions and feedback, which I greatly appreciate.

> One last thing: Maybe a switch to Got 14 is a good thing (release notes of Got v14). I have done the testing with the v14 and so long no error occurred.

Yes, I had already seen the new version of got. Must first check whether the switch to nodejs 20 is not too early for my other projects that use this library.

**Comment by bropat** [comment]
> Must first check whether the switch to nodejs 20 is not too early for my other projects that use this library.

Unfortunately, it is still too early to switch to node 20 (required for got v14), as the ioBroker docker container, for example, is currently only delivered with node 18.

**Comment by PhilippEngler** [comment]
I have found another error in the above code :disappointed:. Please accept my apologies.
Short: Login with correct token is fine, but when the token is invalid, there will be a error message (the connection error), which I have missed (among others because the connection is correctly established).

```
                const profile = await this.getPassportProfile();
                if (profile !== null) {
                    if (!this.connected) {
                        this.connected = true;
                        this.emit("connect");
                        this.scheduleRenewAuthToken();
                    }
                } else {
                    this.emit("connection error", new ApiInvalidResponseError(`Invalid passport profile response`));
                }
```

Now, everything should be fine (I hope so). Sorry.

> Unfortunately, it is still too early to switch to node 20 (required for got v14), as the ioBroker docker container, for example, is currently only delivered with node 18.

This was only an idea. NodeJS 18 is supported until 30th of April 2025. This might be enough time. :smiley:

**Comment by bropat** [comment]
No worries, it can happen ;)
