### ISSUE TITLE
[Feature request]: Additional functionalities for Eufy Solar Wall Light Camera S120

### ISSUE THREAD

**Issue by menno-h** [bropat/eufy-security-client#441]
### Describe the solution you'd like

Thanks for all your work on Eufy!

I have an Eufy Solar Wall Light S120. After adding the Eufy Security Integration I do see my device in Home Assistant. However there are no controls and the sensors are limited to: Debug (device) and Debug (station). There is no "Motion detected" etc. like other supported devices.

Can you add as much control/sensors as for some other devices? Such as sensor "Motion detected" and controls "light: on/off/toggle" and "Guard Mode: Home/Away/Schedule/Custom...." .

Kind regards,
Menno

**Comment by bropat** [comment]
This device will be supported in the next release of this project:

#409

In the current development line it's already supported.

**Comment by menno-h** [comment]
Nice! Looking forward to it! 
Cheers

**Comment by andys73** [comment]
Hello, I have also a camera S120 however the model reported is T81A0 and I can see it in home assistant but nothing seems to be updating and no image. 

What needs to be done to add support for that version? Thanks!
