### ISSUE TITLE
[Bug]: Outdoor Cam Pro (T8441) Sensor "Motion/Person detected" not properly working.

### ISSUE THREAD

**Issue by menno-h** [bropat/eufy-security-client#444]
### Client version

"Error while loading page info." at Settings/About

### Node version

"Error while loading page info." at Settings/About

### Operating System type

Windows

### Operating system version

Windows 11 Home 22H2

### Describe the bug

For Outdoor Cam Pro (T8441)

The sensor "Motion detected" seems to only go to "Detected" when in the Eufy App I set the Security Mode Settings to "Notification" also, instead of only "video recording".

Also "Person detected" did not change to "Detected" when there was a Human detected. In the 'event' history in the Eufy App I can see that the software dit recognize a human, but in HA the "Person detected" dit not come active. For the event with human detection, HA did give a "Detected" for the sensor "Motion detected".

Kind regards,

### To reproduce

2. Click on '...'

**Comment by bropat** [comment]
Motion detection, person detection etc. are all based on push notifications, if you deactivate the push notification you will not receive any.
