### ISSUE TITLE
T8520P Add lock or unlock option[Feature request]: 

### ISSUE THREAD

**Issue by sharpwranglers** [bropat/eufy-security-client#458]
### Describe the solution you'd like

I see the T8520P (I have T8520P not sure if its different) is not currently supported. 
I would love if you could get this device added. I am running Firmware Version 1.1.0.0
Thank you!

**Comment by sharpwranglers** [comment]
How would I provide you access?

**Comment by bropat** [comment]
@sharpwranglers 

By sharing the device with admin rights for the following account:

* patrick.broetto+us2@gmail.com

**Comment by sharpwranglers** [comment]
@bropat Ok I've added you. Thanks so much!
