### ISSUE TITLE
Support for Eufy Solocam S340 (PTZ, battery)

### ISSUE THREAD

**Issue by saschawj** [bropat/eufy-security-client#465]
### Describe the solution you'd like

Is it possible to add support for Solocam S340?
I can provide access as well as to others (E340) etc..

**Comment by borsic77** [comment]
Second this, message me if you need access to a S340.

**Comment by town3r** [comment]
Already added to the v3.0 milestone update. Just waiting its release now.

https://github.com/bropat/eufy-security-client/issues/383

**Comment by borsic77** [comment]
Ah, excellent, thank you!
