### ISSUE TITLE
[Feature request]: Support for Eufy Video Doorbell E340 (T8214)

### ISSUE THREAD

**Issue by dawn-treader** [bropat/eufy-security-client#476]
### Describe the solution you'd like

Looking for support for the new Video Doorbell E340: T8214 (not the same device as the floodlight camera E340).  Let me know if you need access to the device.  I have mine installed and powered with trickle charge.
https://ca.eufy.com/products/t8214111

**Comment by xhemp** [comment]
It's already in: https://github.com/bropat/eufy-security-client/issues/387, slated to be released on the next version.
