### ISSUE TITLE
[Feature request]:  T8170 Camera sensors added

### ISSUE THREAD

**Issue by Risotto8756** [bropat/eufy-security-client#477]
### Describe the solution you'd like

This newer outdoor PTX camera from Eufy only has debug device show up for sensors. Can you add the normal motion and other sensors?

**Comment by Risotto8756** [comment]
Also, T8160 cameras. I see sensor for vehicle motion on/off but not vehicle detected. Can you add that?

**Comment by town3r** [comment]
Already added to the Dev build.
https://github.com/bropat/eufy-security-client/issues/383

Should arrive w/ the 3.0 milestone update.

**Comment by Risotto8756** [comment]
How often are the updates released or when is the next one? Sorry for questions new here. Also great job on this. Works awesome!
