### ISSUE TITLE
Adapter

### ISSUE THREAD

**Issue by CHPhilu** [bropat/eufy-security-client#48]
Hallo

Ich hatte den Eufy Adapter installiert gehabt. Leider ging er nicht mehr online. Habe ihn gelöscht und neu insatlliert. Leider erscheint er nicht mehr. 
Kannst du mir dabei helfen?
Gelöscht habe ich ihn mit
del iobroker eufy-security
Installiert anschliessend über git.
Installation funktionierte einwandfrei. Die Ordner wurden lle wieder angelegt. Nur die Instanz erscheint nicht mehr.
Danke für deine Hilfe
Gruss Philu

**Comment by bropat** [comment]
Falsches Projekt
