### ISSUE TITLE
[Question]: Arm7 docker container for version 1.8?

### ISSUE THREAD

**Issue by HungryZebra563** [bropat/eufy-security-client#491]
### Ask your question

Not sure if this is the right place, but I noticed on dockerhub that there is a v1.8 docker container, but only for amd64 and arm64. Will there be an ARM/v7 version of the v1.8 docker container? Or has support been dropped for this architecture?

Thanks!

**Comment by bropat** [comment]
Wrong repo, but support has been discontinued due to image generation issues with GitHub Actions.
