### ISSUE TITLE
Feature Request:  Add ability to change state variable

### ISSUE THREAD

**Issue by jbrukardt** [bropat/eufy-security-client#5]
Add the ability to change eufy-security.0.CAMERA_ID.cameras.CAMERA_ID.state?  

Reading state is currently present, but changing state not yet.

State variables:
{
“0”: “OFFLINE”,
“1”: “ONLINE”,
“2”: “MANUALLY_DISABLED”,
“3”: “OFFLINE_LOWBAT”,
“4”: “REMOVE_AND_READD”,
“5”: “RESET_AND_READD”

Thank you so much in advance, great code.

**Comment by bropat** [comment]
Hi @jbrukardt,

unfortunately I can not implement this, because Eufy itself does not provide it. You can only read this attribute.
What do you want to achieve? Maybe you can achieve it in another way

**Comment by jbrukardt** [comment]
Ah thats very unfortunate.   I want to replicate the functionality in the app to turn off cameras (no live view, no recording), but have it be machine-triggerable for automation purposes.    None of the guard modes actually turn off the ability to live view, they just stop recording.

**Comment by bropat** [comment]
You have misunderstood me. I said this specific parameter is read only. Furthermore, I asked what you want to achieve to understand if this functionality is already present or not.
In the concrete case this functionality is already available through the writable state "device_enabled".

**Comment by jbrukardt** [comment]
Ah, the functionality mentioned in Eufylife.security is in fact toggling the device_enabled variable, which is already instantiated in eufy-security-client as a writable field.   I was not aware of that, I was looking at the wrong variable it appears.
