### ISSUE TITLE
[Question]: What is a correct way to get events?

### ISSUE THREAD

**Issue by BezzubovEgor** [bropat/eufy-security-client#508]
### Ask your question

First of all, thank you for this great lib, it is really useful.

I have a question about getting the history (events). Could you tell me what the correct way of getting an events list currently? I am specifically interested in getting a list of events for HB3 and S330 cameras.

I have tried to use `databaseQueryLocal` but it in the end returns the following:

```
[p2p] [P2PClientProtocol.handleDataControl] Handle DATA CONTROL - Not implemented - CMD_DATABASE message [{
  "stationSN":"XXXXXXXXXXXXX",
  "commandIdName":"CMD_DATABASE",
  "commandId":1306,
  "channel":255,
  "databaseResponse":{"mIntRet":-6006,"msg":"ERROR_NO_SUPPORT","version":"1.2.0.1"}
}]
```

At the same time `databaseQueryLatestInfo` and `databaseCountByDate` return results.

**Comment by PhilippEngler** [comment]
I have been faced this error, too. The `databaseQueryLocal` is not working with the HB3, but works fine with the HB2 and other standalone devices. At the moment, you can only the last event for the HB3 (with `databaseQueryLatestInfo`).
