### ISSUE TITLE
Sometimes some commands fail with ERROR_COMMAND_TIMEOUT

### ISSUE THREAD

**Issue by fuatakgun** [bropat/eufy-security-client#51]
Hi @bropat ,

Do you think, we can add a simple or exponential retrial mechanism into `eufy-security-client`? I have seen many warnings in docker output as below and retrial might help us to resolve this.

```
2021-10-12 14:09:22.993  WARN Station T8010NXXX - Result data for command not received 
{
  message: {
    sequence: 43,
    command_type: 1145,
    nested_command_type: undefined,
    channel: 1,
    data: <Buffer d1 00 00 2b 58 5a 59 48 79 04 88 00 00 00 01 00 01 00 00 00 01 00 00 00 00 00 00 00 64 30 64 61 38 35 64 35 62 61 31 38 33 66 32 37 37 63 33 64 37 65 ... 106 more bytes>,
    retries: 1,
    acknowledged: true,
    return_code: -133,
    timeout: Timeout {
      _idleTimeout: 20000,
      _idlePrev: null,
      _idleNext: null,
      _idleStart: 584022,
      _onTimeout: [Function (anonymous)],
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: false,
      [Symbol(refed)]: true,
      [Symbol(kHasPrimitive)]: false,
      [Symbol(asyncId)]: 11886,
      [Symbol(triggerId)]: 112
    }
  }
}
```

**Comment by bropat** [comment]
@fuatakgun 

One difference between the official app and my integration is that the app only sends one command at a time to the station, not several at once.

Example:

* App sends the 1st command
* App waits for the result of the 2nd command (spinning wheel).
* Now the user can send a command again via the app.

Perhaps the solution to the problem could be to run a send queue that is processed sequentially and only sends 1 command after the other once the result (or the command times out) of the previous command has been received.

Translated with www.DeepL.com/Translator (free version)

**Comment by rpitera** [comment]
>Perhaps the solution to the problem could be to run a send queue that is processed sequentially and only sends 1 command >after the other, once the result (or the command times out) of the previous command has been received.

This makes a lot of sense to me.  And btw, welcome back - hope you enjoyed your holiday!

**Comment by bropat** [comment]
@rpitera 

> And btw, welcome back - hope you enjoyed your holiday!

I enjoyed it very much. Maybe a little short, but better than nothing ;)

With the next version (1.2.0) that I would like to release today, I should have this problem under control :)

**Comment by rpitera** [comment]
So have you determined the issue with having a number of cams connected to one homebase?  Cause my older Arlo hub is starting to fail and I'm considering replacing them with a couple of smaller Eufycams and that's a concern for me.

**Comment by bropat** [comment]
> i am not seeing this anymore, but sometimes p2p streaming just stuck and i am not able to start it without restarting docker instance. i call start p2p livestream and ws throws an error saying that 5 seconds left and nothing arrived. Not sure if we should investigate this separately or together with timeouts

@fuatakgun 

This is a timeout I introduced if for some reason no more livestream data arrives to stop the stream internally. Without this timeout it can happen in some cases that the library still thinks that a stream is running even if it is not.

In short, this timeout has nothing to do with the other P2P timeout error ;)

**Comment by fuatakgun** [comment]
it is clear @bropat , thanks. i will create a separate issue to discuss stuck p2p case.
