### ISSUE TITLE
[Question]: Solo Indoor C210

### ISSUE THREAD

**Issue by Parrrrd** [bropat/eufy-security-client#527]
### Ask your question

I use several E220 indoor cameras and all entities are displayed. Now I have added the indoor C210 and only the Debug entity is displayed. The camera is supposed to be supported with the 3.0 update. What is my mistake?

**Comment by Parrrrd** [comment]
???

**Comment by bropat** [comment]
The Indoor C210 Cam is not supported as stated in the documentation:

https://bropat.github.io/eufy-security-client/#/supported_devices

**Comment by Parrrrd** [comment]
> The Indoor C210 Cam is not supported as stated in the documentation:
> 
> https://bropat.github.io/eufy-security-client/#/supported_devices

Will there be support in the future? Is anything planned? Thank you

**Comment by bropat** [comment]
I don't know. No.
