### ISSUE TITLE
[Question]: Differences between Solo and HB3-connected devices

### ISSUE THREAD

**Issue by PhilippEngler** [bropat/eufy-security-client#534]
### Ask your question

Hello @bropat,

today I have been run into the problem, that a device that can run as solo device or can be connected to the HB3 can have different properties. In my case, I have the T8416 (IndoorCam S350) here and when it is operated as solo device, the Property `DeviceMotionDetection` must be `[PropertyName.DeviceMotionDetection]: DeviceMotionDetectionIndoorSoloFloodProperty` and when connected to HB3, it must be `[PropertyName.DeviceMotionDetection]: DeviceMotionDetectionProperty`. The problem is, that we not allowed to use the names multiple times.

As a possible solution, we might can create a solo device with the `DeviceType` as the negative number (e.g. for T8416 `DeviceType` is `104`, so we use `-104`. Or have you something "smoother" in mind?

The check before creating the device:
```
if(resDevices[deviceSerial].device_sn === resDevices[deviceSerial].station_sn) {
    rootAddonLogger.info("We have found a solo device...", resDevices[deviceSerial].device_sn);
    if (Object.values(DeviceType).includes(resDevices[deviceSerial].device_type*-1)) {
        rootAddonLogger.info("... and the device has different values for solo and HB3 connected devices.");
        resDevices[deviceSerial].device_type = resDevices[deviceSerial].device_type*-1;
        rootAddonLogger.info(resDevices[deviceSerial].device_type.toString());
    } else {
        rootAddonLogger.info("... and the device has NO different values for solo and HB3 connected devices.");
    }
}
```

The changed types:
```
export enum DeviceType {
    //...
    INDOOR_PT_CAMERA_S350 = 104,
    INDOOR_PT_CAMERA_S350_SOLO = -104,
    //...
}

export const IndoorPanAndTiltCameraS350DefaultDeviceProperties: IndexedProperty = {
    ...GenericDeviceProperties,
    //ALL THE OTHER PROPERTIES FROM THE INDOOR_PT_CAMERA_S350
};

...

export const DeviceProperties: Properties = {
    //...
    [DeviceType.INDOOR_PT_CAMERA_S350]: {
        ...IndoorPanAndTiltCameraS350DefaultDeviceProperties,
        [PropertyName.DeviceMotionDetection]: DeviceMotionDetectionProperty,
    },
    [DeviceType.INDOOR_PT_CAMERA_S350_SOLO]: {
        ...IndoorPanAndTiltCameraS350DefaultDeviceProperties,
        [PropertyName.DeviceMotionDetection]: DeviceMotionDetectionIndoorSoloFloodProperty,
    },
    //...
}
```

Sorry for bother you with that.

Best, Philipp

**Comment by PhilippEngler** [comment]
A possible complete implementation you can find here: [7605b4b](https://github.com/PhilippEngler/eufy-security-client/commit/7605b4b54fe5b3edda1d49a8cbc9d21b83b6dfb6)

**Comment by bropat** [comment]
Hi @PhilippEngler,

What you describe here should already work.
Look here: https://github.com/bropat/eufy-security-client/blob/2c376bc8889b1f92961289b96a7bc667deda8609/src/http/device.ts#L846-L894

If it still did not work in this case, it is a bug and the cause must be found.

**Comment by PhilippEngler** [comment]
Hello bropat,

thank you for your answer. I haven't found this part. Then I will implement it for the IndoorCam S350 in this way.

Best, Philipp

**Comment by PhilippEngler** [comment]
Finished. Optionally see #535.
