### ISSUE TITLE
T8124 : SoloCam S40 Support

### ISSUE THREAD

**Issue by ckbisek** [bropat/eufy-security-client#54]
**Describe the bug**  
Massive battery drain on Eufy SoloCam S40

**To Reproduce**  
Start eufy-security-ws
Utilize eufy-security integration in HASS
[eufy.log](https://github.com/bropat/eufy-security-client/files/7338848/eufy.log)

**Comment by ckbisek** [comment]
12 hours during night
19:00 - 07:00:
eufy-security-ws is stopped
eufy-security in HASS disabled

Battery is 87%

**Comment by bropat** [comment]
@ckbisek 

I have already implemented the support for the new Solo cameras. Could you share the Solocam S40 with me so I can test it?
Where are you from? EU or US?

**Comment by paqpaqpaq** [comment]
@bropat 
Not sure whether you integration reflects 1on1 on the homebridge plugin, but using the S40 is a hit and miss.
Sometimes I need to reload a stream 4 times to eventually get a stream going. Wifi signal is excellent by the way. 
Loading a stream in the eufy app takes approx 1-2 secs.

**Comment by bropat** [comment]
@paqpaqpaq 
To understand if the problem is in my client (eufy-security-client) library, I need the debug logs from it (not other logs).

**Comment by paqpaqpaq** [comment]
> @paqpaqpaq
> To understand if the problem is in my client (eufy-security-client) library, I need the debug logs from it (not other logs).

OK, perhaps this might help then.
https://github.com/samemory/homebridge-eufy-security/issues/311#issuecomment-1007295991


This was the closes I could get to a serious output of logging. 

As for the disarming:
https://github.com/samemory/homebridge-eufy-security/issues/345#issuecomment-1025199516
