### ISSUE TITLE
[Question]: Camera not working on T8214

### ISSUE THREAD

**Issue by MirU-cell** [bropat/eufy-security-client#546]
### Ask your question

There are not "last event" camera files created, folder does exist but only contains image from last event.
Also when using Start_stream / stop_stream nothing happens. No files created, not http link in respective object - nothing.

Any idea what I'm doing wrong?

**Comment by bropat** [comment]
I don't understand what you mean by that:

> There are not "last event" camera files created, folder does exist but only contains image from last event.

No image files are created or managed in this project.

I think you're asking the question in the wrong project.

**Comment by MirU-cell** [comment]
Not sure what the classification "invalid" means. This is actually happening?
