### ISSUE TITLE
Token error: return code 401, invalidate token

### ISSUE THREAD

**Issue by marcus-j-davies** [bropat/eufy-security-client#57]
**Describe the bug**  
I seem to be not getting a clean run with setting guard mode.
I am using the examples that are present in a PR here: https://github.com/bropat/eufy-security-client/pull/19

When trying to `connect` I get the following log output.
```
Load previous login_hash:
Authenticate and get an access token
Request:
done
Response:
Switching to another API_BASE (https://security-app-eu.eufylife.com/v1) and get new token.
Renew token
Authenticate and get an access token
Request:
Response:
Response code not ok
Token error
Authenticate and get an access token
Request:
Response:
Response code not ok
Token error
Request:
Status return code 401, invalidate token
Stations - Response:
Status return code not 200
Authenticate and get an access token
Request:
Response:
Response code not ok
Token error
Request:
Status return code 401, invalidate token
Devices - Response:
Status return code not 200
```

I don't have any problem logging into the official portal (or the phone app), but I now get a captcha.
Could this be stopping a correct logon?

I have tried deleting the persistence file, but this has no affect.

This did once work, so not sure what has changed.

**Steps to reproduce**
I followed the example code

I have 2x 2K Indoor Pan/Tilt cams

**Versions**
**Node Version:** v12.22.2
**Module Version:** 1.2.1

![image](https://user-images.githubusercontent.com/55892693/139234121-2c35ef8f-608a-485b-ac63-3906557ddd9b.png)

**Comment by guny74** [comment]
@marcus-j-davies Hello, I do not get an verification code request on the webpage, but the same error. How did you solve your issue ?

**Comment by marcus-j-davies** [comment]
Hi @guny74 

To be honest - I don't really understand it.

But In the end, I created a new account (and added it as a guest)
I think maybe I was logging in too many times, in a very quick time frame.

I think the backend APIs have throttling, and will throttle for 24-48 hours on the account in question.

Changing the password (via forgot password) I think may reset the throttle.
and I also delete `persistence.json `after login in with the new password.

Just clutching at straws.
