### ISSUE TITLE
T8424 Floodlight support

### ISSUE THREAD

**Issue by yieldhog** [bropat/eufy-security-client#60]
**Describe the bug**  
Floodlight camera is seen as disabled and no commands could be sent to it.

**To Reproduce**  
Model: T8424
Device is enabled by the app, push notifications on, start livestream fails with below error. I can share stream if you need to debug.

```
2021-11-07 14:28:01.821  INFO Push notification connection successfully established 
2021-11-07 14:28:11.731  ERROR Unexpected error 
 RangeError  The value "-128" is invalid for option "size"
details:
{
  code: 'ERR_INVALID_OPT_VALUE'
}
error stack:
• buffer.js:370 alloc
    buffer.js:370:3
• utils.ts:25 stringWithLength
    node_modules/eufy-security-client/src/p2p/utils.ts:25:30
• utils.ts:102 buildIntCommandPayload
    node_modules/eufy-security-client/src/p2p/utils.ts:102:70
• session.ts:337 sendCommandWithInt
    node_modules/eufy-security-client/src/p2p/session.ts:337:25
• station.ts:2359 startLivestream
    node_modules/eufy-security-client/src/http/station.ts:2359:39
• message_handler.ts:100 handle
    src/lib/device/message_handler.ts:100:39
• server.ts:46 device
    src/lib/server.ts:46:34
• server.ts:98 receiveMessage
    src/lib/server.ts:98:58
• server.ts:57 <anonymous>
    src/lib/server.ts:57:53
• events.js:375 emit
    events.js:375:28
```

**Comment by bropat** [comment]
@yieldhog 

This device is not officially supported yet as I have not been able to test it.
Could you share your device with me on one of the following accounts:

* patrick.broetto+eu1@gmail.com
* patrick.broetto+us1@gmail.com

Let me know.

**Comment by bropat** [comment]
Just one more thing: 
I also need admin rights for this.

**Comment by bropat** [comment]
@yieldhog 

I have tested everything and everything works perfectly, including the livestream.

What version are you using?

**Comment by yieldhog** [comment]
@bropat Hm, I've been using this home assistant [add-on](https://github.com/fuatakgun/eufy_security) to access. Thank you for checking, what would be the best procedure to troubleshoot?

**Comment by fuatakgun** [comment]
it is 0.5.2 and pictureUrl is missing from properties

**Comment by bropat** [comment]
@fuatakgun 

> it is 0.5.2 and pictureUrl is missing from properties

That is not correct. It is present on this unit.

**Comment by bropat** [comment]
@yieldhog 

Are you sure you are using eufy-security-ws version 0.5.2?

**Comment by yieldhog** [comment]
@bropat I will try and test this evening

**Comment by yieldhog** [comment]
@bropat @fuatakgun --

I uninstalled everything. Installed the add-on, streaming add-on and HACS integration. I am able to start the add-ons and the integration connects to the device. (shows as idle)

After that, I went into developer / services and started livestream

```
service: eufy_security.start_livestream
data: {}
target:
  entity_id: camera.garage
```

The camera entity then shows it as streaming p2p. It also shows an RTSP livestream source in the attributes of rtsp://localhost:8554/xxxxxx

However, when I click on the camera, video never pulls up. I can run debug and show logs if that's helpful. After a few minutes I went back and it showed as idle and is no longer showing the RTSP livestream url.

**Comment by fuatakgun** [comment]
Please try VLC to validate streaming. Native streaming in HA is not working. if VLC works, install webrtc

**Comment by fuatakgun** [comment]
If you can see picture and events are working for you, please move this issue to home assistant integration repository. https://github.com/fuatakgun/eufy_security

**Comment by yieldhog** [comment]
@fuatakgun I will test this week and close out if it functions for me, have been traveling. I had to uninstall the integration as my home assistant installation had become unstable/slow -- nothing else had changed in my setup. Have you had that experience or has anyone reported similar?

**Comment by yieldhog** [comment]
I started Livestream on the camera in Home Assistant -- camera entity then said it was streaming (Stream url = rtsp://192.168.1.10:8554/T8424N10211XXXXXX) .. I used VLC and tried to connect, nothing came up. After about 3 minutes, the camera went to idle and Streaming url went to unknown.

**Comment by yieldhog** [comment]
Getting this from RTSP add-on logs:

```
2021/11/25 01:46:55 I [-1/0] [path T8424N1021XXXXXX] runOnDemand command started
2021/11/25 01:47:00 I [-1/0] [RTSP] [conn 192.168.1.203:63597] opened
2021/11/25 01:47:00 I [-1/0] [RTSP] [session 759972878] opened by 192.168.1.203:63597
2021/11/25 01:47:00 I [-1/0] [RTSP] [conn 192.168.1.203:63597] ERR: path must end with a slash (T8424N1021XXXXXX)
2021/11/25 01:47:00 I [-1/0] [RTSP] [conn 192.168.1.203:63597] closed
2021/11/25 01:47:00 I [-1/0] [RTSP] [session 759972878] closed
2021/11/25 01:47:00 I [-1/0] [RTSP] [conn 192.168.1.203:63598] opened
2021/11/25 01:47:00 I [-1/0] [RTSP] [conn 192.168.1.203:63598] closed
2021/11/25 01:47:05 I [-1/0] [RTSP] [conn 192.168.1.203:63596] ERR: source of path 'T8424N1021XXXXXX' has timed out
2021/11/25 01:47:05 I [-1/0] [RTSP] [conn 192.168.1.203:63596] closed
2021/11/25 01:47:05 I [-1/0] [path T8424N1021XXXXXX] runOnDemand command stopped
2021/11/25 01:47:05 I [-1/0] [path T8424N1021XXXXXX] destroyed
```

**Comment by yieldhog** [comment]
I have also noticed in my home assistant config directory there are now thousands of these files 'eufy_security-T8424N102XXXXXX.ts'

**Comment by fuatakgun** [comment]
@yieldhog , this is specific file based streaming but related to @bropat 's repositories, please check eufy_security custom integration to get rid of them.

Here, only focus adding support for new devices to eufy-security-client,  i will take care anything for integration inside home assistant
