### ISSUE TITLE
Issues Starting and Stopping Stream

### ISSUE THREAD

**Issue by LordNex** [bropat/eufy-security-client#68]
**Describe the bug**  
Ok let me first try and explain what I'm trying to do and my current setup. Like many of us I'm an IT person so I get most of this but I'm not a programmer by trade. I'm a Network Engineer so very familiar with Cisco, Wireshark, Fortigate, etc. 

I have several Wyze cameras already setup with RSTP through FFMPEG and eventually I plan on building a DeepStack AI Facial Recognition with a Jetson Nano soon, so I would like to be able to add this to that mix. Now I bought the 1080p version of the wired camera but it's somewhat confusing as far as their 2K camera vs the 1080p. But anyway the model number is T8201. 

I have everything setup like you have in your install script. Including the 2 conditional cards for viewing. I'm able to see all of the sensors and the last captured image. If I click on the still image it starts the generic Eufy Start Stream and the stream then progresses through the WebRTC plugin. So the problem comes after the 3 min stream and trying to reset the environment for another viewing. So after a fresh boot of HA, I can click the image and the stream works fine. If I then run camera.turn_off and turn_on accordingly, the stream still stays hung. I end up having to restart both the Eufy and RSTP add-on and then reloading the Eufy integration before everything resets and I'm able to view the stream again. That or restart HA

**To Reproduce**  
See above

**Expected behavior**  
Person clicks on latest still image captured and live stream starts, after so many min it goes back to the last image captured and if you want to view the stream again, just click the image

Or even better, click the image and it stays streaming until the person leaves the page. But can still go back, click the pic again, and get a live stream. 

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Client version: <0.5.3>
 - Node version: <node-version> 
 - Operating system: <Home Assistant>

**Additional context**

**Comment by LordNex** [comment]
Also, does anyone have an easy way to make a notification with the latest image captured? Basically I want me and my family to be able to receive an iPhone notification with a thumbnail of the image captured and a button to view live stream

**Comment by bropat** [comment]
Hi @LordNex,
i think you opened the issue in the wrong project.
Unfortunately, I can't help you with HomeAssistant because I don't use it myself.

**Comment by LordNex** [comment]
Then why is there install instructions for Home Assistant in your instructions? I can't see how this is not a HA project

**Comment by bropat** [comment]
I don't know what you mean, but I think you're confusing things.
Maybe @fuatakgun can help you.

**Comment by fuatakgun** [comment]
@LordNex , eufy-security-client is a library consumed by eufy-security-ws docker image and i have wrapped eufy-security-ws in a home assistant add-on and created an integration to communicate with add-on. So, @bropat does not have any internals of home assistant. I will go through thread and try to understand the issue.

From ownership perspective; i prefer to receive all HA related issues and triage them to check  if they are integration or add-on configuration related, if not, i am redirecting users to here.

**Comment by LordNex** [comment]
I apologize. I thought I had the right project. If you could point me to the right repository, I’d be happy to open an issue for tracking there.

Basically I’ve found that unless I reload the Integration, after the initial load and each subsequent stream, that it will no load anything except the last captured image. I’ve tried building a rest command to the HA API but haven’t had any luck getting it to actually reload the integration


On Nov 21, 2021, at 2:58 AM, Fuat Akgün ***@***.***> wrote:

﻿

@LordNex<https://github.com/LordNex> , eufy-security-client is a library consumed by eufy-security-ws docker image and i have wrapped eufy-security-ws in a home assistant add-on and created an integration to communicate with add-on. So, @bropat<https://github.com/bropat> does not have any internals of home assistant. I will go through thread and try to understand the issue.

From ownership perspective; i prefer to receive all HA related issues and triage them to check if they are integration or add-on configuration related, if not, i am redirecting users to here.

**Comment by fuatakgun** [comment]
Please check my previous message about correct repository. While doing it, double check if you had enabled notifications for motion events so integration can act on incoming push messages.

**Comment by LordNex** [comment]
@fuatakgun<https://github.com/fuatakgun>  Sorry if I’m misunderstanding. So I should look for the eufy-security-ws repository then? As far as push notifications, yes I have them enabled under the account HA uses in the Eufy Security app.


On Nov 21, 2021, at 11:52 AM, Fuat Akgün ***@***.***> wrote:

﻿

Please check my previous message about correct repository. While doing it, double check if you had enabled notifications for motion events so integration can act on incoming push messages.

**Comment by LordNex** [comment]
@fuatakgun<https://github.com/fuatakgun> I currently have the setting for notification for the event that occurred and Full Detail selected under notifications


On Nov 21, 2021, at 11:52 AM, Fuat Akgün ***@***.***> wrote:

﻿

Please check my previous message about correct repository. While doing it, double check if you had enabled notifications for motion events so integration can act on incoming push messages.

**Comment by bropat** [comment]
@LordNex 

Please open your issue here: https://github.com/fuatakgun/eufy_security
