### ISSUE TITLE
Stream not restarting

### ISSUE THREAD

**Issue by LordNex** [bropat/eufy-security-client#70]
Describe the bug

I was asked to reopen this issue here. 

Ok let me first try and explain what I'm trying to do and my current setup. Like many of us I'm an IT person so I get most of this but I'm not a programmer by trade. I'm a Network Engineer so very familiar with Cisco, Wireshark, Fortigate, etc.

I have several Wyze cameras already setup with RSTP through FFMPEG and eventually I plan on building a DeepStack AI Facial Recognition with a Jetson Nano soon, so I would like to be able to add this to that mix. Now I bought the 1080p version of the wired camera but it's somewhat confusing as far as their 2K camera vs the 1080p. But anyway the model number is T8201.

I have everything setup like you have in your install script. Including the 2 conditional cards for viewing. I'm able to see all of the sensors and the last captured image. If I click on the still image it starts the generic Eufy Start Stream and the stream then progresses through the WebRTC plugin. So the problem comes after the 3 min stream and trying to reset the environment for another viewing. So after a fresh boot of HA, I can click the image and the stream works fine. If I then run camera.turn_off and turn_on accordingly, the stream still stays hung. I end up having to restart both the Eufy and RSTP add-on and then reloading the Eufy integration before everything resets and I'm able to view the stream again. That or restart HA

To Reproduce
See above

Expected behavior
Person clicks on latest still image captured and live stream starts, after so many min it goes back to the last image captured and if you want to view the stream again, just click the image

Or even better, click the image and it stays streaming until the person leaves the page. But can still go back, click the pic again, and get a live stream.

Screenshots & Logfiles
If applicable, add screenshots and logfiles to help explain your problem.

Versions:

Client version: <0.5.3>
Node version:
Operating system:
Additional context

**Comment by fuatakgun** [comment]
hi @bropat , i had a chance to debug this issue but could not generate debug logs as my integration does not support captcha yet.

When I started p2p live stream, video data is arriving but when I stop p2p live stream, docker was hanging up and freeze. There was no way to stop the docker other than killing it. Of course, it is not responding any further commands until it is restarted. 

I had asked @LordNex to open this issue here so you can take a look.

**Comment by bropat** [comment]
I think I have found the issue. Tomorrow I will fix it.

**Comment by bropat** [comment]
@fuatakgun @LordNex 

I thought I understood what the problem was, but after taking a closer look it is not clear to me.

Can someone send me the debug logs?

**Comment by LordNex** [comment]
If you can let me know exactly what log file you need and how you need it I’d be happy to send it.

On Nov 24, 2021, at 12:32 AM, bropat ***@***.***> wrote:

﻿

@fuatakgun<https://github.com/fuatakgun> @LordNex<https://github.com/LordNex>

I thought I understood what the problem was, but after taking a closer look it is not clear to me.

Can someone send me the debug logs?

**Comment by LordNex** [comment]
﻿
﻿
﻿Sweet. Let me know if there’s anything I can do to assist. And thanks again!


On Nov 23, 2021, at 1:39 PM, bropat ***@***.***> wrote:

﻿

I think I have found the issue. Tomorrow I will fix it.

**Comment by fuatakgun** [comment]
can you implement a function to set the debug level on the fly? I can start add-on with no debug parameter and when problem starts to happen, i can change it, is this feasible?

**Comment by bropat** [comment]
@fuatakgun 

Yes, that should be possible. But this functionality does not have to be implemented here, but in the other project `eufy-security-ws`.

Can you please make an enhancement request in the other project?

Regarding this issue, I think it is correlated with issue #66 and will be fixed with its fix.

**Comment by fuatakgun** [comment]
I also on correlation, expecting to be fixed with new release, thanks for quick resolution. :clap:

**Comment by bropat** [comment]
Version 1.5.0 released which includes the fix.
