### ISSUE TITLE
T8423 Flood Light Cam 2 Pro not working

### ISSUE THREAD

**Issue by modem123pk** [bropat/eufy-security-client#75]
Describe the bug
Live Streaming is not working for Flood Light Cam 2 pro.

To Reproduce
Follow the steps to install and add a Floodlight cam 2 pro as a camera. RTSP works like a camera, when you enable and disable it, you can view it in WebRTC, however, when you click on the camera, it doesn't stream or turn on for Flood Light Cam 2 pro.

Expected behavior
Please add support for T8423N 

Camera Name: %s Front Door
Serial Number: %s XXXXX
Station Serial Number: %s XXXXXX
Last Camera Image URL: %s https://zhixin-security-pr.s3.us-west-2.amazonaws.com/thumb/2021/12/01/station/
Starting RTSP Stream
Stream URL: %s rtmp://p2p-vir-6.eufylife.com/hls/

Camera Name: %s Garage
Serial Number: %s T8423NXXXXXX
Station Serial Number: %s T8423XXXXXXXX
Last Camera Image URL: %s https://zhixin-security-pr.s3.us-west-2.amazonaws.com/thumb/2021/12/01/station/
Starting RTSP Stream
Unexpected error

**Comment by CodebyADHawk** [comment]
Also interested in added support for the Floodlight Cam Pro 2. What specifically is needed to help facilitate adding support for this model? Feel free to reach out if I can work with someone on a temporary basis.

**Comment by fabianluque** [comment]
> Also interested in added support for the Floodlight Cam Pro 2. What specifically is needed to help facilitate adding support for this model? Feel free to reach out if I can work with someone on a temporary basis.

Same here, I've just installed one of these and having same issues. Happy to help in any way I can.

**Comment by bropat** [comment]
Are you using the HomeAssistant integration of @fuatakgun?
If so, have you already opened an issue in its repository?

**Comment by CodebyADHawk** [comment]
> Are you using the HomeAssistant integration of @fuatakgun?
> 
> If so, have you already opened an issue in its repository?

This issue was opened over on that repository:

https://github.com/fuatakgun/eufy_security/issues/147

But then closed, citing support needed in this project/repository first.

**Comment by bropat** [comment]
This device is not officially supported yet as I have not been able to test it.
Could you share your device with me on one of the following accounts:

* patrick.broetto+eu2@gmail.com (for EU)
* patrick.broetto+us1@gmail.com (for US)

Let me know.

**Comment by fabianluque** [comment]
> This device is not officially supported yet as I have not been able to test it. Could you share your device with me on one of the following accounts:
> 
> * [patrick.broetto+eu2@gmail.com](mailto:patrick.broetto+eu2@gmail.com) (for EU)
> * [patrick.broetto+us1@gmail.com](mailto:patrick.broetto+us1@gmail.com) (for US)
> 
> Let me know.

I've just shared mine with you. Let me know if you need anything else.

**Comment by bropat** [comment]
@fabianluque 

I have found the problem with the livestream. I have already fixed it.

However, I see that some properties are different with this device, and this device also has unique features.

If you want, I can implement the rest step by step, but I won't hide from you that I don't have much time at the moment, so I can't tell you when I'll be done and won't need your device share.

**Comment by fabianluque** [comment]
> @fabianluque
> 
> I have found the problem with the livestream. I have already fixed it.
> 
> However, I see that some properties are different with this device, and this device also has unique features.
> 
> If you want, I can implement the rest step by step, but I won't hide from you that I don't have much time at the moment, so I can't tell you when I'll be done and won't need your device share.

Thanks @bropat for fixing the livestream. 

Of course I'd like the other features to implement if you're up for it. What timeframe are you thinking? We can work something out, no problem.

**Comment by fuatakgun** [comment]
Hey @bropat , i believe we need to wait for next release to have live stream working, right?

**Comment by bropat** [comment]
@fuatakgun 

Yes, for T8423.

Before I make a new release, I want to check a few other things.

**Comment by bropat** [comment]
@fuatakgun 

To be precise, you have to wait for 2 releases:

1. eufy-security-client
2. eufy-security-ws

**Comment by bropat** [comment]
@fabianluque 

>Of course I'd like the other features to be implemented if you're up for it. Can you elaborate on some of them?

Support for some more settings:

* Detection range
* Tracking Sensitivity
* Preset Positions
* Auto-Cruise
* Out-of-View Detection
* etc.

> What timeframe are you thinking? We can work something out, no problem.

It depends on how much time I can spare. I think a few days.

**Comment by fabianluque** [comment]
> @fabianluque
> 
> > Of course I'd like the other features to be implemented if you're up for it. Can you elaborate on some of them?
> 
> Support for some more settings:
> 
> * Detection range
> * Tracking Sensitivity
> * Preset Positions
> * Auto-Cruise
> * Out-of-View Detection
> * etc.
> 
> > What timeframe are you thinking? We can work something out, no problem.
> 
> It depends on how much time I can spare. I think a few days.

Sounds great!

**Comment by bropat** [comment]
@fabianluque 

I have implemented almost everything.
What I have not tested is whether the triggering of the camera alarm works. I'll let you test that once I've released the new version ;)

**Comment by fabianluque** [comment]
> @fabianluque
> 
> I have implemented almost everything. What I have not tested is whether the triggering of the camera alarm works. I'll let you test that once I've released the new version ;)

Hahaha, sounds good! Thank you again! Let me know if you still need access to the camera or not.

**Comment by bropat** [comment]
@fabianluque 

I no longer need access. Thank you!
