### ISSUE TITLE
The "User-Agent": "okhttp/3.12.1" seems to have been forbidden to make start_stream request

### ISSUE THREAD

**Issue by chazeon** [bropat/eufy-security-client#79]
**Describe the bug**  
The `"User-Agent": "okhttp/3.12.1"` seems to have been forbidden to make start_stream request

**To Reproduce**  
- JSON data for request body is like
  ```
  {"device_sn":".....","proto":2,"station_sn":"...."}
  ```
- Send `POST` request to `https://mysecurity.eufylife.com/api/v1/web/equipment/start_stream` without the user-agent line get the correct response
- Add the `"User-Agent": "okhttp/3.12.1"`, get 403 forbidden.

**Expected behavior**  
When send post request to `https://mysecurity.eufylife.com/api/v1/web/equipment/start_stream`, get
```json
{
  "code": 0,
  "msg": "Succeed.",
  "data": {
    "url": "rtmp://mediaserver-usa3.eufylife.com/hls/..."
  }
}
```

**Versions:**  
 - Client version: <client-version>
 - Node version: v16.13.1 
 - Operating system: Ubuntu Linux

**Relavent code:**
https://github.com/bropat/eufy-security-client/blob/8f0b05c6be2f72752db2b1b65dd6494b0553f52d/src/http/api.ts#L36-L53

**Workaroud:**
Change the user-agent or just remove the line.

**Comment by bropat** [comment]
Fix will be released in the next version
