### ISSUE TITLE
Listen for Alarm On and Off

### ISSUE THREAD

**Issue by vincedupuis** [bropat/eufy-security-client#80]
Hi,
Looking at the AlarmEvent enum, how can I know the alarm has turn ON or OFF whatever the reason.

Thanks

**Comment by Palmke** [comment]
The `HUB_STOP, HUB_STOP_BY_KEYPAD, HUB_STOP_BY_APP, HUB_STOP_BY_HAND` types are OFF reasons, the rest are ON. Just check if it's any of these and then you should be fine.
