### ISSUE TITLE
[Question]: Set Activity Zone for P&T

### ISSUE THREAD

**Issue by Palmke** [bropat/eufy-security-client#82]
### Ask your question

I noticed that pan&tilt command is known for setting the activity zone. Why is it not implemented?

I can manage to set the activity zone with upload_devs_params but still have to open the activity zone screen for the device once. I would like to remove the 'manual' step by using the p2p from this library.

Can I assist adding this logic? The format that I push is the same as the one returned in get_devs_params.

**Comment by bropat** [comment]
There is no specific reason why the activity zone has not been implemented.

I have a Pan&Tilt camera myself and can therefore implement this functionality independently.
I'll put it on the wish list ;)

**Comment by Palmke** [comment]
Came across a second command that has no handling yet: `CMD_INDOOR_PAN_CALIBRATION`.
How can I checkout what is required to send this message to the camera so I can provide this information to you?

**Comment by Palmke** [comment]
PR for calibration: https://github.com/bropat/eufy-security-client/pull/113
PR for motion zone: https://github.com/bropat/eufy-security-client/pull/112

**Comment by Palmke** [comment]
Implemented in release 2.1.0
