### ISSUE TITLE
[Feature request]: Add spotlight control for T8442

### ISSUE THREAD

**Issue by totalitarian** [bropat/eufy-security-client#85]
### Describe the solution you'd like

I have this camera where you can turn the spotlight on and off from the app. Could you add support to control the light to this project please?

https://www.amazon.co.uk/gp/product/B0911RYPYZ/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1

Camera model appears as T8442

**Comment by bropat** [comment]
@totalitarian 

This device is not officially supported yet as I have not been able to test it.
Could you share your device with me on one of the following accounts:

* patrick.broetto+eu2@gmail.com (for EU)
* patrick.broetto+us1@gmail.com (for US)

Let me know.

**Comment by bropat** [comment]
Stale
