### ISSUE TITLE
[Bug]: Ring event not sent out

### ISSUE THREAD

**Issue by Palmke** [bropat/eufy-security-client#86]
### Client version

1.4.0

### Node version

16

### Operating System type

Docker

### Operating system version

node:16-alpine

### Describe the bug

It appears the ringing event is not emitted for my T8210.
Using this client wrapped in the `eufy-security-ws:latest` Docker container, I get no event for when the doorbell is ringing.
As the WebSocket client only forwards the event, I assume the problem exists in the client. Other events like person detection get emitted just fine.

I do see this in the changed properties:
`{"type":"event","event":{"source":"device","event":"property changed","serialNumber":"T8210XXXXXXX","name":"ringing","value":false,"timestamp":1639560569432}}`

### To reproduce

1. Start the client
2. Make sure you can observe the events that are emitted (DEBUG=true eg.)
3. Press the doorbell button
4. Observe that property change events are fired and contain "rining" status changes
5. Observe that no "rings" event is emitted

### Screenshots & Logfiles
```
2021-12-15 11:04:04.657  INFO 22251 --- [lient-AsyncIO-5] c.p.a.h.s.a.e.EufyClientConnector        : Message received: {"type":"event","event":{"source":"device","event":"property changed","serialNumber":"T8210PXXXXXXXXXX","name":"ringing","value":false,"timestamp":1639562644656}}
2021-12-15 11:04:08.733  INFO 22251 --- [lient-AsyncIO-4] c.p.a.h.s.a.e.EufyClientConnector        : Message received: {"type":"event","event":{"source":"device","event":"property changed","serialNumber":"T8210PXXXXXXXXXX","name":"ringing","value":true,"timestamp":1639562648217}}
2021-12-15 11:04:20.813  INFO 22251 --- [lient-AsyncIO-6] c.p.a.h.s.a.e.EufyClientConnector        : Message received: {"type":"event","event":{"source":"device","event":"property changed","serialNumber":"T8210PXXXXXXXXXX","name":"ringing","value":false,"timestamp":1639562660812}}
```

**Comment by bropat** [comment]
@Palmke 

That's not a bug in `eufy-security-client`.
Only the event was not implemented in `eufy-security-ws`. Internally in the `eufy-security-client` library, this event is already used to set the `ringing` property. This property is of course also visible in `eufy-security-ws` (as shown above).

**Comment by Palmke** [comment]
Are you sure about that? The `ws`-repo shows a forward for `rings` event:
https://github.com/bropat/eufy-security-ws/blob/baee6164504202ccf416b814a5d7d29a1d410411/src/lib/forward.ts#L546

```
        } else if (device instanceof DoorbellCamera) {
            device.on("rings", (device: Device, state: boolean) => {
                this.clients.clients.forEach((client) =>
                    this.sendEvent(client, {
                        source: "device",
                        event: DeviceEvent.rings,
                        serialNumber: device.getSerial(),
                        state: state,
                    })
                );
            });
        }
```

**Comment by bropat** [comment]
@Palmke 

Yes, you are right. 😅

Can you please activate the debug logs, recreate the problem and send me the entire logs?
I don't have a doorbell so I can't recreate the problem.

**Comment by Palmke** [comment]
Cool, just to be sure, since I'm using the `ws`-wrapper: setting DEBUG on the Docker container is enough to get the debug logs you want? 

From https://github.com/bropat/eufy-security-ws#docker: 
```DEBUG: When the variable is set, debug mode is activated (default: unset)```

**Comment by bropat** [comment]
Yes :)

**Comment by bropat** [comment]
@Palmke Any news?

**Comment by Palmke** [comment]
Sorry man, been busy. Will test later today!

**Comment by bropat** [comment]
@Palmke 

Take your time, just wanted to check if the issue is not stale ;)

Merry Christmas

**Comment by Palmke** [comment]
@bropat got the logging. Is there an emailaddress you use to receive these logs? I don't want to attach them here openly.

**Comment by bropat** [comment]
You can find them [here](https://github.com/bropat/eufy-security-client#license).

**Comment by Palmke** [comment]
I have sent the logs to the address you linked :-)

**Comment by trullock** [comment]
I believe I have the same issue.

If you can tell me how to produce you the debug logs you require i'll send them over.

I'm using this via the HA integration: https://github.com/fuatakgun/eufy_security

Thanks

**Comment by bropat** [comment]
This is a bug in eufy-security-ws and will be fixed there.
