### ISSUE TITLE
[Question]: Alarm delay event

### ISSUE THREAD

**Issue by Palmke** [bropat/eufy-security-client#88]
### Ask your question

There are alarm events for when the alarm is actived or deactived.
However, using a Homebase, you can specify a leave and alarm delay.
For the latter a notification is created when a sensor has detected someone or something. You then have X seconds (as specified under the active guard mode) to disarm the alarm.
Does this client send out any kind of event indicating the system is in "alarm delay" state?

**Comment by bropat** [comment]
@Palmke 

> Does this client send out any kind of event indicating the system is in "alarm delay" state?

To date, I have not experimented with this myself and think that something still needs to be implemented for this.

**Comment by hipsi** [comment]
I too would find this very useful thank you.

**Comment by Palmke** [comment]
When entering alarm delay mode, the following data is sent. I don't know if this is the only time this command is used:
```
[src/eufy-security-client/src/p2p/session.ts:1405  P2PClientProtocol.handleDataControl] Station T8010XXXXXXXXXX - Not implemented - CONTROL message 
{
  commandIdName: 'CMD_GET_DELAY_ALARM',
  commandId: 1164,
  channel: 17,
  data: '060000001e000000'
}
```

Then, when configured properly by the user, you receive a notification of `CusPushEvent` in `push/types.ts` type 16: `ALARM_DELAY`:
(Field `alarm_delay_type` corresponds with a value from `AlarmEvent` in `p2p/types.ts`, in this case a door/entry sensor. `alarm_delay` corresponds with the amount of seconds set up in the app)
```
Normalized push message received
{
  name: '',
  event_time: 16443261199082,
  type: 2,
  station_sn: 'T8010XXXXXXXXXX',
  device_sn: '',
  title: 'Eufy Security',
  content: 'Homebase is going to alarm after alarm delay due to SomeDoor sensor triggered',
  push_time: 16443261199082,
  channel: undefined,
  cipher: undefined,
  event_session: undefined,
  event_type: 16,
  file_path: '',
  pic_url: '',
  push_count: 1,
  notification_style: undefined,
  tfcard_status: undefined,
  alarm_delay_type: 6,
  alarm_delay: 30,
  alarm_type: undefined,
  sound_alarm: undefined,
  user_name: undefined,
  user_type: undefined,
  user_id: undefined,
  short_user_id: undefined,
  station_guard_mode: undefined,
  station_current_mode: undefined,
  person_name: undefined,
  sensor_open: undefined,
  device_online: undefined,
  fetch_id: undefined,
  sense_id: undefined,
  battery_powered: undefined,
  battery_low: undefined,
  storage_type: 1,
  unique_id: undefined,
  automation_id: 0,
  click_action: undefined,
  news_id: undefined
}
```

I have heard other mechanisms in this client rely on the user having enabled certain notifications. If the command `CMD_GET_DELAY_ALARM` is only _ever_ used in the alarm delay situation, this alarm delay logic can be used without the notification.
If people are using motion sensors in the house, I bet they enabled this delay notification as a notification from the motion sensor keeps spamming every time the sensor is triggered.
Nevertheless, I think propagating this push notification to send out a client specific event (towards `eufy-client-ws` for example) is relatively easy.
So far I only know of the Homebase 2 device supporting this alarm logic (T8010) but probably other devices supporting a keypad will also support this.

**Comment by bropat** [comment]
Merged in development branch
