### ISSUE TITLE
[Feature request]: Support for T8221-Z and T8520

### ISSUE THREAD

**Issue by SIDADM** [bropat/eufy-security-client#89]
### Describe the solution you'd like

Submitting a feature/hardware support request for T8221-Z wifi doorbell and T8520 wifi Smart Lock.
The intergration picks up both devices and some entries, but could not steam doorbell video or lock/unlock the smart lock.

**Comment by ms30250** [comment]
I have a T8510 lock.. my integration fails to load. The addon loads and says listening but integration has an error. Curious what your looks like as it sees the T8520

**Comment by ms30250** [comment]
> I have a T8510 lock.. my integration fails to load. The addon loads and says listening but integration has an error. Curious what your looks like as it sees the T8520

Turns out the T8510 works perfectly. The addon is using container port 3000 and so is Z-wave-Js. I tried configuring it to use container 3000---->(random) but it didnt seem to work. I moved zwave from 3000---->3000 to 3000--->3500 and everything works.

**Comment by akroston** [comment]
I have 4 T8520 locks that I just got.  Ran the ws code this morning - tried this
`    socket.send(JSON.stringify({
        messageId: "lock-eet",
        command: command_2.DeviceCommand.lockDevice,
        serialNumber: "T8520...",
        value: true,
    }));`
got "device_not_supported".
Happy to test if you need @bropat

**Comment by CRMStanna** [comment]
@ms30250 , how did you get your T8510 working?  As soon as I share mine with my home assistant user, the eufy security add on starts then stops with an error.
2022-01-03 01:40:47.235  INFO Eufy Security server listening on port 3000 
2022-01-03 01:40:50.462  ERROR Station T8510Q……….8B - Response code not ok 
{
  code: 20028,
  msg: 'Failed to request.'
}
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at Function.from (node:buffer:322:9)
    at stringWithLength (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:23:35)
    at p2pDidToBuffer (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:32:18)
    at buildLookupWithKeyPayload (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:36:26)
    at P2PClientProtocol.lookupByAddress (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:227:63)
    at /usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:211:51
    at Array.map (<anonymous>)
    at P2PClientProtocol.lookup (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:211:29)
    at Socket.<anonymous> (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:290:26) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by ms30250** [comment]
> @ms30250 , how did you get your T8510 working? As soon as I share mine with my home assistant user, the eufy security add on starts then stops with an error. I have already moved zwave to another port. 2022-01-03 01:40:47.235 INFO Eufy Security server listening on port 3000 2022-01-03 01:40:50.462 ERROR Station T8510Q……….8B - Response code not ok { code: 20028, msg: 'Failed to request.' } node:internal/errors:464 ErrorCaptureStackTrace(err); ^ TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined at new NodeError (node:internal/errors:371:5) at Function.from (node:buffer:322:9) at stringWithLength (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:23:35) at p2pDidToBuffer (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:32:18) at buildLookupWithKeyPayload (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:36:26) at P2PClientProtocol.lookupByAddress (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:227:63) at /usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:211:51 at Array.map () at P2PClientProtocol.lookup (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:211:29) at Socket. (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:290:26) { code: 'ERR_INVALID_ARG_TYPE' }

All I did was install per the directions. Added and configured the addon (created a dummy account and shared my devices from my primary account to my dummy account) with my dummy account. And installed the integration via HACS.

**Comment by CRMStanna** [comment]
@ms30250 , Thanks for that.  I had created the dummy account and use that for home assistant.  Do you have the wifi bridge?  I wonder if that is what I am missing.  All my other eufy stuff (doorbell, cameras, etc) is working fine. As soon as I share the lock with the dummy account, it breaks the addin

**Comment by ms30250** [comment]
> @ms30250 , Thanks for that. I had created the dummy account and use that for home assistant. Do you have the wifi bridge? I wonder if that is what I am missing. All my other eufy stuff (doorbell, cameras, etc) is working fine. As soon as I share the lock with the dummy account, it breaks the addin

I do have the wifi bridge. The lock I have is Bluetooth only and requires Bridge to connect wifi.

**Comment by bropat** [comment]
Good news: I was able to decrypt the communication. I can now close and open the T8520 lock.
I still have to decipher and implement a few small things so that everything runs smoothly, but the hardest part is now behind me.
In the next few days I will publish the new version with support for the device.

**Comment by icortes95** [comment]
Can't wait for this support! I'm using the corresponding HomeBridge plugin and have been trying to figure out how to add support for the T8520 since I got it on sale last week. WIth this side taken care of I could maybe even try my hand at implementing the plugin side. Thank you!

**Comment by MikeJMcGuire** [comment]
Brilliant, thanks so much.

**Comment by jredondox** [comment]
> Good news: I was able to decrypt the communication. I can now close and open the T8520 lock.
> I still have to decipher and implement a few small things so that everything runs smoothly, but the hardest part is now behind me.
> In the next few days I will publish the new version with support for the device.

Hi is t8520 now supported? Thank you 🙏

**Comment by bropat** [comment]
@jredondox 

No, not yet.

**Comment by MrMichaelz** [comment]
Thank you!

**Comment by jiayuandeng** [comment]
> @ms30250 , how did you get your T8510 working? As soon as I share mine with my home assistant user, the eufy security add on starts then stops with an error. I have already moved zwave to another port. 2022-01-03 01:40:47.235 INFO Eufy Security server listening on port 3000 2022-01-03 01:40:50.462 ERROR Station T8510Q……….8B - Response code not ok { code: 20028, msg: 'Failed to request.' } node:internal/errors:464 ErrorCaptureStackTrace(err); ^ TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined at new NodeError (node:internal/errors:371:5) at Function.from (node:buffer:322:9) at stringWithLength (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:23:35) at p2pDidToBuffer (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:32:18) at buildLookupWithKeyPayload (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:36:26) at P2PClientProtocol.lookupByAddress (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:227:63) at /usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:211:51 at Array.map () at P2PClientProtocol.lookup (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:211:29) at Socket. (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:290:26) { code: 'ERR_INVALID_ARG_TYPE' }

20028 error on connecting T8510 is likely because you don't have the bridge for it. I have two T8510s, one with bridge and one without, and the error only occur to the one without bridge.

**Comment by ms30250** [comment]
> > @ms30250 , how did you get your T8510 working? As soon as I share mine with my home assistant user, the eufy security add on starts then stops with an error. I have already moved zwave to another port. 2022-01-03 01:40:47.235 INFO Eufy Security server listening on port 3000 2022-01-03 01:40:50.462 ERROR Station T8510Q……….8B - Response code not ok { code: 20028, msg: 'Failed to request.' } node:internal/errors:464 ErrorCaptureStackTrace(err); ^ TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined at new NodeError (node:internal/errors:371:5) at Function.from (node:buffer:322:9) at stringWithLength (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:23:35) at p2pDidToBuffer (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:32:18) at buildLookupWithKeyPayload (/usr/src/app/node_modules/eufy-security-client/build/p2p/utils.js:36:26) at P2PClientProtocol.lookupByAddress (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:227:63) at /usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:211:51 at Array.map () at P2PClientProtocol.lookup (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:211:29) at Socket. (/usr/src/app/node_modules/eufy-security-client/build/p2p/session.js:290:26) { code: 'ERR_INVALID_ARG_TYPE' }
> 
> 20028 error on connecting T8510 is likely because you don't have the bridge for it. I have two T8510s, one with bridge and one without, and the error only occur to the one without bridge.

I have the bridge as well and all i needed to do was change the port for Zwave. Its been working flawlessly for months.
