### ISSUE TITLE
[Question]: Does the country parameter for the client have impact on found devices?

### ISSUE THREAD

**Issue by schliemann** [bropat/eufy-security-client#92]
### Ask your question

What impact does the country parameter have? A user of the homebridge plugin thinks it might be related to not being able to find devices. The plugin hardcodes country to US, but the user lives in Denmark.

https://github.com/samemory/homebridge-eufy-security/issues/310#issuecomment-1003027316

**Comment by bropat** [comment]
@schliemann 

Yes, it has an effect. The Eufy Cloud will then redirect you to the respective "cloud of your country".
