### ISSUE TITLE
[Feature request]: please add support for keypad motion sensor

### ISSUE THREAD

**Issue by Geek-MD** [bropat/eufy-security-client#93]
### Describe the solution you'd like

Keypad has a builtin motion sensor which turns on backlight. It may be usefull to have access to that motion sensor to trigger some scenes or automations.

Is there’s any chance that battery level is reported as a numerical value instead of normal/low? So it can be informed as a percentage of maximum charge.

thanks a lot for your work

**Comment by palmtopicus** [comment]
The keypad does not communicate that it detected motion. I doubt anything can be done without modifying the firmware.

**Comment by bropat** [comment]
> Keypad has a builtin motion sensor which turns on backlight. It may be usefull to have access to that motion sensor to trigger some scenes or automations.

This is not possible according to my knowledge.

> Is there’s any chance that battery level is reported as a numerical value instead of normal/low? So it can be informed as a percentage of maximum charge.

I don't know. I would have to have access to a KeyPad to check if that is possible.

**Comment by schliemann** [comment]
@bropat I have given access to my keypad to patrick.broetto+eu2@gmail.com.

**Comment by bropat** [comment]
@schliemann 

I checked and it's not possible because the Eufy app itself doesn't have more info. Here is an excerpt of how it was implemented there:

```java

    public boolean keypadBatteryIsLow() {
        return getParamValueInt(1653) == 1;
    }

    public boolean keypadBatteryIsChrger() {
        return (getParamValueInt(1655) == 0 || getParamValueInt(1655) == 2) ? false : true;
    }

    this.f18325f = this.f18324e.keypadBatteryIsLow();
    this.f18326g = this.f18324e.keypadBatteryIsChrger();

    if (this.f18325f) {
        this.mImgBattery.setImageResource(R.drawable.ic_icon_battery_low_keypad);
    } else {
        this.mImgBattery.setImageResource(R.drawable.ic_icon_battery_high);
    }
    if (this.f18326g) {
        this.mImgBattery.setImageResource(R.drawable.ic_icon_battery_full_battery);
    }
```

You can remove the sharing. Thanks!
