### ISSUE TITLE
[Question]: Setting the volume of the indoor chime

### ISSUE THREAD

**Issue by atv2016** [bropat/eufy-security-client#95]
### Ask your question

Hi Patrick,
Many eufy devices, like the doorbell for example, have a variable named chimeHomebaseRingtoneVolume: 12

I'm trying to adjust the volume of the homebase ringtone, but it doesn't seem to update in the app (different account of course).

I tried using switch.doorbell.indoor_chime and others, and although it accepts a new value, it doesn't reflect in the app (haven't tested in real life but assume it will not update the volume.

posted this one eufy_security repo as well, but this is probably the better place for it.

**Comment by bropat** [comment]
@atv2016 

After changing the setting, did you force a refresh of the settings in the Eufy app (drag down on the main device view on Android)?
