### ISSUE TITLE
[Feature request]: Change cameraMaxLivestreamSeconds

### ISSUE THREAD

**Issue by lenoxys** [bropat/eufy-security-client#96]
### Describe the solution you'd like

Hello,

It could be nice if we can change the `cameraMaxLivestreamSeconds` variable for a longer one. Timeout is embedded within Apple Home App which provide a warning after 1min of stream if battery is append to the camera device.

**Comment by bropat** [comment]
What you are asking for already exists. See [here](https://github.com/bropat/eufy-security-client/blob/ff14851faaeb00055da6df2a3625c9fc9840458d/src/eufysecurity.ts#L500-L506).
